- Scala/HelloHere.sc
> Add scala worksheet

- C++/Prims Algorithm
It finds and prints the Minimum Spanning Tree
----
C++
> Create Prims Algorithm

- Python/ObjectTracking.py
Track an Object in a video using OpenCV and imutils Library
----
Python
> Tracking a Object in Python using OpenCV and imutils Library.

- Javascript/JS-hello-world/index.html
> Remove an extra whitespace

- Javascript/hello-from-sg.js
Export function that logs out greetings.
----
Javascript.
> hello from sg

- Javascript/helloception.js
Just an Inception Hello World :)
It was written in JavaScript
> add a inception hello world with js

- JADE/helloWord.jade
Added the JADE programming language
Prints out helo world 
----
Jade programming language
> created Jade hello world

- PHP/hello-aeimer.php
> Adds hello world for aeimer

- HelloWorld.csl
- Kusto/HelloWorld.csl
Print query result "Hello World"
----
[Kusto Query Language](https://docs.microsoft.com/en-us/azure/kusto/query/)
> Add Hello World file for Kusto query language

- PHP/pyramidWithPhp
> Print an asterisk pyramid structure with php

- Python/modular_exponentiation.py
Given 3 integers(b,p,m) as input it calculates `(b^p)%m` using modular exponentiation so that it works for large values of b,p,m.
----
Python
> Added modular_exponention.py

- C++/HTHTHTHTHTHTH
THTHTHT...HTHTH......THTHTt#include <bits/stdc++.h>
using namespace std;
int main()
{
int T;
cin >> T;
while (T--)
{
int num;
cin >> num;
char c;
c = getchar();
char a[num] = {};
int j=0; //Length of HTHT
for(int i=0;i<num;i++)
{
c = getchar_unlocked();
if(c == 'H'|| c == 'T')
{a[j] = c; j++;}
}
int marker = 0;
for(int i=0;i<j;i++)
{
if(a[i]=='H')
marker++;
if(a[i]=='T')
marker--;
}
int counter = 0;
for(int i=1;i<=j/2;i++)
{
if(a[2*i-2]=='H' && a[2*i-1]=='T')
counter++;
else counter--;
}
if(counter==(j/2) && marker==0 && (a[0]=='H' || a[0]==0) && (a[j-1]=='T'|| a[j-1]==0))
cout << "Valid\n";
else
cout << "Invalid\n";
}
return 0;
}
----
> HTHTHTHTHTH

- C++/Some snake
> Some snake

- Javascript/reverseAnArray.js
> javascript snippet to reverse an array

- C++/Hi, world!
> Update Hi, world!

- C/float_sat.c
* This function takes an float input, a min, a max and returns the same values if it is within min and max or returns the min if less than min, or max if greater than max.
* If the value is outside the min or max the valid pointer is set to zero.
* ANSI C
> Floating point saturation function

- Python/Time.py
---- This program shows current time in pygame window
---  Python(pygame)
> Added Time.py

- CSS/cssgrid.css
- CSS/cssgrid.html
Example of how CSS Grid works
----
HTML & CSS
> CSS Grid Examples

- Kotlin/HelloFromKotlin.kt
Prints "Hello from Kotlin"
Kotlin
> Hello world Kotlin

- Javascript/caesarCipher.js
Implements Caesar's cipher
JavaScript
> Caesar's cipher

- Javascript/convertToRoman.js
It converts numbers to roman numeral form
JavaScript
> Roman numeral converter

- Javascript/palindromeChecker.js
It checks for palindromes using regex
JavaScript
> palindrome checker

- Python/sqlIntro.py
It is one of my assignments from school
---- It creates a databases where it arranges the email-id with there number of occurrence 
Python 3.6
> python program to create SQL data

- Golang/animated_hello.go
Prints "Hello, world!" message one character at a time with short delay before next character printing.
----
golang
> animated hello world written in golang

- Ruby/extract-domain.rb
Extract the domain name from email address.
----
Ruby
> Extract domain name from email address - Ruby

- Javascript/JS-Task-List/app.js
- Javascript/JS-Task-List/index.html
It is a task list in JS with local storage 
----
Javascript
> Add js task list

- NodeJs/feathers.js
Simple setup for Feathersjs
----
Nodejs
> Added feathers

- C++/say_hello.cpp
Asks for user's name and prints a welcome message
C++
> Added a program that asks for your name and prints a welcome message

- LaTeX/assignment.tex
> Added tex code for assignment :P

- Bash/bulk_resize_images.sh
A tiny script that allows you to bulk resize images to a specific format using ImageMagick.
A tiny script that allows you to bulk resize images to a specific format using ImageMagick.
----
Bash
> Add Bash/bulk_resize_images.sh

- PHP/Hello World Recursive
> Hello world using recursive

- bat/helloworld.bat
> initial commit of bat

- C++/hello_world_nintyo.cpp
Displays "Hello, world"
----
C++
> Pull request

- SH/helloword_tr.sh
Add Turkish Hello World
----
SH
> Add Turkish Hello World For SH

- C++/KONI CHIWA.cpp
----Prints KONI CHIWA, world!
C++
> Koni Chiwa

- Clojure/sieve.clj
Calculates prime numbers
----
Clojure
> Clojure: Sieve of Eratosthenes

- PHP/concatenate.php
---- how to write new concatenate 
php
> add new php concatenate

- Java/MyHelloWorld.java
Prints "Hello World" in output console window
----
Java SE
> Test Commit

- factorial/factorial.py
Calculate the factorial of given number.
----
Python 3.7
> Factorial Program

- Java/HelloWorldInsideOfAPublicStaticVoidMain.java
Says Hello World in Java
----
Java
> Added a Java Hello World for Hacktoberfest 2018

- Java/DateDemo.java
format date to which format we want such as dd-MM-yyyy, yyyy-MM-dd and etc
----
java
> format date to dd-MM-yyyy

- C++/hellaworld.cpp
> Hella World C++

- Python/bfs-for-npuzzle.py
It solves the N-puzzle using Breadth First Search Method
It's written in Python
In reference to Issue #166
> add bfs heuristic for N-puzzle

- Html/hellaworld.html
Shows "Hella World!"
----
HTML
> Hella World Bois

- CodeForJava/Hello.java
combine all words into 1 sentence
----
java
> use string for sentence

- VHDL/hello_world.vhdl
> Hello World in VHDL

- Python/Hello India.py
> Update Hello India.py

- Html/Hello-world.html
save file as .html and just write anything. i will open on the browser
----
html
> Simple way to do Hello World in Html

- Java/Calculator/Main.java
Allow user to enter an input
----
Java
> add for input from user using scanner

- Python/bfs.py
Breadth First Search in Python
----
> New commit

- GO/hellow.go
Print hello world in japanese
----
GO
> added hello world in GO

- Cpp/BANK.CPP
About Banking System
It does Banking Operations
----
C++
> Added New Project

- NodeJs/hacktober.js
Prints 'HactoberFest2k18' in lower triangle fashion
NodeJs
> Created hacktober.js

- Java/myJavaPlex.java
> fibonacci series in java

- C#/MyIfElseProgram.cs
> Simple if-else program

- C#/helloMyWorld.cs
> Added my first program

- Java/semaphore/HRmanager.java
This program lets us know how to Semaphore Works in java.
#166 First Pull-request 
----
it is written completely in java
> semaphoreExample for java

- Python/raghav.py
It prints hello world
----
Python
> Added Raghav's Hello World Python Code

- JSON/helloWorld.json
> Added helloWorld.json

- Java/FibonaciRekursi.java
fibonaci with rekursi
----
java
> fibonaci Rekursi

- C++/ceaser cipher
implementation of ceaser cipher
encrytion and decryption of data.
c++
> CeaserCipher.cpp

- VueJS/Made-with-vue/index.html
It prints number of inputed times **Hello world** or inputed text.
----
`VueJs`
> Add Hello world using vue - https://made-with-love.xyz

- JSP/helloworld.jsp
> Print hello world in heading

- F#/CiaoMondo.fs
Hello, World. Italian.
----
F#
> Aggiungendo il programma Ciao Mondo

- C/random_array.c
Generates random numbers based on user input.
----
C
> Added C code to generate random numbers

- Python/TimeKeeper.py
This is a simple stopwatch script that records a start and stop time.
It also calculates the difference between the two times.
The user can also supply a description of the event.
The results are then written to a .csv as a tuple.
Simply run this script from the command line as 
```
$python3 TimeKeeper.py
```
----
Python 3.x
> Added TimeKeeper.py to Python examples.

- Chapel/hello_world.chpl
Prints "Hello, world!" to the console
Chapel
> Added Hello World in Chapel

- CRYSTAL/hello_world.cr
Signed-off-by: João Daniel <jotaf.daniel@gmail.com>
Outputs "Hello, World!" in Crystal
----
Crystal
> Add CRYSTAL hello_world

- Java/Hello_World_Applet.java
Creates a Java Applet that displays "Hello World" in gross colors.
----
Java
> Code for java update

- C#/HelloFib.cs
Simple Recursive Fibonacci that outputs Hello Worl 
----
C#
> Hello Guys

- C++/nihao.cpp
> add ni hao cpp

- PHP/hola.php
- Ruby/hola.rb
> Hello world venezuela

- Potigol/README.md
- Potigol/helloworld.poti
Print "Hello World!"
[Potigol](potigol.github.io)
> Add Hello World in Potigol

- Bash/Olá Mundo - Hello World PT BR Pascal
> Olá Mundo - Hello World PT BR Pascal

- Kotlin/HalloDunia.kt
> create Hallo Dunia in Kotlin language

- Cpp/min_hello_world.cpp
Prints Hello, world! to the screen
----
C++
> Added basic hello world to Cpp.

- C++/A-small-step-towards-calculators.txt
- C++/desktop.ini
- C++/helloworld_basic.cpp
#33
Simple Hello-World Program
c++
> Simple hello world program

- Javascript/Promise.js
Returns a promise resolve
----
Javascript
> Add Javascript Promise example

- Kotlin/hello.kt
prints out Hello, World!
----
Kotlin
> created hello-world in Kotlin

- Javascript/dots/canvas.js
- Javascript/dots/index.html
Create animated dots on the screen using the `requestAnimationFrame` API
----
JavaScript
> Javascript Dots

- Kotlin/ListFilteringExample.kt
- Kotlin/SingletonExample.kt
This is a Singleton example written in Kotlin.
> Add - Singleton example

- C++/Heapsort_PriQ.cpp
- C/Longest Common Sub-sequence.c
> Added 2-in-1 Max_Priority Queue & Heapsort

- C++/L0G1C4LABHAY.cpp
> Wrote my version of Hello World.

- Clojure/Hello-World.clj
Prints "Hello World" to the console.
----
Clojure
> Machine readable hello world in Clojure.

- LOLCODE/scary.lol
Fizzbuzz script for halloween
LOLCODE
> LOL FizzBuzz

- Javascript/helloWorld.ga.js
Create Hello World in Irish Language
----
> Create Hello World in Irish Language

- C++/SlowPrinter.cpp
- Kotlin/greetings.kt
Using a function that takes as a parameter a name to say "Hello, yourName"
----
Kotlin
> added hello in kt with function

- C++/swap_pointer.cpp
A C++ program to swap two numbers using pointers
C++
> Add program to swap two numbers using pointers

- Javascript/factoriel.js
A simple factorial script
----
Javascript
❤️
> Adding a french factoriel Javascript script

- C/Simple_Linked-list
Very simple linked list with automatic sorting.
Linked List Bro
----
C
> Simple Linked List

- C/Queue_Simple_code
First in last out
Simple program with queue logic
----
C
> Simple Queue code for christ sake

- C/floydwarshall.c
The Floyd Warshall Algorithm is for solving the All Pairs Shortest Path problem.
The problem is to find shortest distances between every pair of vertices in a 
given edge weighted directed Graph.
----
C
> Floyd warshall algorithm implementation in c

- Python/DynamicArray.py
> updated code

- Java/GenericQuickSort
> Implement QuickSort for generic arrays

- Java/Mathematics/BigIntegerGCD.java
----calculate gcd of bigintegers
java
> adds gcd method for bigintegers

- Scala/hellofunction.scala
> Scala function added

- C++/hello-universe.cpp
displays hello universe
----
C++
> added hello-universe file

- Html/Bouncing_Ball.html
> updated bouncing_ball.html

- CSS/Untitled.css
> updated @hacktobefest

- (12)Web-css/index.html
> updated @hacktoberfest

- Efene/hello_efene.fn
A simple hello world
----
Efene http://efene.org/
> add efene hello world

- Html/hello-world.html
- Html/hello-world2.html
- Html/hello-world3.html
- Html/hello-world5.html
> Created a Hello World HTML Page with images and flashing text

- Javascript/HelloWorldJL
Hello World print to console
----
javascript
> helloworldJL.js

- Python/HW_SO.py
prints Hello world and my name
----
Python
> contributed

- mahek/mahek.cpp
> insertion sort c++ program

- ArnoldC/hello.arnoldc
- Java/HWorld
> Add Hello World

- Python/printhelloworld
> Print Hello World n times

- Visual Basic/ASCII Hello World
Prints ASCII bubble text hello world
----
Visual Basic
> Adds fancy vb ascii art Hello World

- FSharp/fsharp-hello-world.sln
- FSharp/fsharp-hello-world/Program.fs
- FSharp/fsharp-hello-world/fsharp-hello-world.fsproj
> FSharp Hello World

- C++/helloworldinc.cpp
it prints hello world o the screen
----
it is written in C plus plus.
> created a hello world program in cpp #hactoberfest

- C++/hello_world!.cpp
creates a hello world program in c++
----
c++
> created hello_world.cpp

- Python/googlesheetsparser.py
parses a google sheet for shift lengths
----
python
> added google sheet parser

- Java/CountingChanges.java
> Add Counting Changes algorithm in Java

- Python/GradientDescent.py
Manual Gradient Descent Algorithm in Python using only NumPy Library.
----
Python
> Gradient Descent using NumPy in Python

- NodeJs/pull-request-tutorial.js
Teach the user how to make a pull request on GitHub.
----
NodeJS.
> Create NodeJS pull request tutorial

- C++/euler_totient_fun.cpp
euler_totient_function
----
C++
> euler_totient_function

- C++/dfs_recursive.cpp
> Depth_first_search

- C++/Binary Index Tree (Fenwick Tree).cpp
- C++/Miller Rabin Test.cpp
Added Binary Index Tree also commonly known as Fenwick Tree
This can calculate prefix sums in O(log2(N)) time and also supports update operation in O(log2(N)) time while using only O(N) space.
Written in C++
> Added Binary Index Tree (Fenwick Tree) implementation and Miller Rabin Primarility check Algorithm

- Python/flatHelloWorld.py
It seems python is saying the world is flat 🤔
> Python says the world is flat 

- Python/helloWorldDutch.py
> Dutch translation for helloworld

- Kotlin/loops.kt
The program is a basic example for different methods to iterate a for loop 
----
Kotlin
> Kotlin for-loops

- Html/Coloring Page.html
- Python/HelloMisterWorld.py
Something i made in school when bored a while ago,
You can press the screen and it changes color 
> The kids love it!
> Coloring page

- Python/hello_world_tr.py
Added Turkish Hello World
----
Python
> Add Turkish Hello World For Python

- Javascript/hello-world-tr.js
Added Turkish Hello World
----
JavaScript
> Add Turkish Hello World For JS

- C++/hello5.cpp
> commit - 5

- C++/hello4.cpp
> commit - 4

- C++/hello3.cpp
> commit - 3

- C++/hello1.cpp
> commit - 2

- C++/hw.cpp
- C++/hw1.cpp
> commit - 1

- Html/HUMANS VS MACHINES
- Html/helloworldallen.html
> Update HUMANS VS MACHINES

- Java/HelloWorldMys.java
malay translation for hello world
----
java
> malay translation

- Python/yo_world.py
Prints "Yo world!" to the console
----
Python
> Add yo_world.py

- Javascript/FastandFurious
> Create Fast and Furious

- NodeJs/map.js
Just map over an array and print to the console
----
NodeJS
> Add map example in js

- Machine Code/Binary.md
Added a Machine code folder, and a binary example of Hello, World!
> Added a Machine code folder, and a binary example of Hello, World!

- CSS/hello.css
> ; was missing

- Python/fancypig.py
- Python/temps.py
- R/Hello-in-R.r
> Temperature converter

- Python/fancypig.py
- R/Hello-in-R.r
> Patch-- added pig latin translator

- PHP/Hello PHP/index.php
The Closing Bracket was missing, so I added one. xD
not have a defined document type
----
html
> Added Doc type

- Python/HelloBaseballFans.py
- R/hello_baseball_fans.rmd
> Hello_Baseball_Fans

- Clojure/macros.clj
It's just a collection of clojure macros that I feel like sharing.
----
Clojure
> Share some clojure macros that I find useful

- PHP/geriadam.php
The Closing Bracket was missing, so I added one. xD
The program would not have a defined end
----
php
> Added PHP Closing Bracket

- Elm/hello.elm
Says hello world in Elm
----
Elm
> Add type annotation for clarity

- C++/A-small-step-towards-calculators.txt
- C++/desktop.ini
- C++/helloworld_basic.cpp
- C++/multiples of 3& 5.cpp
#33  What the program do ?
Program finds out multiples of 3 & 5 among entered numbers
----
c++
> Multiples of 3 & 5

- C++/A-small-step-towards-calculators.txt
- C++/Largest_prime_factor.cpp
- C++/desktop.ini
- C++/helloworld_basic.cpp
#33  What the program do ?
Program finds out the largest prime factor among entered numbers
----
c++
> LARGEST PRIME FACTOR

- AsciiDoc/helloworld.adoc
Print Hello World
----
AsciiDOC
> Hello World in AsciiDOC

- C/Insert_and_Delete_with_BubbleSorting
Not that much, it has bubble sort and uses linear search to delete array values.
Insert and Delete with Bubble Sorting
----
C
> Insert and Delete with Bubble Sorting

- Perl/Factorial.pl
Iteratively get the factorial of a number n.
----
Perl
> Factorial in Perl

- C/infix/push-and-pop-with_infix_to_postfix
The name says it all.
The name says it all.
----
It is written in C.
> Push-Pop_Infix_Postfix_viceversa

- C++/A-small-step-towards-calculators.txt
- C++/A-smallstep toward calculators.h
- C++/desktop.ini
- C++/helloworld_basic.cpp
#33  What the program do ?
Two string of the form x+y or x-y. x and y are single-digit non-negative integers. given code performs the addition or subtraction accordingly and print the result.
written in
C++
> A small step towards calculators

- C#/HelloWorldInBlue.cs
prints hello world with blue foreground colour
----
c#
> HELLO WORLD IN BLUE #H18

- Javascript/gamergb.html
- Python/ImageDownloader.py
A simple interactive game made with Javascript HTML and CSS stack Which is not only fun to play but also helps practicing RGB color code guess.
----A simple Javascript game to guess RGB color codes Helps to get familiar to RGB color codes
Javascript , HTML and CSS
> Added few Simple Yet Fun codes

- Javascript/BST/inOrderTraversal.js
- Javascript/BST/makeBST.js
Binary Search Tree Constructor, Add node method, and inOrder Traversal 
----
JavaScript
> added binary search tree

- Javascript/tasks list/app.js
- Javascript/tasks list/index.html
Its a simple task list using local storage to store data temporarily.
----
HTML,Bootstrap,javascript
> task list using javascript

- Kotlin/HelloWorldID.kt
Print Hello World.
----
kotlin
> Another Hello World from Indonesia!

- Bash/dateintimestamp.sh
print date in timestamp
----
Bash
> created date in timestamp

- Javascript/helloh4ckw0rld.js
Added hacker speak JS
----
Javascript
> Added Hello World h4ck3r script

- C/hello_people.c
Print a "Hello World" in Portugese
C
> New Hello World in Portugues

- ASP/HelloWorld.asp
> Hello World in ASP

- C++/segment_tree.cpp
> segment_tree implimentation

- Bash/calculator.sh
This is demo of Calculator in Bash Script.
----Basic Calculation like Addition,Substraction,Mutiplication,and Division
----BASH
> added new file calculator.sh

- Rust/hello_rusty.rs
> for Hacktoberfest

- C/Hello_World_TR.c
Added Turkish Hello World
----
C
> Add Turkish Hello World For C

- Java/Helloworld_malayalam.java
Prints hello world in malayalam
----
Java
> Hactoberfest2018: Program to print hello world in malayalam

- Java/Hello-world.java
- Java/Hello-world_itsme.java
I added Hello world Its me program.
----
Java
> Added My first change.

- Lua/vingador.lua
> :sparkles: Hello world my vingadores!

- Bash/ilikebash.sh
says Hello, writes "I like bash, a lot." backwards. ( rev )
----
bash!
> Added a greeting

- PugJS/README.md
> PugJS Add Readme

- Html/pengaturanwaktu.php
set the tie of the current location
PHP
> add html php time

- D/HolaMundo-Peru.d
- Javascript/hola-mundo-peru.js
print on console hello world
Javascript
> Hola mundo peru  by arsevys

- Javascript/array-intersect.js
Given two arrays, it returns another array with the intersection of the given arrays
----
Javascript
> Create array intersect function

- Java/databaseconnectiveity/Main.java
- Java/databaseconnectiveity/School.java
----enables database connectivity with oracle
java
> adds school class for database connectivity

- CSS/robotAnimation.html
It adds a simple html + css animation file.
----
HTML and CSS.
> Add css robot animation

- Python/hello-worlds.py
Prints 'hello world'
----
Python!
> Add hworlds!

- Java/anagrams.java
----determines if two strings are anagrams
java
> determines if given strings are anagrams

- C/swap_function.c
- Python/Bubble_sort.py
swap adress int, function in c
bubble sorting array of int in python
python, c
> swap: langage C, bubble sort: langage python

- C++/circular queue.cpp
it prints the circular queue.
----
c++
> added another file: circular queue

- Lua/HelloWorld_TR.lua
Added Turkish Hello World
----
LUA
> Add Turkish Hello World For LUA

- Python/roundHelloWorld.py
- Python/squareWorld.py
Python seems to be claiming the world is round but also square
> Python seems to be claiming the world is round but also square

- Javascript/MyDogNamedBella
> Create New Dog Name

- C++/sidp.cpp
The program just outputs "Hello World!"
It is written in C++.
> Sid's changes!

- Python/HelloLocalLang.py
Prints Hello World in Telugu, an Indian language
----
Python
> Hello World Telugu

- Javascript/hello-jackie.js
Logs a string to the console.
----
JavaScript
> happy hacktoberfest!

- Arduino/2_Bit_Adder.ino
Program Takes two 2 bit numbers and adds them to give a 3 bit Number
Written in C that is readable by Arduino
> Added 2 Bit Adder for Arduino

- Visual Basic/Hello World - glitzeeule
say hello my username
----
visual basic
> adding a file that will say hello my username

- Javascript/Shot balloons game/index.html
- Javascript/Shot balloons game/script.js
- Javascript/Shot balloons game/style.css
It is a balloon shot game in the browser with score, runs forever if you want.
----
Javascript
> Add javascript balloon game

- Html/helloworld2.html
> added changes

- Python/game_of_stick.py
This is a very simple game of sticks. There are 21 sticks, first the user picks number of sticks between 1-4, then the computer picks sticks(1-4). Who ever will pick the last stick will loose
----
The code is written in python language.
> feat : game_of_stick

- Rust/fibonacci.rs
Prints 10th Fibonacci number.
----
Rust
> add fibonnacci solution in Rust

- C++/Factorial.cpp
calculate the factorial of a number
c++
> Optimized Factorial

- Java/HelloWorldTharindu.java
Print the Hello World message.
----
Java
> Added Hello Wolrd sample

- Ruby/climb-the-stairs.rb
A very simple game game I've made during "The Hacking Project" bootcamp.
Picks a number randomly, and makes the player move if it is a good number 
----
Ruby
>  a small game in Ruby

- Python/FileHandling.py
> Added a FileHandling script in the python section

- Python/antivirus_type_utility.py
Added a python program
----
This program checks if any changes have been made to files in the directory that it is in since the last time it has been run by creating a .enil file(custom file). It runs on command line. No GUI. If the program hasn't been run in that directory before or if the .enil file has been deleted then the program creates a small string of a hash of the contents of each file and saves it to a new .enil file and form next run of the program it can check if any file has been modified.
The purpose of the program is to be used on USB drives to check if an unknown computer is infected with a virus. The program is run from the USB drive from a trusted computer and it will create the enil file. Then the USB is inserted into the unknown computer and then removed and …
> Add antivirus_type_utility.py

- Python/knapsack.py
Program solves famous dynamic programming 0-1 knapsack problem.
----
Python
> Famous 0-1 Knapsack Problem.

- Smalltalk/hello_world.st
print hello world
----
GNU-Smalltalk
> add GNU-smalltalk hello world

- Python/HELL_O.py
Add HELL_O.py by using Python
----
Print HELL_O * number of user input
> Add HELL_O python

- Coconut/hello.coco
- Hy/hello.hy
A function to greet whatever it receives.
```
(greet "World")
Hello, World!
```
----
- [Coconut](http://coconut-lang.org)
- [Hy](http://docs.hylang.org/en/stable)
> add coconut and hylang greeting functions

- C#/AgeThing.cs
Asks the user for their age, as well as a number to change the age by, outputting how old they will be in that many years
----
C#
> Added some age thing

- C++/trailing zeroes in factorial.cpp
> created trailing zeroes in a factorial program

- C++/sieve of erathnoses.cpp
> created seive of erathnosis problem

- C++/count distinct divisors of a number.cpp
> Created count divisors.cpp file

- Cpp/islands.cpp
> created islands .cpp

- C++/Graph 3 Cycle.cpp
> created graph 3 cycle.cpp

- Golang/set.go
> add set data_structure

- Ruby/hello_world.en.rb
> Add  hello_world ruby

- Java/HelloWorldMcauliffeM.java
This program prints out "Hello, World" formatted as a quote from myself
----
Java
> Hello World program in Java added

- Lucee/.gitignore
- Lucee/README.md
- Lucee/docker-compose.yml
- Lucee/lucee/Dockerfile
- Lucee/lucee/code/Application.cfc
- Lucee/lucee/code/index.cfm
- Lucee/lucee/config/lucee/lucee-server.xml
- Lucee/lucee/config/lucee/lucee-web.xml.cfm
- Lucee/lucee/config/lucee/setenv.sh
- Lucee/spinup.sh
Presents a "Hello world!" page which is accessible at http://localhost:8888 once you spin up the Docker container.
----
Lucee (open sourced version of ColdFusion). I wrapped it in a Docker container to make it easier to run.
> Lucee - Hello world!

- password_generator/psswd.py
it will generate password for you
python
> added password-generator

- Python/Matplotlib Line
A sample code for drawing a line using matplotlib library.
----
Python
> Create Matplotlib Line

- password_generator/psswd.py
It generates password
----
Python
> A better program

- C++/STL_map.cpp
This file contains basic of map function like insert, find, erase and small use of an iterator.
Basics of STL map
C++
> Created STL_map.cpp

- Agda/Hello-world.agda
Agda is a dependently typed functional programming language. 
It can be used in web client application.
----
Agda
> Create Hello World in Agda

- PHP/OOP/Sample.class.php
> Added Sample.class.php

- Javascript/helloworld-0918nobita.js
Print "Hello, world!"
----
JavaScript
> Create "Hello world" in JavaScript

- html/Hello-World_xavier vick-west
Hello World in HTML5
----
HTML
> Create Hello-World_xavier vick-west

- Factor/hello.factor
Print 'Hello world!'.
----
Factor (https://factorcode.org/).
> Add Hello World in Factor

- INTERCAL/helloWorld.i
Adds Hello World implemented in INTERCAL.
> Added INTERCAL Hello World. Abandon All Sanity, Ye Who Enter Here.

- Javascript/hello_doug.js
Changes all `<a>` tags in an HTML page to say "Hello Doug" with an href attribute to my Github profile
----
JavaScript
> Add hello_doug.js

- C++/city.cpp
----It's a solution to find the smallest path from point A to point B
> Added a kind of dijkstra implemantation

- C/Hello_world_by_Selvah.c
It's a simple hello world program
----
C
> Hello_world_by_Selvah.c

- Python/get_pictures.py
It scrapes images from a webpage. 
Python!
> added python script

- Javascript/HelloWorld.js
Made a helloworld.js file.
Creates hello world via the console, and using a fixed variable.
----
Javascript
> Helloworld.js

- Hello world python/Hello world.pyo
here is my hello world program written in Python language
----
> Hello world program

- Javascript/hello-fromcharcode.js
> Add helloworld using String.fromCharCode in javascript

- Python/Hangman game
This program is a game, the Hangman game.
----
Python
> Create Hangman game

- Bash/Linux_update.sh
Update's the linux system's files.
----
Bash
> Linux_update.sh (Pull 1)

- Python/Monty Hall problem simulation
This program simulates the monty hall problem and proves that changing the door after the choice increases the chances of winning the prize
----
This program was written in Python
> Create Monty Hall problem simulation

- Python/hello_afs.py
writes a text file containing hello world on windows systems
----
> hello_afs.py

- SMLNJ/fibonacci.sml
- SMLNJ/helloworld.sml
There are 2 files: helloworld.sml and fibonacci.sml
helloworld.sml contains a function helloworld(string) that prints "Hello World!" if string is empty. Otherwise, prints "Hello Hacktoberfest 2018!".
fibonacci.sml contains a recursive Fibonacci function and then calls fibonacci(0), fibonacci(1), fibonacci(2) and fibonacci(3)
----
It is written in SML/NJ version 110.83 [1]
[1] http://www.smlnj.org
Signed-off-by: ricardokojo <ricardokojo7@gmail.com>
> Add SMLNJ Hello World files

- C/Caesar Cipher
This program can be encrypted or decipher a file according to a program call.
----
This program was written in C
> Create Caesar Cipher

- C++/What's Your Name?
Asks User for their name and then prints it out.
----
C++
> Create What's Your Name?

- SourcePawn/hello-world.sp
Prints a `Hello world!` message.
----
SourcePawn
> Add SourcePawn/hello-world.sp

- docker/DockerWebStackExample.yaml
Deploy a apache and mysql server container in docker
yaml
> This is a web stack docker swarm  example

- Typescript/hello_looping_world.ts
Loops over a simple console log 10 times printing `Hello Looping World!`
----
> Adds a file to show simple for looping

- Java/Henlo_Doge.java
Print "hello world" in doge language. 
----
Java
> Added Henlo_Doge.java

- docker/Docker_Stack_Yaml_example
This program is a default .yaml archive for docker swarn deploy function
YAML
> Docker YAML Stack Deploy Example

- C++/Tabela-de-Futebol
This program receives the results of the 'n' last games and shows the campaign statistic.
----
This program is written in C and the variables are in Portuguese - Brasil
> Soccer teams performance analyzer

- docker/dockerstackexample.sh
> Docker deploy example script

- Javascript/hello-world-pt-BR.js
- Python/hello-world-pt-BR.py
Hello world in Portuguese.
----
Python and Javascript
> Add Hello World - Javascript e Python em pt-BR

- Java/hello-from-tucker.java
> Added a file in Java directory called hello-from-tucker.java

- Javascript/pozdrav.js
> added pozdrav.js

- C#/Palindromes.cs
- Python/prime_comp.py
Added Palindrome.cs
Check if a Word is a Palindrome.
----
C#
> Added Palindrome.cs

- DOG/hello_world
> added bark comment

- Html/helloworld_jvincent.html
> Rename helloworld.html to helloworld_jvincent.html

- Java/Stack_With_Array.java
it's a stack with an array, that you can use the operations through the console. Like add a element, remove a element, peek the top element.
----
Java
> a data structure with array, that works like a stack

- PHP/HelloOutput.php
Outputs Hello world via php://output stream.
PHP
> Hello world via php://output

- Java/DesignPatternHelloWorld/DesignPatternHelloWorld.iml
- Java/DesignPatternHelloWorld/src/Main.java
- Java/DesignPatternHelloWorld/src/PrintD.java
- Java/DesignPatternHelloWorld/src/PrintE.java
- Java/DesignPatternHelloWorld/src/PrintH.java
- Java/DesignPatternHelloWorld/src/PrintL.java
- Java/DesignPatternHelloWorld/src/PrintO.java
- Java/DesignPatternHelloWorld/src/PrintR.java
- Java/DesignPatternHelloWorld/src/PrintSpace.java
- Java/DesignPatternHelloWorld/src/PrintW.java
Ascii Pattern Print "HELLO WORLD"
----
JAVA
> Ascii design pattern Hello world

- Java/ArraySum
> Sum of array values

- Python/Deep Learning with Keras(Classification)
A basic deep learning(Classification) algorithm with using Keras Library.
Data can be found [here](https://github.com/eijaz1/Deep-Learning-in-Keras-Tutorial/tree/master/data).
----
Python
> Create Deep Learning with Keras(Classification)

- Julia/HelloTheWorld.jl
> julia new hello world

- (12)Web-css/index.html
> Add a few lines in the last para.

- GDScript/hello.gd
Prints "Hello World!"
----
GDScript
> Add 'Hello World' on GDScript

- J#/helloworld.jsl
- WebAssembly/main.wat
> Created Hello World in J# language.

- Haskell/dynamic_programming.hs
Demonstrates a dynamic programming implementation of the solution for the coin row problem. 
It also includes a dynamic programming implementation of a Fibonacci sequence generator for reference so that someone looking at the coin row solver can search around and find a similar example. 
----
Haskell.
> feat: add a nice couple of dynamic programming examples in haskell

- expression2/hello_world.txt
Hello World
----
[Wiremod Expression2](https://github.com/wiremod/wire/wiki/Expression-2)
> create expression2 hello world

- C++/Xersia
- Python/Xersia
> Hello again world

- Java/hw.java
> Hello World in Java :/

- Javascript/hw.js
Say Hello World
----
JavaScript
> Js hello world

- C++/Hello_World!.cpp
c++
----
prints the "Hello, World!"
> Hello_World!.cpp

- Javascript/hello-mendoza.js
> hello-mendoza.js added

- Html/Hello_world.html
This program Displays Hello World in HTML.
----
HTML
> Create Hello World.html

- Bash/hello_tuga.sh
- Portuguese/helloworld.py
prints an hello $name
----
python 3
> added helloworld for Portuguese python

- Arduino/RFID_SimpleSample_withServo.ino
An usefull sample working with a common and cheap RFID module, going with LEDs and a servo.
Works both on seeing RFID Tag's ID and as a simple access problem. As I use both Arduino Uno and MEGA, included also both pins numbers.
Arduino's version of C/C++
> Sample on working with a cheap RFID Module

- Racket/ExampleFunctions.rkt
> Function Examples in Racket

- C/Hello__World.c
Prints a phrase to the screen.
----
C
> Rename HelloWorld.c to Hello__World.c

- C/countingsort.c
Add counting sort in C
Sorts integers (from ARGV) using counting sort.
----
C.
> Counting sort

- Javascript/holamundo-gt.js
- Python/holamundo-gt.py
Print hello world in Chapin
----
Python
Javascript
> Hello world in Chapin

- C/threads.c
- Scala/insertion-sort.scala
---- Calculate the sum of values by creating an array of 1 – 1000 using two threads.
C
> threads to work

- CSS/redvans-helloWorld-css.html
> adding redvans hello css world

- SML/README.md
- SML/hello-world.sml
prints "Hello World"
----
[SML](https://en.wikipedia.org/wiki/Standard_ML)
> added SML implementation

- Ruby/fizz_buzz.rb
This is an implementation of FizzBuzz In Ruby
----
Ruby
> ruby fizz buzz

- Ruby/list_filtering.rb
a function that takes a list of non-negative integers and strings and returns a new list with the strings filtered out.
----
Ruby
> add list filtering ruby program

- PHP/create-triangle.php
> change # to * in create-tringle.php

- Java/Bank_System.java
> Banking Management System

- Html/Basics/hello-world.css
- Html/Basics/hello-world.html
- Html/Basics/hello-world.js
> added Basics folder and updated with html, css, and js - joke of the included! 

- Python/Hello-world.py
> Make code more pythonic

- Javascript/trianglestar.html
> trianglestar

- C++/lucas_thorem.cpp
Lucas theorem basically suggests that the value of nCr can be computed by multiplying results of niCri where ni and ri are individual same-positioned digits in base p representations of n and r respectively.
----
C++
> lucas_theorem[combinatorics]

- Javascript/primenumbers.js
> prime numbers

- C/prototype.c
> prototype file

- Python/helloworldbutbyjulian.py
> Rename helloworld.py to helloworldbutbyjulian.py

- Bash/HelloWorld
- C++/Hello world.cpp
- C++/Hello.cpp
- C++/a240.cpp
- Crystal/hello_world.cr
- Html/index.html
- Python/FizzBuzz.py
- Python/Hello-World.py
- Python/Helloworld.py
- Python/hello-World.py
> add a240.cpp

- Python/checkinput.py
checks what is the type of data taken as input
----
python
> checks type of input data

- C++/triangle2.cpp
> add a triangle program

- C++/Statistics.cpp
This program will take name of the player and the sport he likes as the input. The program will output the most liked sport and the no. of people liking football as a sport.
C++
> Created Statistics.cpp

- C++/AllVowels.cpp
This program will check whether the given string has all the vowels present in it or not.
C++
> Created AllVowels.cpp

- Java/Armstrong
Added user interaction for either to find given number is Armstrong Number or not and print first 'n' Armstrong Number.
1. Prints first n Armstrong Number
2. Whether given Number is Armstrong Number or not
----
Java
> Add user interaction

- C/H33L0_w0rld.c
----Its an small code of hello world in c program
> Hello_world.c

- Javascript/HeyThereWorld/index.html
- Javascript/HeyThereWorld/js/app.js
Displays a "Hello World!" alert, when a button is clicked.
----
JavaScript
> added HeyThereWorld

- Java/recins.java
> Recursive insertion

- C++/print-starpattern
This program will print a star pattern..
----
C++
> display a star pattern

- Wyvern/helloworld.wyv
Hello World Added for Wyvern programming language. Referencing #1 
----
Wyvern
> Hello World for Wyvern Added

- Javascript/JS-hello-world/js/hello.js
---- nothing special
Javascript
> add hello.js

- C++/tictactoe using c++.cpp
Its a simple Tic tac toe game in C++
----
C++
> Added Tic Tac Toe game in C++

- Pascal/add_two_numbers.pas
- Pascal/advanced_calculator.pas
- Pascal/area_of_a_triangle.pas
- Pascal/area_rectangle.pas
- Pascal/average_grade.pas
- Pascal/calculator.pas
- Pascal/circle.pas
- Pascal/cube.pas
- Pascal/currency_conversion.pas
- Pascal/equilateral_triangle.pas
- Pascal/hdi_calculator.pas
- Pascal/heating_display.pas
- Pascal/journey_prices.pas
- Pascal/multiply_three_numbers.pas
- Pascal/olympic_rings.pas
- Pascal/right_triangle.pas
- Pascal/sales_prices.pas
- Pascal/speed_control.pas
Various simple utilities demonstrating the programming language Pascal
----
Pascal
> Add various example pascal programs

- BrainLanguage/hello5.brn
> Added AnotherAnotherAnotherAnother hello world

- BrainLanguage/hello4.brn
> Added AnotherAnotherAnother hello world

- BrainLanguage/hello3.brn
> Added AnotherAnother hello world

- BrainLanguage/hello2.brn
> Added another "Hello world"

- ArnoldC/hello.arnoldc
> added text TALK TO THE HAND "another hello world"

- Python/hello-everyone.py
----Prints 'hello and hi everyone'
----Python 3
> Hello and hi everyone

- Java/LongestCommonSubsequence.java
- Python/longest_common_subsequence.py
It compares two strings,and finds the longest common sub sequence of the strings.
longest common sub sequence for input Sequences “ABCDGH” and “AEDFHR” is “ADH” of length 3.
----
It is written in python
> longest common subsequence

- Python/helloworld123.py
> hello world code added

- R/hello-world.R
> Hello world example

- Python/fuction_to_double_string.py
It doubles all the letters in a string
----
Python
> added a function to double the letters in a string

- Python/digit_recognizer.py
Recognize Digits using Convolutional Neural Network
Needs MNIST dataset
----
Python
> mnist digit recognizer by convolutional network

- Ruby/hello_world_from_london.rb
Prints "Hello, World!" to the stdout
---
Ruby
> add new Ruby Hello World program

- html/index.html
Added the first paragraph
----
> Added a paragraph.

- Batch Script/Dice.bat
It picks a number between 1-6
----
Batch
> Dice.bat (Pull 2)

- Swift/hello.swift
> New Hello's included

- Python/Deletion of duplicate values from list
It deletes duplicate values from a list on integers
Python 3
> Deletion of duplicate values from list

- Python/bokeh_texas.py
Draw map chart about Texas Unemployment 2009
----
Python
> Add bokeh chart about Texas Unemployment 2009

- Java/GCD
Added Eucledian Algo for GCD
----
> feat:- Added Eucledian Algo for GCD in Java

- Java/heyverden/HelloWorld.java
Displays Hello World in Danish
----
Java
> hello world in Danish

- docker/Docker service Apache example.sh
This script deploy an Apache http container
Bash
> This is a example docker service create script

- Hello world python/Hello world.pyo
> Update Hello world.pyo

- Golang/fizzbuzz.go
Solving fizz buzz problem
----
Golang
> Add fizzbuzz

- Java/HelloHacktoberfest.java
> Hello hacktoberfest

- Magical_programs/README.md
- Magical_programs/magic_see.c
Signed-off-by: coppermonkey <parths1229@yahoo.com>
Do stack smashing to overwrite loops. See magic loop in main. As expected it should run for two iteration only, but will go infinitely.
----
C
> Added magic C program

- Ruby/random_hello.rb
Prints "Hello" plus random name
----
Ruby
> Add random hello in ruby

- Python/hello_hack_2018.py
> added hello world file

- Ruby/what_is_your_os.rb
This is a simple Ruby program, know which OS is running on your machine.
----
It is written in Ruby
> Add OS gem

- OOC/hello.ooc
Program says hello!
----
Program is written in OOC
> add ooc hello world

- Javascript/hello_world/index.js
> edited hello world on index.js

- Mohitaaa/Helloworld.cpp
> add hello world in c++

- C++/a240.cpp
- Python/test_hello_world.py
---- Hello World program with pytest
---- python
> Hello Testing World

- Python/Machine_guesses_number.py
simple guessing game (using a binary search method)
written in python
> add machine guesses number game

- Html/hello.html
Added Hacktoberfest heading using h1
----
> Added heading

- Python/HelloWorldFromSPb.py
My program print "Hello world" massage.
----
My program written on Python language.
> Add Hello World program on Python lang.

- Arduino/HelloI2CLCD.ino
This will show hello world on i2c lcd using arduino and nano
This will show Hi ! hello world in 16X2 char lcd using arduino uno and nano
Its written on Arduino (basic c style code for opensource electronic hardware )
> hello world on i2c lcd using arduino and nano

- C#/HelloWorldInPL.cs
> Hello World in Polish

- Python/array.py
> Fixed invalid comment

- C/bigNumbersFactorial.c
- Haskell/concatenate.hs
- Haskell/decimalToBinary.hs
- Haskell/linearize.hs
- Haskell/moneyChange.hs
- Haskell/palindrome.hs
- Haskell/prime.hs
- Haskell/replace.hs
prime.hs - check if the number is prime
concatenate.hs - concatenate two arrays into one
moneyChange.hs - given a value, change into valid notes of 1, 5, 10, 50 or 100
palindrome.hs - check if an array is a palindrome
decimalToBinary.hs - given a decimal number, return a array containing its binary value
replace.hs - replace the first value with the second in a given array
linearize.hs - transform a array of arrays into array of values
bigNumbersFactorial.c - calculates the factorial of any number smaller than 99999
----
Haskell
C
> added haskell programs

- PHP/ url_validator.php
Validate if a URL is working and doesn't return an error (like 404 or 403)
----
PHP
> added php file

- Bash/script-processid.sh
> Script showing process id

- C++/nfactorial.cpp
> file nfactorial.cpp

- SAP ABAP/ZHELLO1. As
SAP ABAP
----
print hello world.
> Create ZHELLO1. As

- Java/trailing zeroes
> Trailing zeroes of a factorial

- C++/BuyingATVSet.cpp
> using inbuilt gcd function

- Haskell/quick_sort.hs
> Add quicksort in haskell

- Html/hello-world-in-bengali
views "Hello World!" in the Bengali language.
----
HTML
> added "hello world!" in Bengali language

- C Language/hello_world.c
Basic Hello World, prints "Hello World".
C
> Create Hello World in C Language

- Python/hello_world_with_format.py
Print "hello world"
----
Python
> Rename hello_world.py to hello_world_with_format.py

- C++/mergesortques.cpp
- C++/minmaxques.cpp
> hacktoberfest

- Java/Mathematics/LCM.java
Calculates lowest commom multiple for given two integers. I found it missing in the Mathematics module from the project.
----
Java
> Add LCM calculating for Mathematics module.

- MIPS/helloworld.asm
> Hello world MIPS

- Python/bresenham.py
- Python/client.py
- Python/create_cmd.py
- Python/koch curve.py
- Python/server.py
create a shell similar to the bash shell
----
python3
> create a shell similar to the bash shell

- Python/bresenham.py
- Python/koch curve.py
> adding python script for bresenham implementation

- Python/bresenham.py
- Python/client.py
- Python/koch curve.py
- Python/server.py
implement a server for a local machine chatbot
----
python3
> python script to implement a server for a local machine chatbot

- C/sparsematrix.C
> Sparse matrix using array Add files via upload

- Kotlin/Quine.kt
- Shakespeare/lost.spl
----Prints it's own source code,
----Prints the numbers from lost,
Kotlin,
Shakespeare Programming Language,
> A Quine and some Shakespeare

- Python/choose_your_class_rpg.py
you can choose a class and and thats it, I was lazy to finish it :) 
----
Python
> little zork game

- Bash/random_number.sh
Generates a random integer between 0 and first passed argument. If no argument is passed, then max value is assumed to be 100
----
Bash
> Add bash random_number

- C++/inorder-traversal.cpp
---- Traverses a tree in an inorder way.
C++
> Inorder Tree Traversal

- RaffaLang/hello_world.bro
It's a Hello World.
----
RaffaLang - https://github.com/raffalang/
> hello world in RaffaLang bro

- Python/ScrapeAmazon.py
Scrapes amazon products in any category over 3 stars using selenium, written in python.
> Added ScrapeAmazon.py

- Assembly/hello.asm
A coworker told me you're not a real programmer unless you've written in Assembly, so here we go
Print "Hello, world."
Assembly.
> initial commit

- Javascript/helloWorldFromFrance.js
> Add french Hello World in Javascript

- Html/hello_world_by.html
> Hello world in Belorussian (html)

- Prolog/mini_master.pl
Its a short SWI-Prolog program, simulating a fictional university that offers a mini-master in Informatics, worth 30 credits. This program checks if a student has completed all required aspects for graduation.
----
Prolog
> Add mini_master to Prolog list

- C++/ajhw.cpp
> hello world cpp

- Solidity/Inbox.sol
> Solidity message setter contract added

- Rust/guessing_game.rs
Guess a number between 0 and 100.
----
Rust
> Rust guessing game

- C++/helloHacktoberfest2018.cpp
- C/helloHacktoberfest2018.c
- Java/helloHacktoberfest2018.java
- LaTeX/Hello_Hacktoberfest_2018.tex
- Python/helloHacktoberfest2018.py
> Java hello sergeeva

- C++/helloHacktoberfest2018.cpp
- C/helloHacktoberfest2018.c
- LaTeX/Hello_Hacktoberfest_2018.tex
- Python/helloHacktoberfest2018.py
> Cpp hello sergeeva

- C/helloHacktoberfest2018.c
- Python/helloHacktoberfest2018.py
> Hello from SPb on C

- C/helloHacktoberfest2018.c
- LaTeX/Hello_Hacktoberfest_2018.tex
- Python/helloHacktoberfest2018.py
Create sample article with text 'Hello World'
----
TeX
> Te x hello sergeeva

- C#/HelloWorldSwedishEdition.cs
Prints HelloWorld in Swedish
----
C#
> HelloWorld in Swedish

- Kotlin/new-hello-world.kt
> add Hello Hacktoberfest in Kotlin

- Jupyter Notebook/addition.ipynb
> Added a python code for additon

- C Language/OddEven.c
> printf statement is changed

- C/privet_voram.c
> Add new file

- C/Simple Interest
> Update Simple Interest

- Java/HelloWorldUA.java
Prints 'Hello World from Ukraine'
Java
> Hello World from Ukraine

- Python/isPrimeNumber.py
> Move tests to a function

- Kotlin/KotlinExtensionsExample.kt
Kotlin String extension example. This example is applicable to any class type.
> Add Kotlin String extension example. This example is applicable to any class type.

- Python/matplotlib.py
----
Draw chart with help of python-matplotlib
Python
> Add matplotlib chart on Python

- Python/plotly.py
----
Draw chart with help of plotly-python
Python
> Add plotly chart on Python

- Python/hello_coursera.py
> Add Hello-world coursera

- C/Multiplication Table
negative mulitplication table not logical
----
> updated data type

- C/Converts temp
> higher precision for conversion

- Elixir/is_it_prime.ex
Using fermat's little theorem
It supposed to say if the number given is likely to be a prime number or not, using fermat little theorem.
May fail at times, but certainly will say when a number is not a prime.
It's written in Elixir
> Prime number check in elixir

- C/BubbleSort.c
> suggested to give larger array size

- C/Factorial
> fact variable undeclared

- C/ArraySort.c
> added missing semi colon

- Jupyter Notebook/Sum of n Numbers
program finds the Sum of all numbers from 0 to user defined values
----
python
> Create Sum of n Numbers

- SQL/p_HelloWorld.sql
Creates a SQL stored procedure which when executed would display Hello World to the name provided as the parameter.
----
SQL
> Added SQL stored procedure for Hacktoberfest 2018

- Python/googlesearchterminal.py
searches google with keywords from terminal. Not complete.
#help
----
> searches google with keywords from terminal

- C++/BinarySearch.cpp
- C++/multiMatrix.cpp
First Commit ,multi two matrix and return (print) result .
Second one , is Binary Search.
----
written in C++ .
> add multiMatrix and BinarySearch

- PHP/HelloVarDump.php
uses `var_dump` with the `string` "Hello World".
----
PHP
> Hello var dump

- C/LeapYear.c
minimize the size of leap year code
----
> updated the leap year code

- AmazonAlexa/index.js
> Add *HELLO WORLD. THE CODE IS AS FOLLOWS-

- Java/hello-world
print hello world
----
written in JAVA
> create hello-world in java

- C/Addition
more clear to user for addition
----
> updated int to float

- Python/Area_triangle.py
> Add Methods for calculating area of triangles

- C#/HelloWorld_esp
HelloWorld en español :P
----
C#
> Esp => HelloWorld_esp

- Egison/hello-world.egi
Printing `Hello, world!` in console.
----
[Egison](https://www.egison.org/)
ref: https://www.egison.org/manual/io.html#ehllo
> Egison's Hello world program

- C/Factorial
> updated value of f in factorial function

- Javascript/hello-leniquenoralez.js
First Pull Request For HacktoberFest. Prints Github username.
Javascript
> Added hacktoberfest first pr

- Python/bogosort.py
> Added bogo-sort in Python

- Python/nasser.py
- Python/nasser_hello.py
printing hello world in python
----
python3
> hi , this is nasser from kuwait.py

- C++/a power b mod m.cpp
> efficient way to find power mod m

- C/bogo_sort.c
> Added bogo-sort in C

- Java/HelloWorld/HelloThere.java
prints my github handle and prints hello world
----
Java
> Adding hello world program

- NodeJs/pairs.js
pairs(names):
* It accepts an array of names:
`pairs(['Asis', 'Hamsa', 'Fawas', 'Mishmish'])`
* It returns a randomized pairing of names:
`[['Mishmish', 'Asis'], ['Fawas', 'Hamsa']]`
* It can handle an odd number of names:
`pairs(['Asis', 'Hamsa', 'Fawas', 'Mishmish', 'Hussein])`
returns `[['Mishmish', 'Fawas'], ['Asis', 'Hussein'], ['Hamsa']]`
* It returns an empty array if it gets passed an empty array:
`pairs([])` returns `[]`
* It returns an empty array if it gets passed nothing:
`pairs()` returns `[]`
----
Nodejs
> Add pair.js file

- Html/HelloHacktoberfest.html
Basic Hello World Webapplication. It shows it's tasty guts.
----
Written in HTML 5.
> Created HelloHacktoberfest.html and added some tasty content.

- MoscowML/README.md
- MoscowML/hello.sml
Prints `Hello world`
----
[Moscow ML](http://www.itu.dk/~sestoft/mosml.html)
> Added Moscow ML Hello world

- C++/decorator.cpp
> Time decorator

- C++/Add Operator Overloading.cpp
+ Operator overloading Example
> Create Add Operator Overloading.cpp

- C++/AvlTree.cpp
- Python/naive_bayes.py
> Avl tree data structure implementation in C++.

- C/jkfdgj
> to implement header file

- C/libnx_helloworld.c
Print "Hello World!" on the screen of an Nintendo Switch
----
C
> Added libnx (switch homebrew library) hello world

- XSLT/hello.xml
- XSLT/hello.xsl
Renders the xml file into html using the xsl file, displays "Hello World!".
----
XSLT/XML
> added XSLT helloworld

- Java/abcd
> sum of two nos

- Boo/fancy_hello_world.boo
Fancy hello world, shows "Hello world" with "ok" option :o
----
Boo
> Created a fancy version of Hello World for Boo!

- C/abc
> printing Hello World

- Javascript/palindrome2.js
checks if the input word is a palindrome
----
written is JavaScript
> adding another palindrome

- C++/SortArrayDescending.cpp
This program sorts given array in Descending order.
Input:-
3
1 2 3 
Output:-
3 2 1
----
c++
> C++ program to sort given array in Descending order

- Java/RadixSort.java
This program explain the Radix Sort Algorithm
----
It is written in Java
> Add Radix Sort

- Python/worldhello.py
Messes Hello World in Python
----
Python 3
> Messy Hello World

- Javascript/theGame.js
Returns a lucky number for the user.
----
JavaScript
> The Game Added

- NodeJs/testserver
- Python/hellosum.py
Run server in NodeJs in a by default or 3000
----
Nodejs
> testserver

- PyGObject/hello.py
> add hello.py

- puppet/hello-world.pp
Outputs hello world in the puppet client
----
Puppet configuration language
> Add Hello World in Puppet

- Java/HallaVarlden.java
> added hello world in swedish

- Html/Clock.html
Show's a clock in the users timezone
----
HTML/JS
> Clock.html (Pull 3)

- nodejs/README.md
- nodejs/index.js
- nodejs/package.json
> add Hello World in nodejs

- Golang/hello_from_Russia.go
This program print "Привет, мир! Из России с любовью! :)" in Russian, this is mean "Hello world! From Russia with love! :)"
Golang
> from Russia with love

- Kotlin/BonjourKotlin
Signed-off-by: Mian Sarim Hameed <miansarimhameed@gmail.com>
Print Bonjour Kotlin (Hello Kotlin)
----
Kotlin
----
> Hello Kotlin in French

- C/sudoku.c
This program solves sudoku.
Input:	
The input given is 
{ 7,0,6, 5, 1, 0, 0, 0, 0,
0, 8, 0, 0, 0, 7, 0, 9, 6,
5, 2, 0, 0, 8, 9, 0, 0, 0,
6, 0, 0, 3, 7, 5, 0, 0, 0,
0, 0, 8, 0, 6, 0, 9, 0, 0,
0, 0, 0, 4, 9, 8, 0, 0, 7,
0, 0, 0, 8, 2, 0, 0, 7, 1,
8, 3, 0, 7, 0, 0, 0, 2, 0,
0, 0, 0, 0, 4, 1, 3, 0, 8};
Where 0 implies empty box
Output:
The output is
7 9 6 5 1 4 2 8 3
1 8 4 2 3 7 5 9 6
5 2 3 6 8 9 7 1 4
6 1 9 3 7 5 8 4 2
4 7 8 1 6 2 9 3 5
3 5 2 4 9 8 1 6 7
9 4 5 8 2 3 6 7 1
8 3 1 7 5 6 4 2 9
2 6 7 9 4 1 3 5 8
for more details go to this link(https://docs.google.com/document/d/131kMlO-xeorZj1yLkkbBAID8u2kOeGNObBexcaiH7GQ/edit)
----
C
> Implementation of sudoku solving algorithm in c

- C/Program to reverse a String
Program to reverse a String
----
C
> Program to reverse a String

- PHP/HelloWorldFromSundanese.php
> Add hello world from sundanese language

- Java/th.java
> Added the hello world of my own

- Java/modularExponentiation.java
Finds modular Exponentiation
----
Java
> Added Modular Exponentiation

- Python/fouropcalc.py
Program make a simple calculator that can add, subtract, multiply and divide using functions
----
> add, subtract, multiply and divide using functions

- Python/helloworldjap.py
Program to print a String that says Hello World in Japanese
----
Python
> Hello World in Japanese

- Javascript/HelloWorldIndonesia
> create hello world indonesia

- Java/HelloFromPoland.java
Prints "Hello from Poland".
----
Java
> Add Java Hello World From Poland

- GO/quick_sort.go
----quick sort on given array of elements
Go
> added quick sort in Go

- Scala/HelloWorld.scala
> anythingelse

- ECMAScript/index.js
helloworld in console log (improvement use const instead of var)
----
EcmaScript (JavaScript)
> use const instead of var in ES

- Magical_programs/read_pid.py
- Magical_programs/waste.c
Signed-off-by: coppermonkey <parths1229@yahoo.com>
Read pid of a running program
----
python
> Added program to read pid of a file

- jq/hello_world.jq
The program simply prints out "Hello World". To run the `jq` script, first have `jq` installed. Next, run: 
```
$ jq -fn hello-world.jq
"Hello world"
```  
----
The code was written using [jq](https://en.wikipedia.org/wiki/Jq_(programming_language)), a very high-level functional programming language related to [Icon](https://en.wikipedia.org/wiki/Icon_(programming_language)) and [Haskell](https://en.wikipedia.org/wiki/Haskell_(programming_language)).
> Add hello world for jq language

- C#/HelloWorldFromTheNetherlands.cs
Says Hello world from the Netherlands
c#
> Hello world from the Netherlands

- Golang/helloFromRTP.go
Greets you from RTP!
----
Golang
> Hello from RTP, NC

- C++/hello_world_gumeo.cpp
I tried to be explicit about what each line is doing
Prints Hello World!
----
C++
> Create yet another hello world in C++

- Javascript/hello-roman.js
This is a simple variation of `hello world` code created during my vlog episode regarding open source. Nothing fancy actually 😄 I just wanted to show how other people can contribute to the OS.
----
JavaScript
> Create hello-roman version of hello world 

- R/HelloWorldIn.R
Another hello world example
----
> My hello world example with comments

- Scheme/histogram.scm
Added a function which creates a histogram from an array in Scheme
----
> Histogram added to scheme

- Python/get_trace_and_log.py
The program is a simple trace and log helper function, which logs the current offending line and the time both into the console and an errors file. I hope this is the right way to do things (still getting used to using github and pull requests 😊 ). Thanks y'all!
----
Python 3.6
> Haktoberfest Pull Request - Simple trace and log helper function -- Python 3.6 -- Cooops

- M/hello.m
M or  MUMPS.
----
Print Hello, World!
> Created Hello World! in M programming language.

- C++/matrix.h
It is a header file which contains matrix operations.
----
It is written in c++
> Added Matrix.h which contains all matrix related operations

- C++/HelloInC++
- C/helloSS.c
- Html/basic-webpage.html
prints hello world
----
written in C
> created helloSS.c

- dsu/dsu.java
this program does basis operations on disjoint sets like makeset , union and findset.
----
JAVA
> code of disjoint set and union in java

- Html/Hello_world.html
Heading 1 set to centered using align.
----
> Heading 1 set to centered.

- C++/floyd_algo.cpp
Finds shortest path between all pairs of nodes in graph using Floyd algorithm
----
C++
> Floyd algorithm

- Java/HelloWorldWithASmile.java
> Made the smile bigger :D

- Objective C/hello_world_by.m
> Hello world in Belarussian (objc)

- Java/HarmonicNumber.java
- Java/HelloWorldArabic.java
- Java/LinkedListRecursion.java
solves harmonics and linkedlist
----
java
> Harmonic and linkedlist

- Java/HelloWorldArabic.java
prints hello world in arabic
----
java
> added hello world in arabic java

- Java/HelloWorlrdBy.java
> Hello world Java in Belarussian

- Java/AreaOfShapes.java
> added surface area of a cube

- SpringBoot/hello_world/hello_world.ipr
- SpringBoot/hello_world/pom.xml
- SpringBoot/hello_world/src/main/java/de/demo/hello_world/HelloWorldApplication.java
- SpringBoot/hello_world/src/main/java/de/demo/hello_world/controller/HelloWorldController.java
- SpringBoot/hello_world/src/test/java/de/demo/hello_world/HelloWorldApplicationTests.java
It prints HelloWorld
----
Java
> add hello_world app in java with spring-boot

- C/helloworld_turkish.c
> Update and rename helloworld.c to helloworld_turkish.c

- Kotlin/MinimalBoxCount.kt
Solve minimum number of packages needed to pack items.
Big package size is 5
Small is 1
If cant pack, return -1
Kotlin
> [HacktoberFest] Solve minimum number of packages needed to pack items.

- Javascript/hello-hacktoberfest-2018.js
> added hello-hacktoberfest-2018.js

- C++/Calculating_an_area_of_a_triangle.cpp
Added a program to calculate the area of a triangle in cpp
calculate the area of a triangle
cpp (C++)
> Added a program

- Java/BinarySearch.java
Does binary search on an array
----
Java
> Added condition for error checking

- Python/yeariturnhundred.py
Predicts the year you turn 100 with only age as input
----
> Fun script for beginners using modules

- MATLAB/helloworldmatlab.m
> this is now a working hello world script

- Python/ClientServer.py
- Python/ServerScript.py
It starts a chat server on cli
----
Python
> chatServer client and python Scripts added

- React-Native/helloWorld/App.js
- adding-two-numbers/adding_num.html
> Addingthirdnumber

- Python/hello_my_world.py
Hello world function
----
Python3
> my hello world script in Python3

- Skip/README.md
- Skip/hello_world.sk
Print "Hello world!" string
----
Skip lang. It is a programming language to skip the things you have already computed.
http://skiplang.com
> Add Skip lang "Hello world"

- Java/fgh
> implement scaner

- C++/Finding_element_in_linked_list.cpp
- C++/Hello_Github.cpp
- Python/Area_Of_Triangle_Herons_Formula.py
Finding element in a linked list
----
C++
> Data Structure

- C/jfgj
> header file

- Python/printhello.py
> hello world in py

- Javascript/HelloWorldIndonesia.js
Show Hello World in Indonesia Language
----
Javascript
> Hello World in Indonesia Language

- Python/portscanner.py
One of the first python3 projects I made
My portscanner scans ports and returns either opened or closed.
----
In python3
> Add Portscanner in python3

- C++/Min_subarray.cpp
Program to find Minimum sum subarray. 
Output Screen Shot 
C++
> Program to calculate Minimum subarray

- Html/hello-name.html
Take inout from user and says Hello <name>
----
HTML
> Add Hello world in HTML

- C#/HelloWorldMe.cs
Adds a Hello world program to the C# directory saying hello and that it's my first PR!
C#
> Adding my own hello!

- C/Snakegame.c
Created snake game in c
It plays snake game
----
Written in C
> Created snake game in c

- DBase/helloworld.dbf
> Added DBase hello world

- Golang/channel_helloworld.go
sample go channel.
----
golang.
---
> add channel hello world

- Twig/hello-world.twig
It is a very simple two line program in the Jinja/Twig templating syntax.
> Hello World program in Twig/Jinja Templating Syntax - Fixes #17

- C/sort.c
sort integer array by quicksort
----
C
> [ADD] sort methods (quicksort)

- Golang/guessingGame.go
It is a guessing game. Guess the number between 1 to 100.
----
Golang
> add guessingGame.go

- Ruby/ruby_spin_word.rb
This program takes 2 strings s1 and s2 including only letters from a to z. Returns a new sorted string, the longest possible, containing distinct letters. each taken only once - coming from s1 or s2. Examples:  a = "xyaabbbccccdefww" b = "xxxxyyyyabklmopq" longest(a, b) -> "abcdefklmopqwxy"
----
Ruby
> add new ruby program

- C/Newton Forward Backward Divided Difference.c
It computes Newton forward backward divided difference
----
C Language
> Added Newton forward backward divided difference

- C++/A-small-step-towards-calculators.cpp
> used ternary to reduce code size

- C++/Factorial
used 'long' dataType to store big integer value
it finds factorial of +integer
----
c++
>  factorial 

- ML/hello.sml
print hello world.
----
ML programming language.
> Created hello world! program in ML Language.

- C++/Yet_Another_Hello_World.cpp
> Another Hello World

- Hello world python/helloworld.py
> Its Hello world

- C++/leapyear.cpp
> leapyear.cpp

- Html/Click_Count.html
It count's how many times you click the button
----
Html/JS
> Click_count.html (Pull 4)

- Python/hello_world_javanese.py
Print hello world in Javanese languange
----
Python
> Add hello world in Javanese with Python

- Java/HelloWorld/HelloThere.java
- Javascript/hello_world/index.html
> New statement added

- C Language/c_hellow_world.c
show "Hello World!" in console
C programming language
> Hello World in C

- Eta/Main.hs
Print Hello World
----
[Eta](https://eta-lang.org/)
> Add language Eta

- Bash/hello-name.sh
Print your name in terminal
Bash
> add hello-name in bash

- Python/happy.py
- Verilog/FIFO.v
it's a 256 bit fifo using ip-core (act like stack)
----
verilog
> written FIFO with ip-core

- NodeJs/arrayFunctions.js
In this file I've implemented some array functions from scratch.
----
It was written in javascript
> Add arrayFunctions.js

- Java/helloVasilisWorld.java
> Hello World from Greece

- C++/Beautiful-Days-at-the-Movies
The Algo and Code to the Problem Beautiful Days at the Movies on Hackerrank.com
Link: https://www.hackerrank.com/challenges/beautiful-days-at-the-movies/problem
----
> Beautiful-Days-at-the-Movies.cpp

- Hello_in_C/hello.c
- Hello_in_C/palindrome.c
--Checks if a given number is Palindrome or not.
--C
> Program to check Palindrome in C Added

- C#/BrainfuckInterpreter.cs
Interpret the brainfuck language.
----
C#
> Create Brainfuck Interpreter in C# (also one of my repos)

- Kotlin/HelloDonya.kt
- Kotlin/hello-world-arabic.kt
Hello word From central java indonesia
kotlin
> Muhrizky hello donya

- Kotlin/HelloDonya.kt
hello donya from central java indonesia
Hello word from central java indonesia
----
kotlin
> Hello donya

- PlantUML/helloworld.puml
UML diagram with HelloWorld
----
PlantUml
> Add Plant UML diagram HelloWorld

- BigosLang/hello.big
Just saying "Hello  world!" around the world.
----
BigosLang - is a parody of Pascal lang by one of Polish users. Bigos is also a food very well known to Polish users.
Download: http://krzysztofkonczak.y0.pl/BigosEdit.rar
> hello world! in bigos lang

- C++/horses.cpp
Codechef problem horses code
Link: https://www.codechef.com/problems/HORSES
C++
> Codechef Horses Problem

- VueJS/ComputedVue
> Example about computed in vue

- C++/TriangleAreaGivenThreeSides.cpp
added TriangleAreaGivenThreeSides.cpp
> add program to calculate triangle area given 3 sides

- JavaScript/PrimeNumber.js
The Program detects that whether a number is a prime number or not.
The Program is written in JavaScript.
> Added Prime Number detector using JS

- Python/hello-word-centraljava.py
central java susgeng rawuh
hello word from central java
----
pyhton
> add-hello-word-centraljava

- C++/stl1.cpp
- C++/stl2.cpp
> commit-101

- VueJS/IfElseTemplateVuejs
> Example about if-else and template in vuejs

- ASM_NASM_X86/HelloWorld.asm
- ASM_NASM_X86/README.md
A colorful World Hello
----
Assembly x86
> Hello world ASM x86

- C++/Factorial.cpp
Calculate the factorial of the input number
It's in C++
> Indentation with Print statement updates

- c/hello.c
The program is written in C
It prints a simple hello world statement and all explanatory comments have been added.
> Minor Indentation and commenting

- PHP/ForkBomb.php
- Rust/forkbomb.rs
> Rust forkbomb

- Python/heap-sort.py
Code description of the heap sort algorithm
----
Python
> Added heap sort code in Python

- C Language/forkbomb.c
- PHP/ForkBomb.php
- Rust/forkbomb.rs
> C lang forkbomb

- Java/Calculator/Calculator.java
changed the data type so that we can add decimal numbers also
----
> change data type

- Bash/H-git.sh
install git & and clone repo
----
bash
> Hello Gnu/linux & git

- JavaScript/functionalCurry.js
Implementation of the functional curry
----
Javascript
> Functional curry

- Crystal/inputexample.cr
It's just a silly example program for Crystal-Lang
> Adding Crystal-Lang Input Example

- C/pushpneetsingh
> added a hello world programme

- C++/HelloWorld_Peru.cpp
Write a Hello World in Spanish and draw the flag of Perú, my country.
C++
> Create Hello World(C++) in Spanish-PE

- Python/Deep Learning with Keras(Classification)
- Python/LinkedList.py
> documented file

- Python/pairs.py
It takes a list of names and pairs them in teams of two. If there is an odd number, there will be 1 team of 1.
----
Python <3
> a python function to create random teams of two

- Python_flask_hello_world/hello_world_flask.py
Program print hello world on your localhost
Python using framework flask
> adding hello world on python flask

- Java/HelloWorldPrachee.java
program print "Hello World!!"  
----
This program is written in Java
> print 'hello world' in java

- C++/HiWorld.cpp
> Hello World HacktoberFest 2018

- Caml/hello_world_graphics.ml
Open a graphic window using the Graphics library of Caml, and draw a centered "Hello World!" string
----
It's written in Caml
> Add graphic version for caml

- Python/printFibNumbers.py
> print Fibonacci numbers

- GO/floodfill/floodfill.go
#33 Simple Golang program that demonstrates how depth first search is used to perform floodfill on grids.
> Added example of floodfill in Go.

- C/Hello_World.c
- C/hello.c
- C/single_level_directories.c
- Cpp/scientific_calculator.cpp
- Crystal/hello_world.cr
- Javascript/Hello_World.js
- NodeJs/README.md
- NodeJs/index.js
- NodeJs/package.json
- Python/HelloworlD
- Python/helloWorld
> added scientific calculator program

- Swift/HelloWorld.swift
Added HelloWorld.Swift
It prints "Hello World"
----
Swift
> Added Swift

- Kotlin/Classes.kt
- Kotlin/Factorial.kt
- Kotlin/FizzBuzz.kt
- Kotlin/GenericSorting.kt
> Added Kotlin programs for explaining loops, classes, and generic sorting.

- Javascript/hello-world.js
Output Hello world to console
----
ES16 does not need semicolon.
> remove semicolon

- Language/helloworldankit.cpp
> ankit's cpp file

- C/Hello_World.c
- C/hello.c
- Crystal/hello_world.cr
- Javascript/Hello_World.js
- Language/HTML hello world.html
- NodeJs/README.md
- NodeJs/index.js
- NodeJs/package.json
- Python/HelloworlD
- Python/helloWorld
created html file for hellow world
----
> HTML hellow world

- docker/DockerWebStackExample.yaml
> mysql is as same as mysql:latest

- c/flipping-the-matix.cpp
This is the Algo And Code to get a perfect solution to the Following Problem link of Hackerrank:
https://www.hackerrank.com/challenges/flipping-the-matrix/problem
----
> flipping-the-matrix.cpp

- Javascript/DiamondSquare.js
> Added DiamondSquare.js

- C/hell0.c
> test pull request

- Python/sendmail.py
send mail from your email address to any receiver
----
python3
> python file to send mail

- Python/FeelingLucky.py
The program implements Google's i am feeling lucky in python and prints the link google redirects to on clicking i am feeling lucky.
----
Python 3
> Implementation of Google's I am Feeling Lucky

- C++/hannoi.cpp
> add hannoi.cpp

- C++/odd_even_hello_world
Print Hello World depending on the input.
----
C++
> Added odd/even hello world.

- GO/sieve-prime-algorithm.go
get prime, using goroutine , the most interesting golang's part
----
Go
> prime algorithm using goroutine

- Bash/bulk_file_printer.sh
- Python/websockets/websocks-hello-cli.py
- Python/websockets/websocks-hello-sv.py
-----
_Websocket server and client for hello world. Open the server in the command line and then open the client. The client should send a message to the server which it then echoes back to the client who displays it._
-----
-----
_Python_
-----
> Added websocket sv/cli for a simple hello world in python.

- VueJS/CatchEventVueJS
> Catch some simple event in vue js

- Html/HelloWorldU
Print a Hello World Message
----
HTML
> Created Hello World

- C++/tetris.cpp
Tetris the game can be played on console
----
C++
> Tetris for console

- C++/snake.cpp
Snake game  that can be played on console
C++
> Snake on console

- Java/LargestNumber.java
Added a Java program that asks for the number of numbers you want to compare and after you enter them tells you which one is the largest.
> Add LargestFile.java

- C#/MathExpressionsCalculator.cs
This program can evaluate mathematical expressions.
It is written in C#.
> C# Mathematical Expression Calculator

- C++/helloworld.cpp
> added helloworld.cpp

- C++/Hello world, but in polish
Says "Hello world" translated to polish language.
----
C++
> Create Hello world, but in polish

- JavaScript/functionalPipe.js
Implementation of functional pipe utility
----
Javascript
> functiona pipe

- Python/Hello World in Python
Asking the name and printing Hello + Name
----
Python
> Now asking name !

- Elixir/HelloWorld.ex
A richer implementation of Elixir's Hello World with attached documentation
----
Elixir
> Add italian Elixir hello world implementation and some docs

- Actually/hello_world
> added hello world insted of H

- Java/hellooooWorldEasy.java
Simple Java program that prints Hello World!
Prints Hello World!
----
Java
> Simple Java Hello World!

- C++/linear_search.cpp
> linear_search

- Electron/app.js
- Electron/index.html
Will show Hello world as a desktop app
----
JavaScript - ElectronJS
> Add ElectronJS

- C++/bucketsort.cpp
Bucket sort is mainly useful when input is uniformly distributed over a range.
----
c++
> Bucket Sort Program

- C++/Hello world.cpp
> Update Hello world.cpp

- Java/BubblesortVn.java
- Javascript/helloworldVN.js
> +helloworld

- C++/Reverse a string.cpp
> refactored to use STL

- JavaScript/helloWorld.js
> Added hello world program

- NodeJs/bruteforce.js
Bruteforces letters to find a given string
Node.js / JavaScript
> Bruteforce

- Elixir/fibonacci.ex
It calculates the fibonacci row
----
Elixir
> added fibonacci implementation in elixir

- C#/BonjourMonde.cs
- Python/BonjourMonde.py
Hello World in French in C#
----
C# and French
> Added French c# Hello World

- anonymousChatServer/clientSide/ClientThreadRead.java
- anonymousChatServer/clientSide/ClientThreadWrite.java
- anonymousChatServer/clientSide/clientSocket.java
- anonymousChatServer/serverSide/ServerThread.java
- anonymousChatServer/serverSide/serverSocket.java
A simple multi-threaded chat server implementation
----
Java
> Multi-threaded chat server implementation

- C++/hello_evryone.cpp
----Prints Hello to everyone and the world
C++
> add hello_evryone.cpp

- Python/hello_World!.py
> Created hello_World!.py

- C#/Hello Word in C#.txt
> Update Hello Word in C#.txt

- C++/Insertion Sort!!
Implements Selection Sort and print the sorted array
----
C++
> Selection Sort!!

- C++/Bubble Sort!!
Implements Bubble Sort and print the sorted array
----
C++
> Create Bubble Sort!!

- C++/Binary Search!!
Implements Binary Search to search and print the index of a given number in an array
----
C++
> Create Binary Search!!

- C++/Add Two Numbers!!
Add and print two numbers
----
C++
> Create Add Two Numbers!!

- C++/Palindrome.cpp
> Palindrome

- C++/Insertion Sort
Implement Insertion Sort
----
C++
> Insertion Sort

- Ksh/helloworld
Prints Hello Hacktoberfest
----
Kornshell (zsh)
> Add Hello World in Kornshell (ksh)

- Java/calculator.java
simple calculator thats support + 1 * / () sin
----
java
> this calculator support +-*/() and Sin :)

- C++/Insertion Sort Steps
Prints all steps occurred during Insertion Sort
----
C++
> Insertion Sort Steps

- C++/BinarySearch.cpp
in the main function parenthesis were not closed so it will return an error
binarysearch
----
c++
> updating main function

- C++/DijkstrasAlgorithem.cpp
> my commit.

- PHP/Hello PHP/index.php
> Suitable with css 3

- Python/HaloDunia.py
---- write hello world and halo dunia
i wrote in Python
> Hello world project

- Python/linear_regression.py
linear regression
----
python3
> python script for linear regression

- Python/impossible_game.py
Program to quiz user but it has no correct answer
Written in python
> added impossible game

- Python/helloWorld!.py
It is a simple program that just prints hello world.
----
It is written in Python
> added helloWorld.py file to the python folder

- Python/linalg.py
---- Solves linear matrices
Python
> Solve matrices

- JavaScript/convertingCallbackintoPromise.js
Converts async function that callback into a promise-returning function.
----
Javascript
> Function to convert callback based function into promise based one

- Html/Print Hello_world.html
> Update Print Hello_world.html

- Python/hello_world_.py
A simple hello world program
----
Python2.7
> Added hello_world_.py

- C++/Hello.cc
> Hello Message in C++

- Elixir/sort.ex
File contains implementations of insertionsort, mergesort and quicksort in elixir
___
Elixir
> uploaded new file

- Python/hello_world_python3
----  Print Hello World!
--- Python3
> Rename README.md to Python/hello_world_python3

- Python/indentor2.py
----#  This is a code formater  in python. This program indents a minified  line based on parantheses {  '( '  ,  ')'  }
Python3
> added paranthesis indentor #first PR

- C++/Pigeonhole-sort.cpp
Pigeonhole sorting is a sorting algorithm that is suitable for sorting lists of elements where the number of elements and the number of possible key values are approximately the same.
----
C++
> Pigeonhole Sort Program
