IntelAISociety/Hello-world

- Koka/helloWorld.kk
Prints _Hello world_.
----
In [Koka](https://github.com/koka-lang/koka) language.
> Add hello world for Koka language

- C/Longest Increasing Subsequence.c
The Longest Increasing Subsequence (LIS) is defined as the longest subsequence of a sequence such that all elements of the subsequence are sorted in increasing order.
A program in C to find the Longest Increasing Subsequence of a given array A.
Input:
The first line of input contains an integer N, denoting the size of array A.
Output:
Length of longest common subsequence.
----
C
> Create Longest Increasing Subsequence.c

- C#/BonjourMonde.cs
- C/BonjourMonde.c
- JavaScript/BonjourMonde/index.html
- JavaScript/BonjourMonde/index.js
- Python/BonjourMonde.py
- Ruby/BonjourMonde.rb
French Hello World
----
Ruby and French
> French language ruby

- C#/BonjourMonde.cs
- JavaScript/BonjourMonde/index.html
- JavaScript/BonjourMonde/index.js
- Python/BonjourMonde.py
French Hello Wworld
----
Javascript and French
> French language java script

- C#/BonjourMonde.cs
- C/BonjourMonde.c
- JavaScript/BonjourMonde/index.html
- JavaScript/BonjourMonde/index.js
- Python/BonjourMonde.py
French Hello World in C
----
C and French
> French language c

- C/Addition
> addition of two numbers

- Java/Projet2/src/Matrix/Array2D.java
- Java/Projet2/src/Matrix/MainArray2D.java
- Python/if.py
- Ruby/hello_world_from_indonesia.rb
> give dynamic input for A and B on python

- CSS/hello.css
> color added

- Python/say_hello.py
PR 5
A program to print and chat with Python
----
Python
> say_hello done

- Apex/getInfo.apxc
it will get the account records from your org.
----
It is written in Apex programming Language.
> getting the accounts from your org

- Python/AddNum.py
> Sum of three

- Common Lisp/helloworld.lisp
Showing "hello world" string.
----
Common Lisp
> added Common Lisp

- Html/hello-world-hindi.html
> new hello world from india in hindi language

- Java/HelloScannerWorld.java
> Add another HelloWorld

- Assembly/texteditor.asm
instruction is at the beginning of the file
a simple text editor by a limited size of the viewer.
----
AssemblyX86 and run under the emulator
> add simple text editor script

- Python/BottomUpMergeSort.py
- Python/karatsubaMultiplication.py
Karatsuba Multiplication Algorithm
Python3
> Merge sort up

- pondthaitay/helloworld.kt
Android Developer and Smart Contract
----
Kotlin
> Jedsada Tiwongvorakul

- Javascript/Harry_Potter/style.css
Minor CSS animation change to make wing shake along x-axis
----
CSS
> Made wing shake across x-axis as well

- Lean/HelloWorld.lean
The program defines a HelloWorld theorem as being true.
[Lean](https://leanprover.github.io/)
Install [Lean Theorem Prover](https://leanprover.github.io/download/) and hover over `#check` to see that the theorem is true.
> Add Hello World program in Lean

- Python/conway.py
Implementation of Conway's game of life.
----
Python 2.7
> Conway's game of life

- JavaScript/hello-jn.js
Prints my own little flavor of Hello World 👍 
----
JavaScript
> Hello World JS

- COW/hello-world.cow
Prints Hello World!
----
COW programming language
> hello-world.cow

- Python/ShellSort.py
> Adding ShellSort Algorithm on Python

- C/Hello Romania.c
> line by line print name

- PHP/README.md
> Create README.md file

- JavaScript/destructuring,js
- JavaScript/rest-params.js
----Describes how to use rest(...) operator
----**JavaScript**
> Add rest params file

- Python/remove_duplicate _items_in_list.py
Removed duplicate items from a list.
----
Python
> ADD: remove_duplicate _items_in_list.py

- JavaScript/Colour Guessing Game/colorGame.css
- JavaScript/Colour Guessing Game/colorGame.html
- JavaScript/Colour Guessing Game/colorGame.js
> Add colour Guessing Game to JS folder

- C/sievePar.c
Calculates the sieve of eratosthenes in parallel.
C with OpenMP
> OpenMP version of sieve of eratosthenes

- GO/hello.go
This program prints the classical "hello world" example!
go programming language
> first commit in golang

- C/hello-george.c
> adding hello george

- Python/naive_string.py
<p>It takes an input text and pattern and finds out if the pattern occurs in the string. If present, it returns the position as to where the pattern starts.</p>
----
Python
> Reformat code in accordance with PEP 8

- Red/hello.red
> Add Red Lang hello world

- NodeJs/fizzbuzz.js
loop that iterates up to user input no **'n'** while outputting **"fizz"** at multiples of **3**, **"buzz"** at multiples of **5** and **"fizzbuzz"** at multiples of **3** and **5**
----
It is written in Vanilla JavaScript.
> FizzBuzzSolution

- Ruby/hello_world_ar.rb
Prints Hello World in Arabic
Ruby
> Add hello world in Arabic

- Python/NodeSwapping.py
- Python/NumberGuess.py
Python program to swap two given nodes of a linked list
----
Python
> Swapping Nodes of Linked List

- MATLAB/hello_x.m
hello world as a function with a parameter 
----
MATLAB
> add a hello world as a function

- PHP/hello_love.php
If you access the program passing a Get attribute like "hello_love.php?world=Caio" it will overwrite the Hello World with the name passed.
---
PHP
> Hello love

- Java/BonjourJava.java
- Scala/BonjourScala
Signed-off-by: Mian Sarim Hameed <miansarimhameed@gmail.com>
Print Bonjour Java (Hello Java)
----
Java
----
> Hello Java in French

- Python/helloooWorldPYPY.py
Simple Python3 Program that prints "Hello World!"
Prints Hello World!
----
Python3
> Python3 Hello World !

- JavaScript/palindrome.js
This program checks if a provided string is a palindrome or not.
----
This program is written in javascript.
> A palindrome program in javascript

- Swift/HelloWorld.playground/Contents.swift
- Swift/HelloWorld.playground/contents.xcplayground
A Hello World program using Swift Playgrounds!
----
Swift, inside a Playground
> Hello world playground

- C/bubbleSortC/bubbleSort
> bubble sort in c

- Python/namaste_world.py
> Hello World Indian Style

- VHDL/blinking_led.vhdl
Let's a LED blink on an FPGA
Pin Configuration depends on used FPGA
VHDL
> Added a blinking LED in VHDL

- C++/Binary Search Without Recursion
Implements Binary Search Without Recursion
----
C++
> Binary Search Without Recursion

- MIPS/DelSubString.asm
The program takes a string and a substring and deletes the occurrences of the substring from the string, if any.
----
The program is written in MIPS.
> Added 'Delete Substring from String' Program in MIPS

- C++/peda.cpp
**RUN HERE** --> http://cpp.sh/46xjz
> Una peda para el Hacktoberfest 2018 <3

- IDL/hw.pro
Prints `Hello, World!` to screen.
----
IDL - Interactive Data Language - Currently owned by Harris Geospatial.  It's an older Fortran like language with GUI components.  It's still used in scientific research.
Quick Links
https://www.harrisgeospatial.com/docs/using_idl_home.html
> IDL hello world example

- pong/pong.html
- pong/pong.js
- pong/readme
Its a ping pong ball game implemented in Javascript
The program is written in HTML, Javascript
> added ping pong game

- C/fpmmfnns.c
Fills and prints a 3x5 matrix on the screen
----
C
> fpmmfnns.c

- Bash/get-youtube_audio.sh
Download audio from youtube
----
Bash
> Download audio from youtube

- JavaScript/hello_w0rld.js
Writes 'hello world' in browser
----
JavaScript
> Hacktoberfest 2018 Hello World Submission

- Python/recursive_knapsack.py
- cpp/Red-Black-Tree.cpp
Knapsack Solution using Recursion
----
Python
> Add knapsack solution using recursion in python

- C++/hw2mfnns.cpp
Prints "Hello world!" on the screen
----
C++
> hw2mfnns.cpp

- C/hfnmfnns.c
Prints the first hundred natural numbers on the screen
----
C
> hfnmfnns.c

- Java/HelloWorld/HelloWorld.java
It output Hello World on the screen when runs and thanks the organization in charge of Hacktoberfest----
Java
> Hello World sample using Java Programming Language

- Hack/helloworld.php
> Fix helloworld.php

- GO/ImportCSV.go
----Opens CSV files to manipulate data
> Open csv files go

- PHP/HacktoberIllusion.php
A pull-request for hacktoberfest 💯
Saying hello to other contributors
----
PHP
> HacktoberIllusion.php

- l33tsp34k/4b0u7(about).txt
- l33tsp34k/hello_world.l33t
A hello world program and a about file containing some basic information about the programming langauge 
---
l33t
> Added l33t (leet)

- Python/swapTwoIntegers.py
> tricky way to swap two integers

- GNU Make/Makefile
- GNU Make/hello world.mk
----
prints Hello World
GNU-Make
> added helloworld.mk and Makefile.mk

- Python/findFloor.py
Finds floor of given input
----
Python
> Added python function

- C++/ModularExponentiation.cpp
This C++ program computes the modular exponentiation of a number in  O(log(n)) time.
> Added Modular Exponentiation in C++

- APL/hello.apl
Print "Hello World" to stdout
----
APL
> Add APL hello world

- SH/HelloWorld_NL.sh
Slow printing HelloWorld (NL) for Hacktoberfest 2018
----
Shell script
> Slow printing HelloWorld (NL) for Hacktoberfest 2018

- Swift/ObserverPattern.swift
Show an example of how to implement observer pattern with Swift
----
Swift
> Observer pattern example

- Socket Program in python/tcpsniff.py
Packet Sniffer program to sniff the packets in Network.
Packets will be encrypted and needed to be parsed.
Sniffs the TCP packets over the Network.Works on Linux machine.
Python.
> tcpsniff.py

- JavaScript/singleton.js
Show the singleton pattern
---
JavaScript
> Create a singleton example in JavaScript

- C++/hello_abhishalya.cpp
Prints the github handle @abhishalya to the terminal.
----
C++
> Added hello_abhishalya.cpp

- C#/HelloWorld5Times.cs
- C#/UniqueArray.cs
> Hello World 5 times

- NodeJs/process_end.js
Created NodeJs file related to process
This program will display Message when we exit node process 
NodeJS
> Created file process end

- Socket Program in python/get_ip_website.py
Simple Program in Python using Socket library to Display the IP address of any Website.
Shows the IPv4 address of any website that the user inputs.
Written in Python using Socket Library.
> get ip of any website

- C/rotation of array.c
added c program for rotation of array
----
> Create rotation of array.c

- PHP/maitenance.php
simple maintenance page example
> simple maintenance page example

- NodeJs/README.md
> Updated readme file

- NodeJs/mocha-tests.js
This program will run mocha tests cases
Javascript [NodeJS]
> Created mocha test cases

- LaTeX/HelloHacktoberfest2k18.tex
- Lua/HelloHacktoberfest2k18.lua
- PHP/HelloHacktoberfest2k18.php
- Python/HelloHacktoberfest2k18.py
Add HelloHacktoberfest2k18.py Python
----
Written in Python
> Python hello

- LaTeX/HelloHacktoberfest2k18.tex
- PHP/HelloHacktoberfest2k18.php
Add HelloHacktoberfest2k18.tex
----
Written in LaTeX
> LaTeX hello

- Python/webscraper.py
This python script can get the details of all the artciles published by a publication in medium.
----
Python
> Medium Webscraper

- Arduino/WaterPlantReminder.ino
- Squirrel/helloWorld.nut
Write on a LCD Screen the Temperature, Humidity and the plant's mm of water 
Arduino
> added WaterPlantReminder.ino

- TrumpScript/README.md
- TrumpScript/helloworld.tr
----
Print "Hello World".
TrumpScript
> TrumpScript

- Elixir/fizzbuzz.ex
- Haskell/fizzbuzz.hs
> fizzbuzz in elixir

- JavaScript/AsyncAwaitErrorHandler/index.js
- JavaScript/AsyncAwaitErrorHandler/test.js
This is a simple utility which helps to catch error while using async and await.
----
Its written in Javascript.
> AsyncAwaitErrorHandler utility

- PHP/KiranHelloPhp.php
- PHP/pull_request.php
> Abkiran patch 1

- vic/vic.php
- vic/vic.py
> Primer hola mundo

- Ruby/quick_sort.rb
Sorts array using Quick sort algorithm
----
It's written in Ruby programming language.
> Quick sort algorithm added

- Language/hello-world.js
Basic DOM Manipulation
Posting Hello World in the browser.
----
html and javascript (DOM)
> hello-world.html

- C/infix/infix.c
we also get negative value
----
> change of int to unsigned

- C++/unique_element_in_array.cpp
> unique element in array

- Ruby/optimized_bubble_sort.rb
Sorts an array using optimized bubble sort technique
----
It's written in Ruby programming language.
> Added optimised bubble sort algorithem

- C/Factorial
removed possibilities of negative value
----
> update unsigned int in 4 line instead of int

- Java/UglyNumbers.java
> Program to find nth ugly number

- C/Converts temp
> update to increse accuracy

- JavaScript/helloworldtag.js
> tagalog.js

- JavaScript/helloWorld_ph.js
> Rename helloWorld.js to helloWorld_ph.js

- Bash/User_add.sh
adduser - Adds a new user to the system, including building their
home directory, copying in default config data, etc.
For a standard Unix/Linux system, not Mac OS X
This Scrip is written in Bash
> Upload User_add

- Javascript/helloword_bosnian.js
hello world in bosnian
This program console logs the "Hello World" program but in Bosnian
----
JavaScript
> js file that console logs hello world in bosnian

- Python/happyNumber.py
- Python/mp3-player.py
It is the easiest mp3 player.
It is written in python. 
Don't forget to change the path of the mp3 file.
> Simple_Mp3_Player & HappyNumber

- C++/fast input output
> Create fast input output

- C++/validtriangle.cpp
Checks if it a valid triangle.
C++
> Created a new file

- Assembly/helloworld_68k.X68
Prints "Hello, world" on screen.
----
68000 Assembly/Assembler
> Added "Hello world" for 68000 Assembly

- README.md
- Ruby/count_char.rb
> Ruby program to count the char occurrence in a string.

- Python/multiple_linear_regression.py
mutiple regression
----
python3
> mutiple regression

- README.md
- Ruby/count_char.rb
Added link for the `Help Wanted` tagged issues to navigate easily.
> Updated readme with `Help Wanted` issues link.

- PHP/README.md
Not a program, but a disclaimer to hopefully prevent some security issues.
> Add Disclaimer

- C/factorial.c
now it can compute the factorial upto first 25 numbers....
----
it is written in C language.......
> add factorial.c anmol20goyal

- Java/sergiyHelloWorld/Hello.java
It prints "Hello world !" with a stream
----
Java
> Added Hello World in Java using streams

- Javascript/HelloWorld-Bahasa
Prints Hello World in Bahasa Indonesia
----
JavaScript
> Hello World in Bahasa Indonesia

- B/hello-world.b
- B/sum-of-numbers.b
There are two programs, first one prints hello world and the second one adds three numbers.
B programming language
> Added programs for the B programming language

- Javascript/hello-world-with-promise.js
Resolves a promise returning 'Hello world!'.
Javascript
> Added hello-world.with-promise.js

- Javascript/hello-world.fr.js
Added hello world in french
Prints hello world in French.
----
Javascript
> Added hello world for JS in French.

- JavaScript/Palindrome_Checker.js
> Added Palindrome_Checker.js

- Python/sieve_of_eratosthenes.py
All the multiples of p before p * p were already marked.
----
> A little optimization

- C Language/the_snake_game.c
Allows you to play the legendary snake game!
----
Built in C
> Added the snake game in C Language

- LaTeX/Hello-world-Urdu .tex
Says Hello word in Urdu
----
file is a .tex file
> added Hello World in Urdu to LaTeX

- C Language/github_handle.c
This c program prints my github handle.
> c program to print github handle

- C/suras_handle.c
--- Prints out my github handle
C
>  file added to print handle

- C++/addition_Of_Two_Numbers.cpp
----This program for addition of two numbers
C++
> added addition of two numbers in cpp

- Python/zellers_congruence.py
Zeller's Congruence Algorithm 
----
determines the day of the week of a given date. This is intended to determine the day of the week your birthday fell on. Can determine day of week for any given date, past or future.
Python 🐍
> Create Zeller's Congruence Algorithm

- shortcut-linux-code/example-bash.sh
Place this bash code in the root directory. Use this bash code to open any application with a keyboard shortcut. Now go to settings>keyboard settings and set the running command to any shortcut keys and you're good to go.
----
> Shortcut For Linux Users To Open Any Application

- C++/Array-Reversal.cpp
- Python/array_reversal.py
###Given an array of integers the program reverses and prints in it
----
> Array Reversal

- C++/hello_world_Jonathan-Montanez.cpp
> In reference to #17

- Raghav/hi.html
> Hello world html file

- C++/flipping-the-matrix.cpp
problem link : https://www.hackerrank.com/challenges/flipping-the-matrix/submissions/code/87442905
This will help for solving the problem
Solution to problem: https://www.hackerrank.com/challenges/flipping-the-matrix/submissions/code/87442905
C++
> Flipping the Matrix Solution from Hackerrank

- Kotlin/PrivetMir.kt
The program changes the value of each char in a string (eg. "Privet Mir") and gives out an ´"encrypted"
string. In this case I used the words "Privet Mir" what means "Hello World" on Russian
----
This Program is written in Kotlin
> Added Russain HelloWorld with "encryption" (Kotlin)

- Ceylon/main.ceylon
Prints hello world
----
https://ceylon-lang.org/
> Add Ceylon lang

- NodeJs/palindrome.js
Program will find if provided input is a palindrome or not, in case insensitive manner.
----
NodeJS
> NodeJS: Palindrome

- prakhar/geo_location.py
geo location of ip address
geo location of ip address
python
> geo_location.py

- C++/a240.cpp
優化cin cout
add return 0
Not add new program, just fix
----
C++
> 優化 Add return session

- prakhar/merge_mail.py
Instead of writing each mail separately, we have a template for body of the mail and a list of names that we merge together to form all the mails.
merge mail and send to many peoples
python
> merge_mail.py

- engineering java projects/inverttriangle.java
This program creates a design of an inverse triangle in the form of numbers
it creates design of inverse traingle form the no's
java language
> inverttriangle.java

- C++/format for coding
> Create format for coding

- C++/hello6.cpp
A simple hello world program written in cpp
----
> Added hello6.cpp file

- enginnering java projects/LeapYear.java
the given java program is constructed to find whether the given year is leap year or not.
the given program takes user input as year and tells you whether it is a leap year or not.
> LeapYear.java

- Python/TurtleCircleDrawer.py
It draws circle using squares.
----
python
> Added Turtle Circle Drawer

- PHP/siemanko
Demonstration of using UTF variables. It's written in Polish!
Przyklad uzycia zmiennych UTF po polsku!
> Add hello world in Polish using UTF variables.

- Scala/HiHf.scala
Prints "Hi, Hacktoberfest ---- [current year]!!"
----
Scala
> Add HiHf.scala

- ASM_ARM/helloworld.s
Adds an example program that outputs the string “Hello World”.
----
It is written in ARM Assembly
> add program in ARM assembly

- C/Manipulating the array.c
Given an array X of N numbers and an integer K, during a turn maximum value of array Xi is chosen as MAX. Then Xi = MAX-Xi is done for every 1<=i<=N.
Write a program in C to find the array after K turns.
Input:
The first line of input contains the number N and K respectively. N is the number of elements in the array and K is the number of turns.
Output:
Output N numbers in a single line after K turns. It should be the elements of array X after K turns
----
C
> Create Manipulating the array.c

- Kotlin/NumberLength.kt
Extension fot Int to return the length of the number
----
Kotlin
> Extension for number length

- Ballerina/hello_world.bal
- Ballerina/hello_world_service.bal
- hello-world.bal program prints hello world in console.
- hello-world-service.bal program send "Hello, World!" a response to the client 
----
Ballerina
> Add Ballerina hello world samples

- C/helloWorldInHindi.c
Prints "Hello World" in Hindi language.
----
It's written in C programming language.
> Added hello world in Hindi Language

- Python/google.md
calculate a expression
----
python
> add google.md and google.py

- Batch Script/Okay.bat
> Add Okay.bat

- GO/helloworld_without_imports.go
Prints hello world in most simple way.
----
Go
https://play.golang.org/p/id_D7Zh82jr
> Simplest "hello world" possible

- Puppet/hello_world.pp
This [Puppet](https://puppet.com/) manifest will run locally on the machine and print out two `Hello World!` messages.
Executed with `puppet apply hello_world.pp` (Assuming puppet binary is installed).
----
Puppet Manifest
> Added a hello_world printing Puppet manifest

- jocaml/hello.ml
Use the jocaml programming language to write hello world program
print "Hello World!" to the console
----
jocaml
> create hello world in jocaml

- VueJS/WatchVueJs
> Example about watch feature in vuejs

- PowerShell/CurlMyIP.ps1
The following command returns the public IP address of the localhost by looking up the
OpenDNS MyIP subdomain which returns information about the IP address that looked up the
domain.
----
Powershell
> Commit CurlMyIP.ps1

- Html/Table Example
- Html/ordered list
This is an example of how you can create an ordered list in HTML.
It will create an ordered list with numbers.
----
It is written in HTML.
> Ordered List Example

- JavaScript/hello-name.js
This program is a very simple CLI app that asks the user what their name is. The user can then input their name via command line and press enter. It then writes:
`Hello, <name>!` 
To stdout.
----
This is written in JavaScript.
> add a fun hello <name> node.js program

- Bro/main.bro
Prints "Hello, World!"
----
Bro
> Added Bro hello world

- C++/HelloWorldForAnIndian
> Adding hello world for my language (Hindi)

- C++/Binary Search!!
> Adding comments to make file easier to read

- JavaScript/Guitar Chord Chart Generator/chart-data.js
- JavaScript/Guitar Chord Chart Generator/guichart.js
- JavaScript/Guitar Chord Chart Generator/index.html
Generate a guitar chord chart based on chart-data.js using canvas
----
JavaScript
> Added New Program : Guitar Chord Chart Generator

- Bash/bulk_file_printer.sh
----
Bulk file printer. Asks the user for file extension and prints all files in working dir
----
Bash
> Added a bulk file printer for CL in bash, requests file extension.

- Html/hellofromNY.html
A simple webpage to say hello
----
HTML
> Added a hello world file to the HTML folder

- Java/Hello, Hello
> Create Hello, Hello

- C++/random_num_generator.cpp
The program will provide a random integer(no floating points) above 0 to the max number entered. 
----
C++
> Added C++ Random Number Generator

- NodeJS/phil-was-here.js
Displays 'Phil was here'.
----
Javascript
> Add Phil was here script

- PHP/Hello World Recursive
Reduced the code size, and it's preferred to don't close the PHP tag if the file is only PHP code
> Update Hello World Recursive

- C++/Add Two Numbers!!
> Update Add Two Numbers!!

- Python/Fibonacci.py
> Added Comments

- Python/palindrome2.py
> Rename palindrome.py to palindrome2.py

- NodeJs/.gitignore
- NodeJs/flatiron.js
- NodeJs/package.json
The program is a [flatiron.js](https://github.com/flatiron/flatiron) simple Hello World.
----
NodeJs/JavaScript.
> Added flatiron.js simple Hello World.

- Html/HHelloWorld
> HHelloWorld

- C ++/HelloWorldd
> HelloWorlddd

- PHP/hello_world.php
> php hello world

- C++/string_function.h
it is an implementation of some string functions
----
it is written in C++
> adding string functions

- Python/helloHacktoberfest2018.py
Printing Coder's Cities
Python
> Adding Strasbourg

- Python/calculator.py
Some simple Calculations
Python
> Now testing inputs !

- C++/floydWarshall.cpp
> Created floydWarshall.cpp

- Ruby/hello_world_el.rb
Creates a simple hello world script in **Greek**
> Greek hello world

- Python/hello_user.py
> Hello world Program in Python

- Python/TrailingZeroInFactorial.py
This code finds number of trailing zero in factorial of given number, Complexity of program is O(N) 
----
This is written in Python
> Finds Number of Trailing Zero in factorial of Given Number

- C#/hacktoberfest-c#-hello
Hello world in C# - showing GIT user name and current Year.
----
C# - Visual Studio 2018
> Hello world c#

- GraphQL/GraphQLAPI/.gitignore
- GraphQL/GraphQLAPI/hello-world-graphql.js
- GraphQL/GraphQLAPI/package.json
The program is a basic Hello World API.
----
NodeJs, using express, graphql, expres-graphql and graphql-tools.
> Added GraphQL basic Hello World API

- Python/Hello World in Python
> Grammatical error

- Java/Hello World.java
>  Hello  world in  Java

- Robot/hello-word.robot
- Robot/log.html
- Robot/output.xml
- Robot/report.html
search hello world
robot framework
> Added hello world robot framework

- Swift/Binary-Search.swift
- Swift/Find a Number in an Array
- Swift/kthLargest.swift
Binay-Search on an Array
Code for Finding a number in swift which returns Bool value depending on the element being searched
----
Swift 4
> Binay-Search on an Array in Swift 4

- Python/hello.py
It print "hello world" randomly
Python.
Use with color  2 in cmd.
> Random Print Hello World

- Golang/hello_from_the_other_side
- Golang/hello_from_the_other_side.go
> add golang hello world

- Python/hello_from_the_other_side.py
add hello_from_the_other_side.py
----
> add hello_from_the_other_side.py

- Bash/cron.sh
- Python/loading_Animation.py
Checks if a cronjob is running or not 
----
Bash
> Added CronJob Checker

- Mathematica/Dini's surface.nb
Calculate Dini's surface
----
Wolfram Language (using Mathematica)
> Dini's surface.nb

- Typescript/teste
> actions.ts

- Python/hello_waldo.py
prints 'Hello Waldo!'
----
Python
> add hello waldo!!!

- ASM_NASM_X86/palindrome.asm
Checks palindrome between two numbers in assembly language.
----
Assembly.
> Palindrome checking in assembly.

- PHP/HelloWorldFromCH.php
The program outputs Hello World in Swiss German.
----
The program is written in PHP.
> This is a Hello World file which outputs Hello World in Swiss German

- asciidots/helloworld.dots
The program just prints out hello world
----
It's written in the [AsciiDots](https://esolangs.org/wiki/AsciiDots) language
Code was shamelessly stolen from [here](https://github.com/aaronduino/asciidots)
> Added helloworld for asciidots language

- Java/HelloWorld/Hello-world.java
> This is Hello world file written in java

- C++/say_hello.cpp
Displayed a message to ask for the users' name.
----
> Updated say_hello.cpp

- GDScript/hello_in_childNode.gd
Script to set a label child node text property to "Hello World!"
Get the label node in childNode_label variable, and then set its text property to "Hello World!" when it is loaded
----
GDScript
> hello_in_childNode.gd

- C++/hello__world.cpp
> First Contro.

- GDScript/endless_hello_printer.gd
Prints "Hello World!" endlessly until the user stops it
Prints "Hello World" in every frame until the user presses "ui_accept" button (the default key is spacebar)
----
GDScript
> endless_hello_printer.gd

- Arduino/helloworld.ino
"1152" is not a correct baudrate
> Correcting baudrate in helloword.ino since "1152" is bad

- Perl/odd_or_even.pl
finds a given number is odd or even
----
perl
> odd or even in perl | Hacktoberfest'18

- GO/variadicFunction.go
Added variadic multiplication mechanism. Can pass any number of parameters to execute the multiplication.
`multiplication(1,2) = 2`
`multiplication(1,2,3) = 6`
----
Go
> Variadic Multiplication

- Python/sum_of_multiples_of_3_5_until_1000.py
> Hacktoberfest2018

- Kotlin/greetings.kt
> Improve Kotlin structure

- Swift/hello-world.swift
Prints out "Hello World!"
----
Swift
> Added a hello world program

- fstar/hello.fst
Prints `Hello, World!`.
----
[F*](https://www.fstar-lang.org/)
> add F* program

- C#/HelloWorldUsingStaticConstructor
Hello World Using Static Constructor
c#
> HelloWorldUsingStaticConstructor

- C#/HelloWorldUsingInheritence
Creating hello world program using inheritance.
c#
> HelloWorldUsingInheritence

- java/helloworld.java
Simple print Hello World to console.
----
It is written in java
> helloworld.java is created.

- 8th/fizzbuzz.8th
----
This program an example of the FizzBuzz program written in eighth.
This program was written in [8th](https://8th-dev.com), a secure, cross-platform, efficient, cost-effective, robust, and fun concatenative programming language for mobile, desktop, server, and embedded application development.
> Add 8th fizzbuzz

- Python/tower_of_hanoi.py
Shows the process of the tower of hanoi.
----
Python 3
> Added tower_of_hanoi with command line actions

- C/Subtraction.c
Give the Subtraction of given two numbers
----
C
> Create Subtraction.c file

- .gitignore
- Python/hello_world_flask/app.py
- Python/hello_world_flask/requirements.txt
A simple Hello World with Flask framework.
----
Python, using the package Flask, to install:
cd Python/hello_world_flask
pip install -r requirements.txt
to run just do a:
flask run
> Sample Hello World with flask.

- Python/hello_word.py
> Hello world in Python

- 8th/helloworld.8th
----
This simple program is the most basic hello world written in eighth.
This program was written in [8th](https://8th-dev.com), a secure, cross-platform, efficient, cost-effective, robust, and fun concatenative programming language for mobile, desktop, server, and embedded application development.
> Add 8th hello world

- C++/TicTacToe_vs_cpu.cpp
Single player tic tac toe. Play against CPU.
Play Tic Tac Toe against your computer. Single player game.
----
C++
> Tic Tac Toe vs CPU

- GO/sqrt.go
- Shakespeare/reverse.spl
Golang: sqrt.go reimplement math.Sqrt() function
Shakespeare: reverse.spl reverse the input
Golang
Shakespeare
> Shakespeare lang and Golang

- Cool/hello-world.cl
It prints "Hello, world!".
----
Cool (Classroom Object Oriented Language)
> Added Hello World in Cool

- C/pyramid.c
> added pyramid pattern program in c

- C++/operatoroverloading.cpp
Added a C++ program on operator overloading
----
> operator overloading

- C++/resultGenerator.cpp
- C++/tempconv.cpp
> Cyberdhirendra patch 1

- Shell Script/sayH.sh
> add sayH.sh

- c programming/hello.c
A simple hello world program
----
Written in c programming
> my contributiion

- hello_in_java/hello_world.java
----prints hello world to the console
Java
> first pull request

- PHP/say-hello.php
> Hello From Bristol

- Fantom/HelloWorld.fan
- Zimbu/helloworld.zu
> Zimbu language

- Fantom/HelloWorld.fan
> Add fantom language

- Omgrofl/helloworld.o
> Add Omgrofl language

- Dart/Fibonacci.dart
Find the fibonacci sequence.
----
Dart.
> Add Fibonacci.dart

- Python/helllllloworld.py
> first hello world program in python

- C#/BonjourCSharp.cs
- Scala/BonjourScala
Signed-off-by: Mian Sarim Hameed <miansarimhameed@gmail.com>
Print Bounjour CSharp (Hello CSharp)
----
C#
----
> Print Hello CSharp in French

- Python/current_time.py
this is a simple python program which uses the datetime library to fetch the current time and date and print the same.
----
python 2.7
> current_time.py

- Swift/Hello.swift
Prints: Namaste from India.
----
Written in Swift.
> Added greetings from India, written in swift.

- Java/Helloworld.java
print Hello World !!
----
java
> This is a simple program using java language

- Kotlin/beer-song.kt
It prints a hundred rows of a famous beer song  
----
Kotlin
> added a beer song in Kotlin

- BIRL/hello_world_en-us.birl
Hello World in EN-US
----
[BIRL ](https://birl-language.github.io/)
> Add hello world in BIRL in en-US

- PHP/HelloWorldFromPh.php
Hacktober fest Pull-request from xander
> Hello world PR

- Python/.gitignore
> gitignore .DS_Store files

- GDScript/random_hello_printer.gd
Hello World printer with random number.
Prints either "Hello World!" or "Hi World!" according to the random number rolls.
----
GDScript
> random_hello_printer.gd

- C/helloWorldWithoutMain.c
The Program prints hello world.
It uses a preprocessor directive that creates an impression of running the program without main function
----
It is written in C
> Hello World without main function

- Amiga/Hello world!
> Create Hello world!

- GDScript/timed_hello_printer.gd
Time based 'Hello World' printer in GDScript
Prints 'Hello World' every 2 seconds and prints how many times it has been printed
----
GDScript
> timed_hello_printer.gd

- Java/RMIPrimeNumber/Prime.java
- Java/RMIPrimeNumber/PrimeImpli.java
- Java/RMIPrimeNumber/PrimeNumberRMI.java
- Java/RMIPrimeNumber/PrimeServer.java
- Java/RMIPrimeNumber/README.md
Java RMI application to check whether the given number is Prime Number or not.
----
Java
> RMI Prime Number checker

- GDScript/hello_printer.gd
Prints 'Hello World' message when spacebar is pressed.
----
Godot Engine script, or gdscript
> hello_printer.gd

- Angular/src/app/post.component.html
> add body to post list

- Python/HelloGitHub.py
---- Just says hello to all the GitHub users (Mostly to practice how to make pull requests!)
Python
> added HelloGitHub.py

- Python_tornado_hello_world/hello_world_tornado.py
- VueJS/WatchVueJs
Python web framework Tornado hello world show case .
----
Tornado in Python
> add Python tornado hello world

- C/sumanth_handle.c
---- Prints out  my github handle
C
> added program

- Groovy/com/hello/HelloWorldGroovyClass.groovy
Created a Groovy class to say Hello World
Groovy
> Added groovy class to say hello world

- Python/binary_tree.py
- Binary Tree implementation using Node as the base entity.
- Node is a class that holds data for a Node, its left and right children.
Python
> Add binary tree implementation

- Bash/Install-Qemu-image-and-create-img.sh
- Bash/Install-iSCSI-Target.sh
- Bash/install-openvswitch-centos.sh
- Bash/install-qemu-kvm.sh
- Python/hello_world_python3.py
Ouput Hello World to minitor
----
python
> Create  hello_world_python3.py

- LaTeX/LaTeX_CN.tex
geneate a pdf contain '你好，LaTeX ！', which mean hello LaTeX in chinse.
----
LaTeX using Ctex micro package and chinses.
> add Hello World in Chinse via LaTeX

- JavaScript/helloWorldAndrew.js
output hello world
----
javascript
> add andrew

- Docker/hello-world.dockerfile
This program builds a Docker image using Bash that prints `Hello, world!` to the screen!
----
A Dockerfile is a simple text file. To get it started, run these commands:
```bash
$ docker build -f hello-world.dockerfile -t hello-world .
$ docker run --rm hello-world
```
> Added hello world sample for Docker!

- html/hello_world.html
the hello world sentence scrolls from right to left
It is a html program that displays scrolling text
html
> added hello_world.html

- JavaScript/AHelloWorldFromEarth.js
A hello world 
----
javascript
> AHelloWorldFromEarth

- JavaScript/hello-world-himno-mx.js
Hello World and Himno de México
----
Javascript
> Hello world, Himno de Mexico

- C#/SelamDünya.cs
Hello World in Turkish!
----
C#
> Add Turkish Hello World in C#

- Java/Mathematics/PotenciaRecursiva.java
- Python/recursive_power.py
program that calculates the power of any number
----
Java and Python
> add recursive power in java and python

- Monkey/Hello.monkey
Prints "Hello, Hacktoberfest"
----
Monkey
> Hello World in Monkey

- Python/PasswordManager.py
The program acts as an insecure password manager.
----
Its written in Python 3.
> Added insecure password manager

- C++/Hello World
> Add output to file

- Python/rand_forest_reg.py
> script for random forest regression

- Cpp/min_hello_world.cpp
> add output in mi_hello_world file

- Python/svr.py
> script for support vector regressor

- Python/dec_tree_reg.py
- Python/svr.py
> decision tree regressor

- C++/hellolight.cpp
Print Hello HACKTOBERFEST
----
C++
> Add hellolight.cpp

- CSS/flex, BEM/index.html
- CSS/flex, BEM/main.css
just code example about flex and BEM style
----
just used html and css
> created new CSS code example

- C/int_sat.c
- C/pec15.c
* This function takes an float input, a min, a max and returns the same values if it is within min and max or returns the min if less than min, or max if greater than max.
* If the value is outside the min or max the valid pointer is set to zero.
* ANSI C
> Integer saturation function

- Python/welcome.py
The program gives the 'welcome to Python world' message.
Python
> Python code

- JavaScript/alert in malayalam
- JavaScript/alert in malayalam.js
> Hello world in malayalam

- Python/brutus.py
- Python/encrypt_image.py
encrypts the images
encrypts a given image 
python
> Addeed the main encrypting file

- C++/Hello_World_Cpp
> add output to hello world

- C++/min-max.cpp
Minimax is a kind of backtracking algorithm that is used in decision making and game theory to find the optimal move for a player, assuming that your opponent also plays optimally. It is widely used in two player turn-based games such as Tic-Tac-Toe, Backgammon, Mancala, Chess, etc.
----
The Code is in C++
> MinMax Algorithm in game theory

- Rockstar/fizzbuzz.rock
> add fizzbuzz in rockstar

- C++/hello_bkhanale.cpp
Prints `Hello @bkhanale` at terminal.
----
C++
> Added hello_bkhanale.cpp

- Python/topological_sort.py
- cpp/bubble_sort.cpp
----sorting using primitive sorting algorithm
---- C++
> bubble_sort added

- C++/Anagram.cpp
It checks whether 2 provided string as input are anagrams(have same letters in them) or not.
C++
> add anagram code into c++ codes

- Python/ron_swanson_quote_generator.py
Generates Ron Swanson quotes from an json API.
----
Python
> ADD: ron_swanson_quote_generator.py

- Html/CanvasHelloWorld.html
It is a simple page that show how to use HTML Canvas element and how to draw over it.
----
HTML and JavaScript
> Created HTML Canvas hello world

- Javascript/aloha_world.js
prints Aloha World
----
JavaScript
> aloha world

- Python/EloRanking.py
This is the Elo ranking Algoorithm which was used by Mark Zukerberg to create facemash. This algorithm is also used to rank chess players.
> Elo Ranking Algorithm

- C++/DynamicProgramming/longest_common_subsequence.cpp
Solution for [Longest Common Subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) using [Dynamic Programming](https://en.wikipedia.org/wiki/Dynamic_programming).
----
C++
> Add solution for Longest Common Subsequence(LCS) using DP

- Actually/hello_world
Reverts Hacktoberfest-2018/Hello-world#2901 as it entirely removes the functionality of the program.
See #2389 for details.
> Revert #2901 - "added hello world insted of H"

- JavaScript/Instagram 9x9 Grid maker/index.html
Split and image into 3x3 grid for instragram feed
----
JavaScript
> Upload new program

- C/HelloWorldvmsantos.c
Simple HelloWorld
-----
Written in C
> HelloWorld in C

- Befunge93/README
- Befunge93/helloworld.bf
The program prints hello world in the Esoteric programming language known as Befunge. 
----
Befunge 93
> added hello world in befunge

- Golang/quick sort
----quick sort algorithm
golang
> Create quick sort

- ABAP/helloworld-Korean-ABAP.txt
Displays hello world in Korean
----
ABAP
> ABAP like K-POP

- Ruby/pangram.rb
Takes an input phrase and checks to see if that sentence includes every letter in the English alphabet
----
Ruby
> add pangram

- PHP/ReverseHelloWorld.php
Add a reversed Hello World
----
PHP
> Add reverse hello world

- JavaScript/age.js
Vanilla JS to calculate your age from input
JavaScript
> Add age.js

- Kotlin/hello-world-zip.kt
Writes a hello world message by using Kotlin zip function.
----
Kotlin
> Added hello world with ZIP function

- PHP/OOP/helloo.php
> add brackets for clarity

- C/add_two_matrices.c
this programs adds two matrices 
----
C language
> adding code to add two matrices

- C/dc_filter.c
A random number is genarated and sets an offset than main routine used to estimate added fixed offset.
----
C was used.
> iir dc estimator added for referance.

- PULL_REQUEST_TEMPLATE.md
Fix the grammar in the pr template
> Fix the grammar in the PR template

- Python/MANY TO MANY RELATIONSHIP
show the demonstration Many to many relationships in the database
----
> Create MANY TO MANY RELATIONSHIP

- Rust/hello_hackers.rs
ask or user input (his name)
prints Hello World with that name
Rust
> add a rusty hello World to Hacktoberfest from Bochum

- Python/PiCalculator.py
Calculating Pi number using Monte Carlo method
----
Python
> adding PiCalculator.py script

- JS/index.js
> Add Hello World JS

- PHP/HelloWorldFromPH.php
PHP developer from Philippines!
Prints 'Hello world from Philippines'.
----
PHP
> Added PHP file HelloWorldFromPH

- C++/constexpr_factorial.cpp
Given a number less than 21 as the first argument, prints the factorial of that number.
----
Written in C++
> add constexpr_factorial

- Hello world python/python says hello
> Create python says hello

- JavaScript/download_pdf_file.php
Instead of opening file in browser this function open the provided PDF file and download in new window.
----
PHP
> Added function to download PDF file

- NotePad/HelloWorld.txt
> ADD NOTEPAD

- AIML/helloworld.aiml
A simple chatbot program written in AIML. It compares the user input against the phrase in each of tags using REGEX, and if there is a match the phrase from the tag is returned.
A separate AIML, such as pyaiml, is needed to run the program.
----
AIML (Artificial Intelligence Markup Language)
> Add Hello World in AIML

- Java/HelloWorldZephi
> Adding my first pull request for Hacktober

- Python/reply_reverse.py
It asks for a sentence and then output the reversed string.
----
It is written in Python.
> Add a reverse-word python script

- JavaScript/es6-hello-world.js
----
It logs "Hello World" using ES6 and async JavaScript.
JavaScript
> Add ES6 hello world!

- Python/sleepsort.py
The program takes a list of integers and outputs them in ascending order by sleeping n seconds for each integer asynchronously.
----
Python
> Add python sleep sort implementation

- Bash/HelloWorld!
> Rename HelloWorld to HelloWorld!

- GO/factorial/factorial.go
#33 Demonstrate three different ways of implementing factorial in Go, namely: recursive, iterative and tail recursion approaches.
----
Golang
> Added three different ways of implementing factorial in Go.

- C/sort.c
added selection sort method
----
C
> add selection sort method

- JavaScript/say hello world x times
Print hello world x times
----
Javascript
> Create say hello world x times

- PascalLanguage/helloword_bosnian
hello world pascal program but in bosnian
hello world pascal program but in bosnian
----
Pascal
> new hello world pascal program

- Actually/hello_world
> Added text "Hello world"?

- BIRL/functions.birl
Improve the Birl repo with functions
BIRL
> How create functions on Birl

- Python/readMatFile.py
> Add readMatFile

- C++/Height of binary tree.cpp
- C++/TreePreorderTraversal.cpp
- PHP/binarySearch
> Code for binary serach in php

- cpp/helloworld.cpp
> First open source contribution

- Cpp/solution.cpp
> Hello, World!

- shellkore/saying hello
> saying hello

- PHP/hello-world-with-heredoc.php
> Created hello world with heredoc

- C++/helloworld21.cpp
> Rename helloworld.cpp to helloworld21.cpp

- Html/Hello world heading.html
> Update Hello world heading.html

- Python/sentiment_analysis.py
> add python program

- Battlestar/hello.bts
Outputs "Hello, World!" and a newline.
Battlestar
> Add Hello World in Battlestar

- C++/Reverse a number.cpp
- C++/Second Largest.cpp
- C++/Square Roots.cpp
Displays the reverse of a given number.
----
The first line of input contains an integer T, total number of testcases. Then follow T lines, each line contains an integer N.
C++
> Create Reverse a number.cpp

- Python/logging.py
display logs on STDOUT, and write them in a file if option verb is true
Python
> Add logging class

- Python/hello-world-random-caps.py
Prints "Hello World" but in random caps like "hEllo wOrlD".
Python
> Added hello-world-random-caps.py

- AWK/hello_world.awk
> Added Hello World in AWK

- C++/InsertionSort123
> InsertionSort123

- Python/ASCIIArt.py
Who doesn't like ASCII ART
Displays ASCII art of hello world.
----
It is written in python.
> ASCII Art in Python

- C++/LCM of intergers a and b.cpp
Find the lowest common multiple of 2 integers (a & b)
----
C++
> Lowest common multiple of 2 integers

- Java/abc
Add logic to the main method. 
----
Java
> Fix compile issue.

- Bash/helloworld.sh
> Specify type of script

- Ruby/count_char_on_string.rb
> Add a method in order to count char on a string.

- Bash/Helloctober.sh
Say Hello world in bash
----
Bash script
> Hi from Helloctober

- Ruby/fibonnaci.rb
This program return the fibonacci number at the index you enter, starting with 0 return 0. 
The fibonacci function return (nbr -1) + (nbr -2)
----
The program is written in ruby
> Add of fibonacci.rb

- MSF4J/Hello-Service/Hello-Service.iml
- MSF4J/Hello-Service/pom.xml
- MSF4J/Hello-Service/src/main/java/org/example/service/Application.java
- MSF4J/Hello-Service/src/main/java/org/example/service/HelloService.java
A simple hello service written to demonstrate the implementation of the basic HTTP methods using the MSF4J framework.
Uses the [MSF4J framework](https://github.com/wso2/msf4j)
> MSF4J hello service

- Ruby/countdown.rb
It's a countdown.
----
In Ruby.
> Countdown added.

- C++/printingLinkedList.cpp
> printingLinkedList.cpp

- Dart/exceptions.dart
> Dart - exception example

- KennySpeak/helloworld
> Add KennySpeak

- Bash/html_check
This bash script checks whether in an html file all the tags are correctly opened as well as closed. You can call it **html _tags_syntax_parser**.
----
Written in bash.
> html_check

- Java/ALPHA PATTERN
PRINTS FOLLOWING PATTERN 
A
BB
CCC
DDDD
and so on !
----
> ALPHA PATTERN

- NewRelic/hello.nrql
It prints the number 1 in the units of "Hello World!"
----
New Relic Insights NRQL syntax.
https://docs.newrelic.com/docs/insights/nrql-new-relic-query-language/nrql-resources/nrql-syntax-components-functions
> Adding New Relic Insights NRQL query

- Python/Hello Vicky!.py
Prints a message a number of times.
----
Python.
> Create Hello Vicky!.py

- Java/BaiTap1.java
- Java/BaiTap10.java
- Java/BaiTap2.java
- Java/BaiTap3.java
- Java/BaiTap4.java
- Java/BaiTap5.java
- Java/BaiTap6.java
- Java/BaiTap7.java
- Java/HelloWorld122213.java
- Java/HelloWorld1223.java
calulator : S(n) = 1 + 2 + 3 + … + n.
----
Java
> 20181710 new pull request

- Hy/hello_githubuser.hy
- Python/helloworld_izm.py
Greets the user.
----
Python 3.6
> Python script

- Python/count_contributions.py
Counts how many files are in the Python folder of the Hacktoberfest _Hello-World_ repo.
----
Python
> count the number of Python contributions

- Actually/hello_world
> Used C++ for Hello World

- Cpp/solution.cpp
> updated hello-world

- ring/hello,world.ring
> Printing Hello-World using Dynamic Typing.

- C/Hello Romania.c
> Update Hello Romania.c

- JavaScript/timeSince.js
This is a standalone function and can be imported directly (in ES5 or ES6).
It returns the time since a particular timestamp (converted to `xx s ago`)
----
JavaScript (ES5)
> ADD: A new function to return the past time. (ago)

- Advpl/HelloWorld.prw
- Advpl/README.md
Hello World with advpl
----
print the hello world on the screen
> Advpl hello world

- C/HelloTaiwan.c
> hello india.c

- Terraform/hello_world.tf
- Terraform/terraform.tfstate
Prints Hello world once you run `terraform apply`
----
Terraform
> Add Terraform hello world example

- LaTeX/LaTeX-FR.tex
First Hacktober commit.
Creates a document that reads Hello World in French
----
LaTeX
> Hello World in French

- CRYSTAL/hello2.cr
Hello, world! With type annotations
Crystal
> Hello world in Crystal, using type annotations

- C++/Fit_square_in_equilateral_triangle
The program can calculate the number of squares that can fit in an equilateral triangle, it only includes the squares that can fit entirely.
----
C++
> program to calculate squares that can fit in a equilateral triangle

- C++/numbers from 1 to 100
> print one to hundered

- Ruby/hello-world-in-vietnamese.rb
It print the phrase "Hello world, from Vietnam" in Vietnamese
----
Ruby
> hello world from Vietnam

- C/special number.c
A number is special if it is possible to remove some digits from it to get a number having 3, 5 or 6 only.
For example, 38597 is special since it is possible to remove digits 8, 9, 7 to get 35. You cannot remove all the digits.
You can remove digits from left, right or middle.
Write a program in C which given a number N, calculate how many divisors of N are special
Input:
An integer N
Output:
Output in a single line the number of divisors which are special.
Constraints:
1 <= N <= 109
----
C
> Create special number.c

- Ruby/epsv.rb
> Searches extended passive mode used for passive

- Python/heiverden.py
prints hei verden (hello world in norwegian)
python
> hei verden

- Ruby/convert_files_to_task.rb
> Convert files to tasks

- Python/helloWorldUserName.py
* Added helloWorld.py which takes user name as input and greets the user
Prompts for user's name and then greets the user with their name.
----
Python
> Added helloWorld.py

- NodeJS/helloWorldServer.js
----Instead of using console.log() to print hello world in terminal, I have created a local host to print hello world in the browser.
NodeJs
> Hello World server hosted locally on PC.

- JSON/basicHelloWorld.json
> Rename helloWorld.json to basicHelloWorld.json

- Cpp/Is it square?
> Update Is it square?

- Python/helloworld!
> created hello world file

- Python/helloworld_Turkish.py
Print Hello World in Turkish
----
Python
> added Python/helloworld_Turkish.py

- Java/array intersection
To find common elements in two user defined arrays !
finds common elements in two arrays !
----
JAVA
> Array intersection in JAVA

- Java/HelloWorld/helloWorldJava
> hello world in java

- C Language/oddEvenC
> odd even in c

- C Language/helloWorld
> hello world c

- Hello world python/mariana_hello_world.py
print Hello World using python 3
----
Python 3
> First commit Hello World

- C++/hellovietnam.cpp
> hello world from viet nam

- ArnoldC/hello_world_until_max.arnoldc
Prints "Hello, world!" 10 times (or whatever the max variable is set to)
[ArnoldC](https://github.com/lhartikk/ArnoldC)
[Try it online!](https://tio.run/##fZDBTsMwEETv/YqhFy4c4A9w021t1fZG9roox4hWAikkUnOAvw8OpRVCmL3taGf2adpTP3SH52kychsRNT@JcbRAHk0NKh1MFKciJBDhdbTHcZSXtnftx9fRPA0nRBKkiFTj0TPqwCtLjks5b0X3w33J0xccZ0MUU@2gAie/LmBus0UYoilHc11T@JF5fhoIJsI1MH5vRIlh/@tmDpkxryJ5TlsNUXZ31ebl8kqrDLTUx64b7vA@nLrDzfI/pL/Zy3jfhV3G5kTebBDZUS6FlMOKvM9qX0SutLF2Mbeq1Z7yPXkIBWe8ElpP0yc "ArnoldC – Try It Online")
> Added ArnoldC/hello_world_until_max.arnoldc

- JS_Hello_Everyone/HelloEveryone.js
rewrites map function
----
javascript
> added hello everyone and map function

- Python/hell_o.py
prints The Zen of Python
----
Python 3
> Some reminder what is this all about ;)

- C++/bookreader/bookreader.cpp
- C++/bookreader/olivertwist.txt
Program prompts user to enter in a file to read from, and will read from the file if specified file is in the same directory as the .cpp file. Program attempts to find the most frequent word in the file, removing all punctuation and capitalization.
Also added olivertwist.txt for testing, just in case you don't want to go to google to find a book in .txt format :)
C++
> added bookreader.cpp and olivertwist.txt

- C++/sort.cpp
> commit-103

- Python/RomanNumeralsDecoder.py
It's a Roman Numerals Decoder
----
Python
> added codewars katas solutions

- graphql/helloWorld.gql
Simple .gql file simulating 'hello world' query
graphql
> Creating hello world using graphql

- C/Armstrong-Number
Signed-off-by: Shubham Bhandari <dev.sb18@gmail.com>
Finds a number is Armstrong or not.
----
C Programming Language
> Created a file for Armstrong Number

- C++/reverse_linked_list_recursive.cpp
It reverses a linked list recursively
----
C++
> added c++ program to reverse a linked list

- C/Suparmarket Management System
This is a small C program to demonstrate how we could use programming to automate the ordering process and handling of money in shops and restaurants.
It automates the process of ordering stuff and handling money to relieve customers of the hassle they have to go through when shopping as well as to ensure proper service to the customers.
----
It is written in C.
> Suparmarket/Restaurant Management System

- C++/Hello__World.cpp
> add C++ Hello-world

- C/find day from DOB
>  find day from DOB

- Python_codes/gridworld.py
Reinforcement Learning based code for GridWorld problem
----
Python
> Added Python code for GridWorld

- Ruby/learnrubythehardwayex1helloworld.rb
Simple ruby hello world from the Learn Ruby the Hard Way book, exercise 1.
----
Ruby
> Add Ruby/learnrubythehardwayex1helloworld.rb

- Python/string_concat.py
> resolved conflicts by another pr

- JavaScript/TopKFrequent/TopKFrequent.js
- JavaScript/TopKFrequent/TopKFrequent.test.js
Algorithm that figures out top k frequent number in a list
----
JavaScript
> add topkfrequent to javascript folder

- Python/hellohacktoberfest.py
- hello.py
> create a hellohacktoberfest.py file in python folder

- Java/DataStructure/Arrays/HasDuplicate.java
Given an array of integers, find if the array contains any duplicates.
The function should return true if any value appears at least twice in the array,
and it should return false if every element is distinct.
[1, 2, 3, 4, 4, 5]
[1, 2, 3, 4, 4, 5]
true
JAVA
> If an array has duplicate elements

- Python/hello-from-holland.py
Print hello from Holland
----
Python
> Happy hack-o-ween

- Java/HelloJupiter/HelloJupiter.java
this program prints Hello Jupiter
----
java
> helloov jupiter

- Python/hima_hello_world.py
> add python hello world

- Java/ForLoop.java
> java for loop

- CPP Programs/Prime Generator
----This program prints  prime numbers between given two numbers.
This is written in C++ .
> Prime Generator

- Amiga/Hello world!
> Updated Hello World using Logo

- Python/mygreet.py
>  mygreet.py

- C++/counting_sort.cpp
implementation of counting sort  on an array of intergers
C++
> added counting sort in cpp

- Python/factorialgenerator.py
>  factorialgenerator.py

- C ++/Mars_Exploration_Hackerrank.cpp
> Added Mars_Exploration Problem Hackerrank

- Java/HelloFromLviv.java
Prints 'Hello World from Lviv'
JAVA
> Hello World from Lviv

- C Language/hi.c
> make change

- Bash/cowsay-hello-world.sh
Shell script to output Hello World with cowsay
```
$ ./cowsay-hello-world.sh
______________
< Hello, World >
--------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```
----
Shell script (Bash)
> add Hello World with cowsay

- Reactjs/src/App.css
- Reactjs/src/App.js
Add a rainbow text
----
I add some css and ajust form in app.js
> add rainbow text

- enriquezm/app.css
- enriquezm/app.js
- enriquezm/index.html
Animates a ghost with "Hello, world!".
* html
* css
* js
> Create scary world.

- C/sort.c
add insertion sort method
----
C
> add insertion sort method

- VueJS/HelloWorldVueJSHacktoberfest/index.html
- VueJS/HelloWorldVueJSHacktoberfest/main.js
- VueJS/HelloWorldVueJSHacktoberfest/style.css
It displays Hello World and Hacktoberfest 2018 using a VueJS component.
----
VueJS
> VueJS Hello World example.

- JavaScript/randomHelloWorld.js
Randomly selects a version of Hello world! from an array and then displays it to the console.
----
JavaScript
> add randomHelloWorld.js

- JavaScript/rock_paper_scissors.js
Rock Paper Scissors Game 
----
Javascript
> Add Rock Paper Scissors in Javascript

- JavaScript/HelloWorld.html
The programn prints a HelloWorld in JavaScript on the console and using an alert.
JavaScript.
> Add HelloWorld in JavaScript

- Python/genetic_algorithm
genetic algorithm with a little change
----genetic algorithm with a little change to minimize sphere
python
> genetic_algorithm2

- FALSE/check_prime
check prime number between 1-100
----
check prime number between 1-100
python
> kamithanthanh

- Hack/helloWorld-esp.php
Imprime una variable con el texto "Hola Mudo, Hacktoberfest 2018"
----
PHP
> Jacinto Rammirez

- Python/SumOf2Numb.py
calculate the sum of two integer
----
python
> the sum of two integer

- NodeJS/module-commonjs.js
Creates a NodeJS CommonJS module that exports the string "hello world."
----
JavaScript (CommonJS)
> add CommonJS NodeJS module

- NodeJS/module-es6.js
Creates a NodeJS ES6 module that exports the string "hello world."
----
JavaScript (ES6)
> add ES6 NodeJS module

- Python/hello_world_hacktoberfest.py
Takes a list of ints that hold ascii values corresponding to **Hello world! Its Hacktoberfest** and converts the value to their respective characters iteratively to print the same 
Based on #17 
Python
> Hello World (Hacktoberfest)

- Lua/Luaselection_sort.lua
Represents the selection sort algorithm
----
Lua
> Added Selection Sort!!!

- speedTester/.directory
- speedTester/finalShell.sh
- speedTester/logs/average.py
- speedTester/readFromFile.c
- speedTester/readFromFile.cpp
- speedTester/readFromFile.java
- speedTester/readFromFile.py
- speedTester/shells/cTester.sh
- speedTester/shells/cppTester.sh
- speedTester/shells/javaTester.sh
- speedTester/shells/pyTester.sh
Running "finalShell.sh" runs all programs to read through a 370,000+ word file [that you can find here](https://github.com/dwyl/english-words/blob/master/words_alpha.zip). Each language searches for "zulu" in the text file (chose zulu because it's so far down the file), and writes the time it took to complete the process to a file in the "logs" folder. If you can find a way to make this more efficient, please do! 
In general, in order from fastest to slowest, my tests ran an average of:
0.12528969923000005 seconds for Python
0.03976097 seconds for C
0.038764757 seconds for C++
0.3368500018119812 seconds for Java
Python, C, C++, Java, and shell scripts
> Speed tester

- CRYSTAL/99bottles.cr
> 99 object-oriented bottles of beer in Crystal

- C#/hello world PMB.cs
> I added hello world in c# language

- Kotlin/functionalCalculator.kt
Simple calculator in functional way
----
Kotlin
> simple kotlin calculator in functional way

- C++/AvlTree.cpp
Easy implementation of AVL tree using classes tested on DEVC++
Implements AVL tree and its basic operations
----
C++
> Updated entire "new code"

- Python/Python program/Hello_World.py
Hello world! in five languages
----
python
> Hello world! in five languages

- C/hello_world_epitech.c
Print hello world without using stdio.h and stdlib.h, only using unistd.h and write() function.
C
> feat/hello world: Epitech way

- Javascript/hello world. 2D world
'hello world' in 2d world <3
p5js
> Create hello world. 2D world

- Hello world python/scrolling_hello.py
Scrolling Hello World
----
python
> Create: Scrolling Hello World!

- Golang/hello_from_Indonesia.go
Showing hello world in Indonesia language 
----
Go
> Add Hello World from Indonesia

- GO/hello-world-len.txt
it's show length of hello word
----
go
> length of hello world

- JavaScript/Title Case A Sentence
The function titleCase() within the program takes a sentence as an argument and returns a new sentence in which the first letter of every word is uppercase/title case.
It title cases any valid sentence.
----
Javascript.
> A program to title case any sentence

- Kotlin/Country.kt
showing sample of using data class
----
Kotlin
> add data class example

- C ++/imgenhancement.cpp
Simple median filter with 8-neighborhood
C++
> add median filter with opencv in c++

- Java/HelloWorld/helloWorld.java
hacktoberfest woooo
print hello world
-----
java
> add helloWorld java

- Python/Battleships.py
Its basically a game of battleships.
Python
> Add battleships

- Elixir/factorial.exs
Simple factorial implementation with Elixir language.
Elixir
> Factorial implementation with Elixir

- Kotlin/BasicDataSourceConfigurationForSpringBoot.kt
This is a basic configuration file for datasource bean for Spring Boot. This was one of the first things I was having difficulties back when learning to build APIs with Kotlin and Spring Boot so I want to help next one :)
----
Kotlin
> Created an example of datasource bean configuration in Kotlin

- Vyper/helloworld.vy
Returns an "hello world" message
----
It is written in a new experimental language called Vyper, used to write smart contracts in the Ethereum blockchain.
> Add Hello World in Vyper

- Python/hello_pygame.py
Open a PyGame window and display the message "Hello, Pygame!"
----
python with pygame
> added hello_pygame.py

- C#/HelloWorldPTPT.cs
Prints `Hello World` with the Portuguese flag colours.
----
It was written in C# (CSharp)
> Add hello world in Portuguese from Portugal

- Jenkins/Jenkinsfile
- Jenkins/Node.js/Jenkinsfile
----
Simple Jenkins pipeline in Java
Groovy
> Add Jenkins Getting Started Script for Java

- CPP Programs/Hello_World.cpp
This Program prints Hello World in different Programming Languages.
----This Program prints Hello World in different Programming Languages.
cpp
> Hello_World in different Programming Languages

- Kotlin/hello-world-bugis.kt
Showing hello world in Bugis language 
----
Kotlin
> add hello world for bugis lang

- BETA/helloworld.beta
Prints "Hello world!"
----
BETA
> Added beta language

- JavaScript/db-hello-world.js
Prints 'hello world' to the console. 
----
JavaScript
> Created new Hello World js file

- C/factors.c
- C/pattern2.c
made the program generalized for any number of rows....
----
C language
> add Patterns anmol20goyal

- C/factors.c
some changes in the factors.c--as 1 and the number itself are also the factors of the given number.....
And also used for loop instead of the while loop....
----
C language
> add factors anmol20goyal

- AngularJS/app.js
- AngularJS/index.html
> Print Hello world

- C ++/Number add 2
> made a number add

- C++/Add N+ Numbers!
(N+ being the set of integers greater than 0)
The program asks the user for the number of integers to add. N numbers are then added and the sum is output.
----
C++
> Create Add N+ Numbers!

- Hello-world-Java/.classpath
- Hello-world-Java/.project
- Hello-world-Java/.settings/org.eclipse.jdt.core.prefs
- Hello-world-Java/src/main/HelloWorld.java
> Commit Hello World in Java

- C/hanoy.c
----my program makes the hanoi tower recursively.
C
> adding hanoy in c, recursive

- JavaScript/babysteps.js
> added babysteps

- JavaScript/HelloWorldFromBrazil.js
Strange things. And "Hello world!".
Javascript
> Add JavaScript/HelloWorldFromBrazil.js

- Kotlin/estensionFunctionHelloWorld.kt
hello world with extension function
----
kotlin
> kotlin hello world with extension function

- Python/1579_hello.py
> Yet another Hello World.

- Python/Rich_Calculator.py
##Hacktoberfest.
Completes Issues #166 
* Basic Rich Calculator which support basic arithmetic. (Mac Like)
* Supports Operations to Output of the previous Operation.
> Create Rich Calculator (mac/linux like).

- C/tricky-hello.c
Prints "hello" on the console. 
----
C
> Added One more hello world C program

- Python/fibonacci.py
- Python/helloworld!
> fibonacci series python

- Java/HelloWorldVietnamese-Only
Asks user what language they want the program to print Hello World in
If the user types Vietnamese (ignoring cases), it'll print out Hello World in Vietnamese
If not, the user gets an apology
----
Java
> Hello World in Vietnamese with Scanner

- Java/GutenTagWelt.java
It's a Hello_World Program that answers in three different languages, based on input.
----
Java
> new Hello_World Program

- C/Hello_world_Sl1.c
----Display Hello World
C programming Language
> I Added A Program

- C#/DBUtil.cs
Its a Database Utility class which can be used for running Query and Reading Data from Database in C#
C#
> Created Database Utility class to run Query and read data from mySql

- PHP/ShortHelloWorld.php
It display "Hello World" in the shortest way
----
PHP
> Make it shorter

- C/hello_world_SL.c
> i printed hello world

- Python/Helloworld_malayalam.go
This program prints hello world in Malayalam.
----
Python
> Add Hello world in malayalam.

- Turkish/hello_world.txt
Hello, world translation in Turkish.
Turkish
> merhaba_dünya.txt

- C++/Hello_world_master.cpp
This program prints out hello world master 
----
C++
> Add hello world master.

- Java/HelloWorld/hello.java
> Check this and add

- Golang/hej_verden.go
Prints "halløj, verden", which is danish for "hello, world"
----
Go
> add danish hello world in go

- Python/EvenorOdd.py
The Program checks whether a number is even or odd.
----
Python 2.x
> My Contribution to the Hello World Repository 

- JS/ES6 Basics.js
Demonstrate the ES6 concepts such as:
1. Variables & Constants
2. Spread & Rest operators
3. Destructuring
4. Array map function
ES6 so babel transpiler is needed to convert into older JavaScript version
> Describe the basics of ES6

- Golang/Hello_world.go
Prints out 'Hello world' in GoLang
----
GoLang
> Add Hello World in Go

- Html/hello-world-sl.html
Simple hello-world html file with minor styling.
> Add my hello-world file

- VietName/HelloHanoi.java
- VietName/HelloworldVietnamJava.java
> Write Helloworld Vietnamese Java

- Html/Hello world heading.html
added header tag in line 8 and 10
----
> Added header tag

- Turing/Hello_World.t
Writes the program hello world in Turkish
Turing
> Hello_World.t

- C/xinchao.c
> Add xinchao to contributors list

- Swift/Merhaba_Dunya.swift
Swift "Hello, World!" in Turkish.
Prints hello world in Turkish
Swift
> Merhaba_Dunya.swift

- Python/burger.py
Create decorated burger
----
Python 3
> Add burger hello_world

- ModiScript/HelloIndia.chai
Prints 'Hello from India'
ModiScript
> Hello in ModiScript

- PHP/hello-world-tld-ro.php
----
It prints the url to access the helloworld website from .ro top level domain.
PHP
> Add hello world from .ro top level domain.

- C/Perfect number
this program decided if the number enterd is a perfect number or not.
it is written in C
>  Perfect number

- PHP/hello-world-tld-jp.php
----
It prints the url to access the helloworld website from .jp top level domain.
PHP
> Add hello world from .jp top level domain.

- Groovy/GeoLocationFinderScript.groovy
This groovy script will take IP address or Website address as a input from Console/IDE and will show
the Geo location of IP address/Website as output in console.   
----
Groovy
> Geo location finder

- C++/Hierholzer_Algorithm_for_directed_graph.cpp
Hierholzer’s Algorithm for directed graph
----
C++
> Hierholzer’s Algorithm for directed graph

- PHP/hello-world-implode.php
implode arraymap ello world
----
> php-hello-world--implode

- C/prims_minimum_spanning_tree.c
- Java/kruskals_minimum_spanning_tree_algorithm.java
Kruskal’s Minimum Spanning Tree Algorithm
----
Java
> Kruskal’s Minimum Spanning Tree Algorithm

- Legoscript/HelloWorld.java
- SystemVerilog/helloworld.sv
Printout Helloworld
----
Legoscript Language
> Legoscript apisak

- C/prims_minimum_spanning_tree.c
Prim's Algorithm for minimum spanning tree
----
It is written in C.
> Prim's Algorithm for minimum spanning tree

- SystemVerilog/helloworld.sv
Print out "HelloWorld"
----
SystemVerilog
> Added Helloworld in SystemVerilog language

- C ++/HELLO WORLD !!.CPP
----
---
( BUT IF WE ENTER (3,3) IT WILL PERFORM BETTER OTHERWISE THERE WILL BE SOME DIFFERENCES DUE TO SPACES I HAVE PROVIDED )
>  ADD HELLO WORLD git status to c++

- C++/topological_search_using_dfs/Makefile
- C++/topological_search_using_dfs/main.cpp
> Adds a topological search algorithm that uses DFS to search the graph

- VBA/HelloWorldVBA
Prints "Hello World!" to the immediate window in a VBA based application.
Visual Basic for Applications (VBA)
> Created VBA folder and code

- C++/heapsort.cpp
Program sorts a given array using HeapSort in nlog(n).
----
It is written in C++.
> HeapSort program in C++

- Html/Hello-Tamil/css/main.css
- Html/Hello-Tamil/index.html
Just a web page program to say Hello in the Tamil language.
----
HTML & CSS
> Hello in Tamil Language

- C++/Rod_cutting_problem.cpp
It's solution to the famous rod cutting problem.
----
C++
> Add solution to rod cutting problem

- Ook!/helloworld
- ~English/Helloworld
- ~English/~English.txt
> Hello world in Ook!

- C/arraysum.c
changes in the code so that the code works properly.....
----
C language
> add arraysum anmol20goyal

- Expressjs/helloworld.js
It picks a random number and if the number is one way then it prints Hello World plus the number of times this message has printed, else is prints Hello Hacktoberfest 2018 and the number of times this message printed
----
Javascript using ExpressJS
> express for hacktoberfest 2018

- C#/SawatdeeTH.cs
just print hello in Thai language
c#
> add c# class SawatdeeTH

- C Language/Hello_world+design.c
> I added Hellow world with design

- Python/ron_swanson_quote_generator.py
Python
----
Generate Ron Swanson Quotes
> ADD: Better inline comments

- Java/MohammedHelloWorld.java
> Added Hello world file to Java folder

- Java/Euler'sNumber.java
Outputs the Napier Constant (Euler's Number). Caculated using a recursive function.
Java.
> Euler's Number 

- Python/CodeBreaker.py
- Python/CodeBreakerUrPassword.py
- Python/CotaçãoDolar e Clima.py
- Python/Formula de Bhaskara.py
- Python/PyAutoGui.py
- Python/hello-world-kivy.py
Generate a random password and randomly tries to discover what was that password.
Let the user give a password and then randomly tries to discover what was that password.
It's an autoclicker program.
Simple bhaskara calculator.
With the city name informed by the user, it shows the weather in that place, and the Dollar converted to Real (Brazilian).
----
Python
> Python programs

- Python/PasswordGenerator.py
Create a random password according to your needs(size, 
character type) and save it if you want!
Python 3
> Add random password Generator

- Arduino/app.ino
> Hello World Arduino

- Python/shodanSearchActive.py
require api key and cli instalation.
Allows user to use shodans search engine to parse vulnerabilities 
python 3.7
> Shodan browsing application

- Python/ransomware.py
A simple ransoware
A simple ransomware
----
Python
> ransomware.py

- Rust/fizzbuzz.rs
It prints out the first 25 number/words in fizz buzz.
https://en.wikipedia.org/wiki/Fizz_buzz
This program is written in the rust programming language.
> Add FizzBuzz rust program

- Prolog-2/find_largest.pl
This is a prolog program could find the largest number given a list, even if the list is a nested list 
----
prolog
> add prolog

- Python/foscamdiscover.py
Detects FOSCAM IPCams on a network.
Similar to the official FOSCAM-distributed programs for Windows and OS X, this one runs wherever Python runs!
----
Python
> Add small program to detect FOSCAM IPCams on a network

- C#/OlaMundoBR.cs
Hello World in Portuguese Brazil!
It says Hello World in Portuguese
----
C#
> OlaMundoBR.cs

- JavaScript/advanced-string-to-function.js
Execute string operation (convert a string to a function)
----
Javascript
> Added convert string to a function

- Python/helloworld_french.py
Displaying a french hello world in console.
----
Python 3.6.3
> French Hello world (first contribution)

- Hello/hello
- Hello/hello.java
- Hello/helloWorld.java
its a hello world program
----
Java Language
> adding a new hello WORLD class in java

- python/Operaciones.py
A simple program to understand decorators in python
Python <3
> Add Operaciones.py

- PHP/Hello PHP/index.php
Added simple styling to hello world page
Program says Hello World!
----
PHP
> Updated index.php

- Python/Hello_name.py
> Adding Hello_name.py in Python

- C/cifradecesar.cpp
go ahead :)
it does the caesar ciphre. asks for a number to ciphre. 
----
C
> caesar ciphre

- C++/railcipher.cpp
The rail fence cipher is a form of transposition cipher.
User Input a plain-text message and a numeric key(height of the fence), cipher/de-cipher the given text using Rail Fence algorithm.
C++
For more Information, refer this link : [https://en.wikipedia.org/wiki/Rail_fence_cipher](https://en.wikipedia.org/wiki/Rail_fence_cipher)
> Rail Fence Cipher Algorthim

- Python/list_reverse.py
> Third pr to top-contributed repo

- Language/HellowWorld.dart
Adding hello wolrd dart
----
Dart lang
> dart hello wolrd

- JavaScript/functional_programming/sum.js
- JavaScript/functional_programming/sum_mult.js
sum example using funciontal programming paradigm
----
javascript
> add javascript functional programming example

- Html/hello_world_Hacktoberfest.html
> New Hello World in HTML

- c/virus.c
Quine written in C, it will output itself 3 times with a random numeric name.
----
C
> Added a quine written in C, it will output 3 same .c files

- Java/AddingBinary.java
> java - add binary

- Bash/triangle.sh
> adding triangle file

- Python/WebProjectCreator.py
create every file you need for a simple web project (HTML, CSS and JavaScript)
Python 3
> add webProjectCreator

- Python/Grayscale.py
transform an image to grayscale 
Python 3
> add converter to grayscale

- C#/HelloFromMilan.cs
Writes Hello World with async/await
----
CSharp
> Hello World from Milan

- Python/helloprogram.py
> Rename helloworld2.py to helloprogram.py

- C/Addition
> Code updated

- C++/ValidParenthesis.cpp
checks for the validity of the input brackets entered.
c++
> add code for checking valid parenthesis

- JavaScript/NaveenKoti-UserScoring.js
----Program calculates the user score on clicking texts
Written in JavaScript
> NaveenKoti-UserScoring.js

- C++/DynamicProgramming/Hosoya_triangle.cpp
The program is a solution to print Hosoya's triangle of height n using dynamic programming.
----
C++
> Add dynamic programming solution to print Hosoya's triangle of height n

- C++/DynamicProgramming/word_wrap.cpp
The program is a solution to the word wrap problem using dynamic programming.
----
C++
> Add dynamic programming solution for word wrap problem

- Hi_the_simplest_way/the_simplest_way_ever.py
Writes 'Hello world' using several operations
----
Written in Python
> Star Wars brain burst

- VB.NET/HelloWorld.vb
This is a program that prints "Hello, world!" in the console.
----
VB.NET
> Add VB.NET hello world application

- Python/Classing-Gender-SVM.py
- Python/Classing-Gender.py
Classing gender by height, weight, shoes_size using SVM Algorithm
----
Python
> Hichem python

- C++/DynamicProgramming/weighted_job_scheduling.cpp
The program is a solution to the weighted job scheduling using dynamic programming.
----
C++
> Add dynamic programming solution for weighted job scheduling problem

- Haxe/GameOfLife/Main.hx
- Haxe/GameOfLife/World.hx
It's a game of life implemented for the console
----
Haxe
> haxe game of life

- C/DynamicProgramming/coin_change_problem.c
The program is a solution to the coin change problem using dynamic programming.
----
C
> Add dynamic programming solution for coin change problem

- C++/DynamicProgramming/KnapSack_problem.cpp
The program is a solution to the 0-1 Knapsack problem using dynamic programming.
----
C++
> Add solution for 0-1 Knapsack problem in C++

- Cuneiform/helloworld-cuneiform.txt
- VueJS/WatchVueJs
It is a standard "Hello World" program.
----
It is written in Cuneiform programming language.
> add-cuneiform

- C ++/hello-hacktober.cpp
> Added hello-hacktober.cpp

- C++/hellow_world.cpp
> Created Hello World Program Using C++.

- C Language/calculate height using struc
create a menu driven program as follows
enter 1 to add 2 heights and display result
enter 2 to subtract 2 heights and display result
enter 3 to display both the heights in meters
enter 4 to exit
calculation of two heights
----
C
> calculate height using structure and switch in c

- Elixir/reverse_list.exs
Reverses a given input list.
Elixir
> Add reverse_list.exs

- Python/find_max_palindrome_substring.py
It'll return maximum length palindrome sub-string for given string.
----
Python
> Added Python code to find maximum length palindrome substring.

- C/factors.c
HELLO WORLD USING ONLY C IN ONE LINE.
---PRINT HELLO WORLD IN C
C
> update prime factors

- Python/flatten_container.py
This will flatten any kind of nested container objects.
----
Python
> Added Python code for flattening of container type object.

- Python/circular_prime.py
It'll check for circular prime.
----
Python
> Added Python code for circular prime check.

- C/H33L0_w0rld.c
HELLO WORLD USING ONLY C IN ONE LINE.
---PRINT HELLO WORLD IN C
C
> HELLO WORLD EXPLICITLY IN C

- ASPECTJ/Program
> Added Hello-world in ASPECTJ

- C/Factorial
> FACTORIAL FOR LARGE NUMBERS

- Html/helloworld-textcolor.html
> added helloworld-textcolor.html to Html

- C/Sorting an array in descending order
This program sorts the array in descending order.
It is written in C.
> Sorting an array in descending order

- WarayLang/hello-world.waray
It prints out _Hello, World!_.
----
[WarayLang](https://github.com/johnpaulada/waraylang)
> Added Hello World in WarayLang

- Python/lenofstr.py
---- The program consists of a function that returns length of a string, without using predefined len() function
---- Python
> Length of a string function

- Python/max_length_between_two_node_n_ry_tree.py
It find the maximum length of path between two nodes and these two nodes also in n-ry tree.
----
Python
> Add program for Diameter of n-ry tree

- C Language/c program to implement ceaser cipher algorithm.c
-it encrypts the given message using ceaser cipher algorithm---
c language
> c program to impplement 

- C ++/Hello_world_by_Shashwat-Garg.cpp
Program prints Hello World with my Github handle (Shashwat-Garg).
----
Programming Language used is C++.
> Hello World with Github handle in C++

- Java/HTTPServer/SimpleHTTPServer.java
Create a simple HTTP Server
----
JAVA
> creating a simple HTTP server

- C++/rev_linkedlist_using_recursion.cpp
The program is reversing a [linked list](https://en.wikipedia.org/wiki/Linked_list)  using [recursion](https://en.wikipedia.org/wiki/Recursion_(computer_science)).
Programming language used - C++
> C++ Program for reversing the linked list using recursion

- C/vigenere.c
learn what is Vigenere cipher and how to find length of key given cipher text
C
> Add: Vigenere cipher utilities

- Python/Reverse of a number
This program reverses the given number.
It is written in python.
> Reverse of a number

- Java/BinarySearch2DArray.java
Performs a binary search on a 2D array in O(log n) time complexity.
----
Java
> Fast binary seach on 2D array

- Indonesia/README.md
- Indonesia/hello_world_in_indonesia.py
- Indonesia/hello_world_in_javanese.py
- Indonesia/hello_world_in_sundanese.py
Indonesia have more than [700+ languages](https://en.wikipedia.org/wiki/Languages_of_Indonesia). this PR is intended to make it easier to organize these languages in one directory.
----
Currently in `python` (may will add more on another language)
> Hello world in most indonesia languages

- C ++/Hello Earth.cpp
Basic C++ Hello Earth code
----
C++
> Create Hello Earth.cpp

- Html/HelloWorldFromParaguay.html
- Html/HelloWorldInParaguay.html
> Hello world paraguay

- Docker/build_hello_world.dockerfile
Prints hello when building 
bash is docker
> added dockerfile that prints hello world when building

- Hello world python/ggasconn-helloWorld.py
Yet another Hello World in Python!
----
Python
> Added hello world in Python

- Java/BINARY TO DECIMAL
converts binary to decimal !
----
JAVa
> Create BINARY TO DECIMAL

- Java/decimal to binary
converts decimal to binary !
----
JAVA
> Create decimal to binary

- Kotlin/hello-world-delegation.kt
> Added hello world with delegation pattern.

- LOLCODE/fib.lol
Prints Fibonacci sequence up to the _nth_ number.
LOLCODE
> Add LOLCODE fib

- HAL-S/hello-world.hal
> Add Hello World in HAL-S language

- React-Native/App-Hello-World.js
Hello World in React Native
Hello World in React Native
----
React-Native
> App-Hello-World.js

- JavaScript/setInterval.js
Prints 'Hello World' every second
----
Javascript
> Javascript setInterval printing hello world every second

- C#/PalindromeRecursive.cs
It tests Palindromes recursively
----
C#
> Palindromes lmao

- C/swap.c
made the program of swap without using the third variable...
----
C language....
> add swap anmol20goyal

- Python/factorial_calc.py
---- Calculates factorial of a number input by the user
---- Python 3
> Add program to calculate fatorial of a number

- Python/wholenumtobit.py
---The program takes a whole number as an input from the user and converts it to binary form
---Python
> Add new program to convert whole number to binary form

- C++/mandragora_forest.cpp
Solves the "Mandragora Forest" programming challenge from HackerRank (https://www.hackerrank.com/challenges/mandragora/problem).
----
Written in C++.
> add "Mandragora Forest" problem from HackerRank

- Perl/hello.pl
- Perl/review_perl.sh
- Perl/t/hello.t
----
The `./hello.pl` program prints 'Hello World' to the console, and logs every use in `$HOME/log/`
The `./review_perl.sh` script does `perl -c`, `perlcritic` on 5 levels, and `prove` and reports to TeamCity.
Perl5
- Passes perlcritic --brutal
- Has 3 test-cases. #4623
> ✨ ❣️ Hacktoberfest: a better perl Hello World.

- Java/Binary_Search.java
Binary Search Program in java
Does binary search (written in java) :)
----
Java
> Binary Search Program in java

- C/fabonacci.c
> Used for loop

- NodeJS/Nodejs.js
> need node modules to run

- CSharp/HelloWorld/Program.cs
> I added hello world c# file

- katrinasilver/hello-world.liquid
Says hello world
----
in liquid 😸
> Add hello world in liquid 😸

- Julia/Matrix Hello World.jl
First Julia Program
Basic Hello World Program. Banner style printing using matrix.
Julia
> Added a Matrix Hello World Greeting

- Java/DataStructure/Arrays/StringOfNBit
Program to generate all strings of N bit
----
JAVA
> adding string of N Bit program

- C++/doubly_linked_list.cpp
The program is creating a [doubly linked list] (https://en.wikipedia.org/wiki/Doubly_linked_list) and is printing the list in forward and reverse directions.
Programming language used is C++.
> C++ program for doubly linked list

- C/abhishek.c
- Java/successive_mult.java
Factorial
#166 Hacktoberfest contribution
C
> added my factorial program

- Python/udp-flood.py
Python Pentest Tool
Pentest Tool
----
Python
> udp-flood.py

- JavaScript/post-message/iframe.html
- JavaScript/post-message/index.html
Uses post message to say hello world
----
javascript and html
> Javascript postmessage saying hello world from an iframe

- Python/image_scrape.py
Minimal image scraper using selenium, defaulted to the Chrome driver
> Adding image scraper

- JavaScript/hello-arkjel.js
Printing "Hello" with some name
----
JavaScript
> Arkjel commit for Hello World

- JavaScript/quiz.js
Consists of a quiz on founders of different programming languages using HTML, CSS and Javascript.
It has a quiz consisting of 5 questions on founders of different programming languages. It gives you option to select answers and shows the results right away.
----
Javascript, HTML and CSS.
> Created quiz.js
