IntelAISociety/Hello-world

Cplusplus/hello.cpp
=> Created hello world in cplusplus

Shell Script/helloworld.sh
=> shell script

PHP/HelloWorld.php
=> Create HelloWorld in PHP

R/HelloWorld.R
=> Create HelloWorld in R

Lua/HelloWorld.lua
=> Create HelloWorld in lua

C++/helloWorld.cpp
=> Hello World in C++

R/Hello-in-R.r
Code For R language added.
#Lovefordatascience #Hacktoberfest
=> Added R code as well

Java/HelloWorld.java
=> HelloWorld.java

Dart/HelloWorld.dart
=> HelloWorld.dart

Rust/hello_world.rs
=> added Hello World - Rust

html/HelloWorld.html
=> HTML implementation

.idea/Hello-world.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, .idea/workspace.xml, Javascript/index2.html, Javascript/myfirstjs.js
my hello world with javascript
=> added my hello world with javascript

Elm/hello.elm
=> Elm Language

helloworld.f
=> Written in FORTRAN

Java/myGithubUsername.java
Java program to print my Github Username/Handle
=> My Github Handle!

C++/hello_world.cpp
=> Added hello World

README.md
=> Polished the README.md file with various grammar changes

VBScript/HelloWorld.vbs
Added a short program to show pop up box displaying Hello World in VBScript.
=> Created Hello World in VBScript

Javascript/server.js
=> Creates server.js

C/RenFraser.c
=> Added RenFraser

Typescript/hello-world.ts
=> first time PR

C/amankumarsoni.cpp, Java/amanhello.java
=> contributed successfully

Python/rsa.py
A python implementation of RSA
=> added Python RSA implementation

ACPI/HelloWorld.aml
The *.aml file stores source code in ACPI machine language.
=> The machine language used to configuration a computer power management

Python/Hello-World.py
Removed the space between "world" and "!" and capitalized the letter "w"
=> Updated Hello-World.py

CSS/index.html
=> CSS Hello World

innovative
!! printing hello world without semicolon !!
=> innovative

Javascript/hercegtomas.js
As HelloWorld is already implemented I added a program that prints my GitHub handle
=> Add hercegtomas

Html/index.html
<!doctype html>
<html>
<head>
<title>Hello World</title>
</head>
<body>
<p><strong>My First WebPage</strong></p>
</body>
</html>
=> index.html

Solidity/hello_world.sol
hello world using solidity language,
what is solidity?
solidity is the programming language to make a smartcontract in ethereum blockchain technology
for more details : https://solidity.readthedocs.io/en/v0.4.25/
=> add solidity helloworld

Python/Hello-World.py
this pull request will contribute to my hacktoberfest pull requests
=> changed Hello-world.py

Html/simpleHelloWorld.html
Created a simple Hello World program
=> Create Hello World Program

Java/Hello.java
Added Hello world program in java
=> Added HelloWorld.java program

C/meghana_hello_world.c
=> add helloworld.c

Html/hacktober.html
hello world page with bootstrap
=> hello. im join in hacktoberfest 2018

Elixir/HelloWorld.ex
=> Added Elixir

C++/Sum in array.cpp
I have performed addition and summing in a single loop which improves the run time of program and also improved indentation.
Thanks!
=> Update Sum in array.cpp

Javascript/helloworld.js, Javascript/index3.html
printed hello world without any html.
=> used document.write() to print hello world

Python/HiWorld.py
=> Add Hi World in Python

PHP/phpinfo.php
for checking php info on server
=> added php-info file

Java/abstract.java
i add java abstract class to repo
=> add java abstract class

typescript/hello.ts
i add typescript hello with reference
=> add typescript hello with reference

Java/linkedList.java
this is an example for java Linked List and how it is used
=> java linkedlist example

Java/linkedList.java, Java/staticInitializer.java
this is java static initializer and i have given a example to how we can use it in programme
=> Java static initializer

Lua/homing_missile.lua
Just a silly script from a silly game I was trying to make moddable
=> Added a lua script from a game I made.

PHP/Add.php
To calculate addition/sum of two numbers
=> Created Add.php

PHP/Diff.php
To calculate the difference between two numbers
=> Created Diff.php

C++/strange_sumB.cpp
Professor gave this function as a runtime analysis question. Enjoy it as I have.
=> Added infinite recursive program from CS2

C++/BuyingATVSet.cpp
=> First PR in C++

MATLAB/cmpsimp.m
Added A composite simpson program
=> Added cmpsimp.m to matlab directory

awk/hello_world.awk
=> Add awk hello world

Javascript/hello_world/index.html, Javascript/hello_world/index.js
I add Hello world folder that contains hello world in javascript.
=> Insert Hello world in JavaScript - Praveen

Html/Hello Big Font.html
=> Add HTML Big

D/HelloWorld.d
Added D language Hello World Program
=> Added D Program

Java/BinarySearch.java
Added Binary Search Algorithm in java folder
=> Binary Search Added

Python/Benches.py
=> Code Push 2

Html/helloworldTaiwan.html
Happy coding & have a great day!~~
=> Hello From Taiwan

Java/PresentedBy.java
Script to display Hacktoberfest main company sponsors in random order
=> Add PresentedBy.java

Python/LinkedList.py
Linked list data structure implementation... with cute ASCII art (hand-typed).
=> Add LinkedList.py

Python/Stack
The stack data structure represented by a python class, explained by a robot...
=> Add Stack.py

Bash/example.sh, Golang/httpexample.go, Python/funny_Hello.py
Created a python example showing simple join, string add, string multiplication examples
=> Python simple join, string add, string multiplication examples

Python/Counting the Number words.py
added comments and fixed a bug
=> Update Counting the Number words.py

C/binary_sort.c
Add binary sort  C example 
----
C
=> add binary sort example

Haxe/HelloWorld.hx
visual studio code to weiten.
and run command '$ haxe -main HelloWorld --interp' to display.
----
Introduction basic use programming language is haxe.
=> add new programming language to preview hellow-world

Basic/Hello World
Just Says, Hello World
----
Basic Language
=> Added hello world in basic

PHP/HelloWorld_IT, PHP/time_now
Just says "Hello World!" in Italian :)
----
php
=> Hello World in Italian - php

GolfScript/helloworld.gs
Prints "Hello world!"
----
GolfScript
=> Golfscript Hello world

C++/Shubham code.cpp
I also added a file which outputs Hello world
This proggreme prints a message Hello world on the execution./
----
Thiss is written in c++
=> Shubham's code

Html/helloworld.html
Just print 'Hello world'
----
HTML
=> simple hello world

Python/greatest_common_divisor.py
It will find GCD of two numbers.
----
Python
=> add gcd program in python

Java/QuickFindUF.java, Java/QuickUnionUF.java
=> QuickUnion added

C#/HelloWorldC#.cs
=> add hello world in C#

wml/index.wml
Shows "Hello world" and some info about WML language.
----
WML
=> WML hello world

VueJS/index.html, VueJS/index.js
print "Hello World" in vuejs
----
It's written in latest VueJS Version.
=> Added vuejs hello world

C/Chocolate Distribution Problem
A programming exercise problem found in geeksforgeeks
Given an array A[] of N integers where each value represents number of chocolates in a packet. Each packet can have variable number of chocolates. There are m students, the task is to distribute chocolate packets such that :
1. Each student gets one packet.
2. The difference between the number of chocolates given to the students in packet with maximum chocolates and packet with minimum chocolates is minimum.
It is written in C language.
=> Create Chocolate Distribution Problem

C++/SegTree.cpp
It is a program for segment tree 
----
It is written in C++
=> Add segment tree code in c++

Ook/helloWorld.txt
=> added hello world in ook!

PHP/helloworld.php, Perl/helloworld.pl
This Hello World is written in PHP
=> Created helloworld.php

HelloWorldGraphics.cpp
It shows hello world in C++ using the graphics.h library! Multithreaded and cool!
----
C++ and graphics.h
=> Added a nice animation!

Python/bracket_finder.py
It will Find Brackets in Given String.
----
Python
=> Add Bracket Finder Program in Python

Java/HelloWorldSk.java
=> Hello world

Python/sum_prime.py
Sum of All the Prime Numbers.
----
Python
=> Add Sum of Prime Numbers Program

PHP/OOP/HelloWorldOOP.php, PHP/OOP/index.php
=> Hello World in PHP7 OOP

Python/average_grades_finder.py
This Program find Average grades as per given format.
----
python
=> Add Program to Find Average Grades

Python/add_mult_polynomial.py
Add and Multiply two Polynomials.
----
Python
=> Add program to Multiply and Add two polynomials

Python/number_guessing.py
It is a game in which the computer decides a number and the user has to guess it iin minimum number of tries. Hints are provided by the computer to help the user. 
Python
=> added number guessing game in python

Python/floyd_warshall.py
It is an implementation of Floyd Warshall Algorithm for finding shortest path between all nodes of a graph
----
python
=> floyd_warshal_python

Python/decimal_to_base.py
A function to convert a decimal number (base10) to other bases (2-16)
----
Python
=> add decimal_to_base python

Swift/hello.swift
* UIKit and Foundation imports are unnecessary
* Swift can almost always infer the type to be used, assigning "Hello, World!" to `message` makes it String
* print has a signature of `func print(_ items: Any..., separator: String = default, terminator: String = default)` so there's no need to supply value for terminator parameter
* Removed invalid syntax fileManager call
Prints "Hello, World!" in Swift
----
In terminal, type:
`swift hello.swift`
Swift
=> Removed unnecessary codes

Gradle/build.gradle
Hello world implemented in gradle
----
Gradle, a build language based on Groovy
=> Added hello world in gradle

Java/minASCIIdelSum.java
Minimum ASCII deletion sum - Dynamic Programming Problem.
----
Java
=> Added min ASCII del sum DP problem

Java/DefinitelyNotAHelloWorld.java
Prints Hello Hacktoberfest 2018!
----
Java
Happy Hacktoberfest 2018!!
=> Added a hello Hacktoberfest

Python/Tree.py
Converts infix expression to prefix and postfix
----
Program is written in Python
=> Added Tree

Python/dijkstra's_algorithm.py
Algorithm to find the shortest path between nodes of a graph.
----
python
=> added dijkstra's aglo

AmazonAlexa/References.txt, AmazonAlexa/index.js, AmazonAlexa/package.json
Lambda code for saying Hello World!
----
Written in Node.js, but with serverless Lambda and Alexa SDK in the works too
=> adding simple tutorial for getting your Amazon Alexa to say Hello World

C++/merge_sort(top-down-recursvive).cpp
=> Added code of Merge-Sort in C++.

Java/FibonacciStream.java
This class showcases how we can use Java stream api to print fibonacci numbers
----
Java
=> Added fiboanacci using java stream api

Javascript/jperez.js
Prints out link to my GitHub
----
JavaScript
=> Add Coffeescript

PureBasic/helloworld.pb
Prints "Hello World!" to the console.
----
PureBasic
=> Added Hello World in PureBasic

C/hellodunia.c, PHP/hellophpid.php, SQL/HelloWorld.SQL
create hello world in php 
hello world in indonesian version
=> added hello world 

Python/hello_world_pt-br.py
It prints "Hello world!" in pt-BR, "Ola mundo!", using lambdas and bit shifting.
----
Python
=> Added "Hello world!" in pt-BR, Python

C++/convexHull
Calculates de Convex Hull of a given set of points
----
In C++
=> Convext hull code

C++/crossWord
This program solves a crossword using backtracking.
----
C++
=> crossWord solver

C++/helloword_id.cpp, C++/helloword_in_id.cpp
=> hello world_id.cpp

C++/hello world.cpp
#include<iostream>
using namespace std;
class Message
{
public:
void display() {
cout << "Hello World\n";
}
};
int main()
{
Message c;    
c.display(); 
return 0;
}
----
I have written a program in c++ which will print hello world in the output
=> Create hello world.cpp

C#/helloworld_id.cs, C#/helloworld_in_id.cs
=> hello dunia in c#

Lopa.java
=> Added hello world java file

C++/sieve.cpp
Finds primes up to MAX_SIZE using the sieve of eratosthenes
----
C++
=> C++: Add program to find primes using sieve of eratosthenes

Java/LeapYear.java
- Fixed logical bug for leap year
----
Java
=> Fixed logical bug in LeapYear

R/HelloWorldPrintPaste.r
=> add a parse methode

Python/shell_sort.py
Closes http://github.com/Hacktoberfest-2018/Hello-world/issues/480
Sorts an array using shell Sort algorithm
python
=> add shell_sort.py: Added Shell Sort Algorithm

Java/Demo.java
=> Added Hello World in Java

Html/helloworld.html, PHP/helloworld.php
Hello World program!
* Written in clojure.
* New version with instructions on how to run.
=> Added hello world clojure ver2

Shell Script/palindrome.sh
Finds the Palindrome of the Given Number
----
Shell Script
=> Palindrome using shell script

Python/rockpaperscissors.py
A simple rock paper scissors game
----
Python 3.6
=> A simple python rock paper scissor game

NodeJs/zmq.js
The program subscribes to a ZeroMQ server and prints all messages.
----
Node.JS
=> add zeromq program

Java/LongestIncreasingSubsequence.java
---- it calculates the length of longest increasing subsequence using dynamic programming
java
#1
=> Adding DP algorithm for Longest Increasing Subsequence in java

C++/factorial.cpp
----Calculate factorial of large number using dynamic programming
c++
=> added factorial program using dp

C++/bfs.cpp, C++/factorial.cpp
----calculate bfs of graph
c++
=> Add bfs graph

C++/dfs.cpp
=> added dfs of graphs

C++/dfs.cpp, C++/islands.cpp
----\solution to famous problem number of islands
c++
=> Calcuate number of islands

SageMath/helloworld.sage
Prints Hello World
----
Sage Math
=> Added SageMath

C/cpu_waster.c
Added an example of bad memory management.
Mallocs a continuously increasing number in an infinite loop. 
Continuously eats up your memory as you are never freeing it. 
----
Written in C.
=> Added cpu_waster.c

Python/nc-responder.py
Use this in order to automate netcat connection, responding, receiving and extracting data.
Helpful during CTFs.
----
Python
=> added nc-responder file

Python/validar_cpf.py
This program validates the CPF, unique set of 11 numbers used to identify a person in Brasil. This script validate it
Python3 compatibility.
----
=> Add Validador de CPF

Html/footer.html
=> footer.html

Html/dialog.html
=> dialog.html

Vim/useful-vimrc-file.vim
=> added useful vimrc file

Shell Script/hello_arg.sh
If no command-line argument given, echoes program usage.
If a command-line argument given, echoes 'Hello <arg> !'
----
bash shell script
=> Shell script - hello arg

Javascript/receive_udp.js
recieve data via udp protocol
----
Javascript
=> add udp javascript

Java/MagicSquare.java
Basic magic square is written by Java, support only square with nxn where n % 2 = 1 only (odd number).
Java
=> Add Magic Square Java

Python/email_regex.py
to find all the email-addresses inside large texts using regular expressions and display them individually.
----
python
=> email_regex

Java/insertion_sort.java
The program does insertion sort.
The program is written in java.
=> created insertion_sort.java

C++/tic.cpp
Programme is a game Tic Tac Toe
----
It is written in c++
=> Game - Tic Tac Toe

Angular/src/app/app.component.html, Angular/src/app/app.component.ts, Angular/src/app/app.module.ts
Example how to add reactive form and submit form Value.
----
Angular 5+
=> Added Reactive Form

Julia/hello_world.jl
=> hello world in julia

Ruby/prime-number.rb
The program checks whether the user input number is prime or not.
----
Ruby
=> Added a ruby code to check if the number is prime.

Python/Zombie game.py
Its a Post Apocalyptic zombie survival game. 
Python
=> zombie Game

Javascript/namaste.html
hello in Hindi!!
prints "namaste from india" when clicked in the button
----
html,js,css
=> added namaste.html

Assembly/helloworld_arm.S
It prints "Hello, World!"
----
Assembly language of ARM (eABI) architecture. There was a program written in assembly language of x86, so I tried another one.
=> Added another assembly program

Python/longest_substring.py
The program prints the longest substring of a string s in which the letters occur in alphabetical order. For example, 
if s = 'azcbobobegghakl', then the program would print: Longest substring in alphabetical order is: beggh
----
Python
=> Added python program to find longest substring

Python/GetDataFromRssUrl.py
This script can be used to get data from RSS feed url
----
Python
=> added Get RSS data from URL

Python/hello-world-from-python.py
Prints Hello World using Python integrated Easter Egg
----
Python
=> Python Hello World integrated Easter Egg

Java/Hello.java
=> Change end of sentence

Python/death_bot.py
This is a program which displays small window and says that 'I will click you' on clicking the button
Uses tkinter in Python to display 2 buttons in a window which display a message box when clicked
----
Python
=> Death bot program in python

CSS/Untitled.css
=> Css file added

C++/longest_increasing_subsequence
Find the length of the Longest Increasing Subsequence in an array using DP
----
C++
#1
=> adding Longest Increasing Subsequence code in C++

Python/bellman_ford_algorithm.py
Implementation of the Bellman-Ford algorithm.
It is written in python.
=> Bellman_ford_algorithm

Html/Introduction.html
=> ADDED "DOCTYPE HTML " DECLARATION TO ARTICLE

Html/Form
=> ADDED "DOCTYPE HTML" DECLARATION TO ARTICLE

Html/html-css.html
=> ADDED "DOCTYPE HTML"  AND </html> DECLARATIONS TO ARTICLE

C/array.c
=> decreased the length of the code,removed unnecessary variables

Html/Hello Big Font.html
=> ADDED "<!DOCTYPE html>" DECLARATION

C++/HelloWorld
- This file is not contain format .cpp;
- In this file code is wrong.
- HelloWorld.cpp already exist (with correctly code).
=> Delete unnecessary file HelloWorld

C/HelloWorld.cpp
=> The program was not returning any value, so added return.

CSS/hello-world.css
Displays hello world using CSS, without a dependency on HTML.
=> Hello world in CSS without HTML

TorqueScript/hello-world.cs
Prints out hello world in TorqueScript, a scripting language used by the Torque game engines.
=> Hello world in TorqueScript

Html/Hello Big Font.html
=> ADDED "<!DOCTYPE html>" DECLARATION.

Html/footer.html
=> ADDED ""<!DOCTYPE html>" DECLARATION.

Html/HelloWorld_marquee.html
=> ADDED ""DOCTYPE HTML" DECLARATION TO ARTICLE

Javascript/hi.js
print hi everyone in console
----
javascript
=> Created hi.js in javascript

Html/Helloworldjm.html
=> ADDED PROPER TAGS TO ARTICLE

Html/manav.html
=> ADDED "DOCTYPE HTML "DECLARATION

GNU Make/makefile
It prints "HACKTOBER 2018"
----
GNU Make
=> Added GNU Make

CUDA/HelloWorld.cu
Hello World in CUDA  -Parallel Programming version!
----
CUDA - https://es.wikipedia.org/wiki/CUDA
=> Hello World in CUDA 🚀

Python/swapping_variable_values.py
Swap the values of two variables.
----
Python
=> swap variables

C/arrayeven.c
=> change in for loop

C/matrixaddtwo.c
=> manipulated variables and for loops

C/positivecheck.c
=> change in if else statement

Python/hello-folks.py
Prints hello in python
Prints Hello, Folks
----
Python
=> Rename hello.py to hello-folks.py

C/weekdayswitch.c
=> change in switch statement

Dart/async_example.dart
A simple program that displays the asynchronous nature of the programming language, basic syntax, and functionality.
Dart (https://www.dartlang.org)
As per instructions in #1
=> Hello asynchronous Dart

Expressjs/index.js
Express JS Hello World Example. Runs a mini web server and sends "Hello, World!" text when visited the URL
----
node.js (JavaScript)
=> added express js

CoffeeScript/hello_world.coffee, Javascript/hello_world.js
It outputs `hello, world` to stdout.
----
CoffeeScript, a language that compiles to JavaScript.
=> create hello world program in coffeescript and javascript

Python/tower of hanoi.py
It is a python algorithm to implement tower of hanoi.
----
Python
=> Added tower of hanoi python code

Python/Hello-World.py
Minor edits
prints hello world
python
=> Hello-World.py

C++/searchinrotatedarray.cpp
=> add searchinrotatedarray.cpp

Python/in_bestseller.py, com_bestseller.py
=> Python Scraper

Python/platform-info.py
This simple program shows information about your platform
----
Python
=> Simple program to show information about your platform (Python)

C++/decimalToRoman.cpp
Converts Decimal number to Roman 
C++
=> Converts Decimal number to Roman 

Javascript/server.js
=> Fixes syntax error

Golang/helloword-no-import.go
=> Add Hello World of Golang without vendor

C/hello .c, Python/Hola Mundo
=> Update Hola Mundo

HolyC/HelloWorld.holyc
Prints out "Hello World"
HolyC, a language invented by Terry A. Davis
=> add Hello World in holyC

C++/fibonacci.cpp
This is a "fibonacci sequence" program, letting you choosing the term you want to calculate.
----
The program is written in C++ (should work without problem in C++11 and >)
=> adding a fibonacci algorithm letting you choosing the term you want

C++/insertionsort.cpp
=> Adding Insertion Sort in C++

Shell Script/numberGuessing.sh
lets the user guess a number.
----
Shell Scripting
=> added numberGuessing game

Python/fastestprime.py
Finds prime numbers to a certain value using sieves
----
Python
=> Finds prime numbers to a certain value using sieves

C++/LL.cpp
Linked List Implementation
----
C++
=> Linked List Implementation

Python/Alphabet_Rangoli.py
The program is an exercise from [Hackerrank](https://www.hackerrank.com/challenges/alphabet-rangoli/problem
) 
You write an size in the shell and the program returns the alphabet-rangoli , like that:
3
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----
----
The program is written in Python
=> Add Alphabet_Rangoli.py

CheckKthBit.java, Java/KadanesAlgorithm.java, Python/bubble_sort.py
=> Check kth bit

C++/Best_Buying_and_Selling_days_for _stock
Finds the buy-sell schedule for maximum profit.
----
c++
=> Program to find best buying and selling days for given stock trend

C++/Queue LL.cpp, C++/Stacks.cpp
Stacks and Queues using Linked List
----
C++
=> Stacks and Queues using Linked List

Angular/src/app/app.module.ts, Angular/src/app/post.component.html, Angular/src/app/post.component.ts
Example of how to fetch data from server using GET request.
----
Angular 5+
=> Http example

Python/LeapYear.py
Python program to check whether the input year(entered by user) is leap year or not.
----
n this program, user is asked to enter a year. Program checks whether the entered year is leap year or not. Programme is written in python language
=> new leap year program added

Python/hello.py
=> hello python

C++/Bounded Buffer.cpp, C++/Circular Queue.cpp
=> Circular Queue

C/Segmentation.c
Segmentation working in C
----
C
=> Segmentation Working in C

Python/Primalitytest.py
This program simply checks whether the number is prime or not in O(sqrt(n))
Python3.6
=> a simple efficient program to test the primality of the number

Javascript/hactochandu.js
this is hello world program
It prints hello world in console
----
JavaScript
=> Create hactochandu.js file

Javascript/hello_world/index.html
=> Update JavaScript hello-world

C++/Factorial.cpp
if the user inputs 0 the function will return 1 as the output
----
=> Added test case of n equals 0

Rust/helloWorld.rs
=> Adding hello world in Rust

C++/Armstrong.cpp
Reduction in space used to write the code by removing unnecessary brackets. It makes it easier for the user to read it,
----
=> Shortened the Armstrong code

C/pallindraome.c
checks whether the given string ins pallindrome or not
----
C language
=> added pallindrome.c

Java/HelloWorldWithASmile.java
It prints hello world along with a smile
Java
=> Add HelloWorldWithASmile

C/list.c, C/rev.c
reverses the given string
----
C language
=> Added Rev.c

Bash/hello.sh
Like that greeting to world.
----
=> Changed Text

C/double.c, C/spiceBS.c
Doubly linked list implementation and applications
----
C language
=> added Double.c

Java/HelloWorld/src/HelloWorld.java
=> remake for take user inputs

C++/LL.cpp, C++/SelectionSort.cpp
Making linkedlist class a friend class of node class
----
=> Changing privacy settings

Java/quicksort.java
=> quicksort program

C++/Hi, world!
=> Create Hi, world!

Inspec/hello.txt, Inspec/hello_spec.rb
Inspec hello world example
----
inspec (ruby)
=> Inspec hello world

Swift/hello alex azarov! <3
It says hi to my friend!
Swift
=> Create hello alex azarov! <3

Kotlin/HelloWorld.kt
Print: "Hello, World!"
----
Kotlin
=> added another hello-world

Assembly/helloworld_fasm.asm
The program prints "Hello, World!" using DOS 21h interrupt.
----
It's written in FASM syntax assembly and compiles under the DOS using flat assembler compiler from flatassembler.net.
=> Hello world source code for DOS in FASM assembly.

Golang/helloname.go
Prints hello + a name passed in args.
Golang.
=> Add helloname.go

Basic/Hello World, Hypercard/HelloWorld
Add ability for BASIC to actually RUN
Add REM remark statements
Add Hypercard helloworld
BASIC - Prints Hello world and rings bell on TTY
Hypercard - Prints hello world
----
BASIC
Hypercard
=> Refactor BASIC and Add Hypercard

Golang/HelloWorld.go, Golang/arrays.go, Golang/channels.go, Golang/closures.go, Golang/errors.go, Golang/for.go, Golang/if-else.go, Golang/sort-by-func.go, Golang/sorting.go, Golang/switch.go, Golang/timeouts.go, Golang/timers.go, Golang/variables.go
A few code snippets which cover basic blocks of programming
----
Go
=> Add a few function in Go Language

J/HelloWorld.ijs, SQL/HelloWorldSybase.sql
Prints Hello World in J Software
=> Add HelloWorld in J

C++/2018201023_5.cpp
Running Median
Computes the running median of numbers given as input.
C++
=> Running Median CPP

Bash/list-banned-ips.sh
Lists all rejected IP entries in iptables.
----
Bash
=> Added Bash/list-banned-ips.sh script.

Python/avg-response-time.py
Return average response time of URL.
----
Python 2
=> Added Python/avg-response-time.py script.

Bash/hex
Change string to hexadecimal
----
Linux bash(Ubuntu)
=> Hello World in Hexadecimal

C++/KMP_Pattern_Matching_algo.cpp
It's standard KMP pattern matching Algorithm.
----
c++
=> added KMP pattern matching program in c++

C/Linked_List.c
The program is a simple linked list with basic functions to insert, traverse or delete items.
----
C
=> Add Linked List with functions

C/Guess_My_Number.c
It is a mini game which lets users guess the number the computer is "thinking" about
----
C
=> Add guess my number mini game

Assembly/helloworld_nasm.asm
Prints "Hello, World!\n" and cleanly exits
----
NASM x64 assembly (Unix)
=> Added Hello World in NASM

C/uefi_helloworld.c
This is a UEFI boot loader using EDK2
----
C Language!
=> LETS PARTY!

Java/HelloFromTrumvekhuya.java
Print out my hello to open source
----
Java
=> Hello From TVK

Javascript/bitwise-helloworld.js
This PR includes a different approach to log `Hello World!` in JavaScript.
The following features in JavaScript are not allowed: `Strings, numbers, regular expressions, functions named "Hello", "World", "HelloWorld" or anything similar, and object keys named "Hello", "World", "HelloWorld" or anything similar`.
This script uses bitwise operation to form ASCII values of the string `Hello World!`, then log to the console using `String.fromCharCode()`.
=> Add new hello world for JavaScript

C++/cplusplushelloworld.cpp, C/chelloworld.c, Java/JavaHelloWorld.java, Python/pythonHelloWorld.py, R/rhelloworld.r
=> Adding Hello World Programs in 5 Languages

Ruby/hello_world.rb
printed statement of Hello World
Print into the terminal the statement: "Hello World!"
----
Ruby
=> Created hello_world for Ruby

C++/hello_world1.cpp
Hello World is printed with the help of both if and else executing at the same time.
program prints hello world by the help of both if and else statement running on machine at the same time.
----
it is written in c++
=> both if and else part execute

Python/get_web_title.py
- Read title from website behind the given url
----
- Python
=> Add tool to get title from url provided (Python)

C++/factorial.cpp, C++/hello world.cpp, Chef/hello.txt, Golang/helloworld.go, Html/helloworld.html, Python/helloworld.py, Python/rockpaperscissors.py, Shakespeare/hello.spl
Prints "Hello, world"
----
Shakespeare
=> Added Shakespeare

C/akshatkaush/helloworld.c
I am born as a normie.
Print classic `hello world`
----
C
=> Generic Hello World Preference

Java/schbebsi.java, Python/schbebsi.py
prints "Hello Schbebsi"
----
Java
=> Added schbebsi.java

Python/helloworld-pt-br-rn.py
Talks Hello World in Brazilian Norteriograndense
----
Python
=> Hello World no RN-BRA

Javascript/bluetreebranch.js
=> Added bluetreebranch.js to /Javascript

C++/ParallelBinarySearch.cpp
----  This program is useful for optimizing the binary search algorithm for large number of queries.
----  It is written in cpp.
=> Added Code for parallel binary search

C++/helloworldd.cpp
=> first commit

Python/jyri_is_great.py
My version of Hello World :EE
----
Byton
=> Jyri is greatest!

Scala/HelloYou.scala
Prints Hello, You! if no args are given. Prints Hello, Name!, if name is given as first argument.
Scala
=> Added Hello You in Scala

Rexx/pohyi-k.rexx
=> added hello world in rexx

C++/GCD2.cpp
Added use of GCD
GCD and it's implementation
----
C++
=> Added GCD example

Html/hello-world romanian.html
I added the HELLO WORLD title in romanian
in romanian
=> Hello world written in romanian

Pike/Hello World
The program prints Hello World in Pike
=> Create Hello World

C++/linear equation in matrix form
it represents a given linear equation in form of a matrix.
----
it is written in c++.
=> Create linear equation in matrix form

C++/helloWorld.cpp
=> modified hello world

GCD.c
Fix #33 Fix #166
Calculate GCD
----
C
Fix #33 Fix #166
=> Added GCD example in C

Hello World, Hello world
The program prints Hello world.
----
Program is written in C language
=>  Hello world

Python/Designer_Door_Mat.py
=> new Python project

C++/GCD_Calculate.cpp
It calculate GCD of two numbers
----
C++
Fix #166 #33
=> Added GCD_Calculate.cpp

C/HelloOpenSource.c
Print hello open source
----
C
Fix #33 Fix #166
=> Added HelloOpenSource.c

Html/Hello world heading.html
=> Hello worldh1.html

Javascript/reverse_int.js
Function that reverse a integer number
----
Javascript
=> reverse int function

Java/Hello-world.java
=> update hello world

Javascript/converting temperatures.js
Converting temperature from Celsius to Fahrenheit 😃   
----
JavaScript
=> Add converting temperatures formula

Expressjs/axiosToDo.js
Makes a request to a todo api and returns the response
----
Javascript/ Express
=> Added axios to do example

C++/prime_or_not.cpp
----
Tells if a number is Prime or Not.
C++
=> Added Prime or Not program

Javascript/reverse.js
Add a simples reverse function that reverse a given string.
----
Javascript
=> add JS reverse function

C++/NQueen-PrintAllSolutions.cpp
Take as input N, the size of a chess board. We are asked to place N number of queens in it, so that no queen can kill other
----
This program is written in c++ language
=> N-Queen-Problem

Dot Product.py, Python/Dot Product.py
The program prints the dot product and angle between two vectors input by the user in rectangular coordinates
----
Python 3.x
=> Dot Product and Angle of two vectors

Rust/hello_earth.rs
=> rust hello earth!

NASM/hello-world.asm
=> Hello World in NASM

CSS/hello.css, Javascript/hello_world_function.js
Creates a web page with a hello world message and a blue background.
Added a hello world js file
----
css
JS
=> Added a hello css file

PHP/geriadam.php
=> Hello World PHP Geri Adam

Golang/helloworld1.go
=> hello world in golang

Html/HUMANS VS MACHINES
=> Added description of an indian chess grandmaster

xquery/HelloWorld.xqy
=> XQuery Hello World

Shiva924
Prints my github handle 🙌🏻
----
JavaScript(JS) in Hyper Text Markup Language(HTML) with the help of Document Object Manipulation (DOM).
=> Create github handle using JS in HTML

Html/helloworld2.html
=> Rename helloworld.html to helloworld2.html

Python/add.py
=> modified add

MATLAB/demodulator.m, MATLAB/modulator.m
Modulate signal with the desired frequency.
----
MATLAB
=> Signal Modulator

Python/LeapYear.py
* Fixed typo in the variable name
* Years 2000, 2400 etc were falsely detected as non-Leap
=> Fix errors in the leap year detection

heelo world
=> Create heelo world

C++/Polymorphism.cpp
=> Added Polymorphism Program

C++/evenoddBitManipulation.cpp
odd even test using bit manipulation operations 
----
=> add evenodd with bitmanipulation

Html/helloWorldBySungk44.html
It displays a greeting from me in English and Korean!
----
html
=> added-html-hello-world

Python/TriangleHelloWorld.py
Print Half Triangle Hello World
Python
=> Add Hello World 

C/something.c
just prints "hello world"
----
C
=> added something.c

chicken/index.ck
Write `Hello world!`. in chicken 
----
Chicken is an esoteric programming language by Torbjörn Söderstedt, in which "chicken" is the only valid symbol.
you can find the complete description on: https://esolangs.org/wiki/chicken
=> Added `Hello, world!` in chicken

Html/hello-world-ph.html
=> Added hello world HTML

Small Basic/helloworld.sd
Prints "Hello World"
----
Small Basic
=> Small Basic

C++/SmAlLFaCtOrIaL.cpp
=> Added Small Factorial Program in C++

Golang/helloearth.go, Python/hello_earth.py
prints hello earth
----
python!
=> hello earth in python

Java/Hello-World-New.java
=> create new hello-wolrd programme in java

Python/helloworldnm.py
=> add hello world in py

Terraform_Cloudflare/README, Terraform_Cloudflare/cloudflare.tf
nouveau fichier : cloudflare.tf
----
=> Hello world w/ Terraform and Cloudflare (novice)

C++/RatinMaze.cpp
Added a path finder algorithm's recursive implementation for the problem rat in a maze (https://www.codechef.com/problems/BPHC03).
Author :- Manu S Pillai (manupillai308)
It finds and prints the path for a rat which is at the position (0,0) in a graph to (n,n) (user defined n).
C++
=> Recursive path finder for RatinAMaze problem.

Python/ceasar-cipher.py
Utility that encrypts and decrypts strings using Ceasar Cipher.
----
Python 3
=> Added Python/ceasar-cipher.py script.

Javascript/Advance-if.js, Javascript/boolean.js, Javascript/hello-world.js, Javascript/if.js, Javascript/logical-and-or.js, Javascript/numbers.js, Javascript/strings.js, Javascript/temp-conversion.js, Javascript/variable.js
=> Some New Program

AngularJS/app.js
A Simple Hello World program in AngularJS
=> Hello World in AngularJS

Forth/helloworld.fth
Print into the terminal the statement: "Hello World!"
Forth
=> Add Hello World Forth Program

Ruby/christmas.rb
Check if the current day is christmas.
----
Ruby
=> christmas.rb added

Python/Average_for_3test.py
the average of three numbers
python3
=> code in python 3

C++/Palidrome.cpp, Javascript/hello_world_function.js
checks the number is palindrome or not
c++
=> palindrome program modified

Bash/clean_old_images.sh
Cleaning the docker images with tag NONE, created when you create a new image from a previous repository
----
bash
=> Added clean_old_images.sh

Golang/hello_jflayhart.go
Prints `Go World! Oh, and hello.`, since it's my first time writing GO.
[Go-lang](https://golang.org/)
=> Added my first Go script

Golang/hello-world.ru.go
print hello on ru lang
----
go
=> add golang ru lang

Javascript/chetanraj.js
Prints my github username
----
JavaScript
Ref: #17
=> Created chetanraj.js

FLEX/identifiers.l
It identifies identifiers in a file.
----
FLEX
=> Added a flex program to identify identifiers.

FLEX/vowels.l
It removes vowels from a file.
----
FLEX
=> Added a flex program to remove vowels.

FLEX/special_char.l
It removes special characters from a file.
----
FLEX
=> Added a flex program to remove special characters.

Python/Guessing Number Game.py
a number guessing game which you have to guessed the randomly generated number in 5 numbr of turns.
programming language used - Python!! :)
=> A number guessing game!

hello.go
=> add golang code

Java/MathMethods.java
MathMethods provides some helpful methods for solving problems on projecteuler.net
Use MathMethods to help you solve problems in projecteuler.net problems. No solutions are presented
----
Java
=> Added MathMethods.java

Zig/hello.zig
Prints 'Hello, world!'
[Zig](https://ziglang.org/)
=> Add hello world written in Zig.

C#/Hacktoberfest Hello.cs
This commit adds the hello world app for 2018.
This program is a basic hello world app
----
C#
=> Adding HelloWorld app for Issue #33

SELECT./helloworld
prints the hello world
----
SELECT.
Check out the [Reference](https://esolangs.org/wiki/SELECT./Hello_Worldl)
=> hello world in SELECT.

Javascript/hello.js, Javascript/hello_world.js, Python/bubble-sort.py
=> bubble sort

Prolog/fibonacci.pl
Print 100 first numbers in Fibonacci's sequence (more if specified)
----
SWI-Prolog
=> Fibonacci in Prolog

Brainfuck/fibonacci.bf, Prolog/fibonacci.pl
Prints Fibonacci sequence (as bytes) until the interpreter gives up
An interpreter with uncapped cells and integer printing will show it properly
----
Brainfuck
=> Fibonacci sequence in Brainfuck

Linotte/bonjour_monde.liv
Print a `Hello World!` message
Linotte
Ref: #17
=> Added Hello World in Linotte

Python/BackTracking/ClimbingStaircase.py, Python/BackTracking/StringPermutations.py
The folder already has some problems with their solution. All the problems have a description and a link of the place where I took it from.
Python
=> Added a folder for backtracking problems in python

Html/Jaydeep_Eraniya_blog.html, Html/jaydeep_eraniya_photoGrid.html
This is simple model of bootstrap grid system.
----
Code is written in HTML,CSS.
=> My Third Contribution

Python/game_TTT.py
----
It helps User to play Tic Tac Toe GAme
Python
=> Ä Program of Tic Tac Toe game added 

Swift/rover.swift
Suppose you have a rover that starts at position (0,0) on a NxN matrix. Given an array of commands and a number N which denotes a NxN matrix. Return the position of the rover after all the commands have passed.
Swift
=> added a swift programming challenge answer

C++/EvenOdd.cpp, Python/HiWorld.py
HI WORLD AND EVENODD
PYTHON AND CPP
=> i have modified hi python an evenodd in cpp

Html/Hello Big Font.html
changed the colour, and added extra exclamation mark
----
html
=> Update Hello Big Font.html

Python/Hello India.py
=> Create Hello India.py

MATLAB/Convolution, MATLAB/Graph plotting
Convolution of two variables
This program gives the convolution of two variables
----
Programming Language:- Matlab
=> Convolution

C++/level-order-traversal.cpp, C++/mirror-tree.cpp
1. mirror-tree : Prints the mirror image of a binary tree
2. level-order-traversal : Performs level order traversal on a binary tree
----
Both programs are written in C++
=> add mirror tree and level-order-traversal programs

Html/ThaTruth24Helloworld.html
=> ThaTruth24

LLVM-IR/hello_world.ll
=> Add Hello World for LLVM-IR

Python/webserver.py
----
This is a simple flask webserver written in python. Serves a webpage which prints the OS of the client.
Python
First timer here #17
=> simple flask webserver written in python

ClojureScript/hello.cljs
It prints "Hello World"
----
In ClojureScript
=> Add ClojureScript

C/Keshavprogramhelloworld.c
----print hello world
c language
=> program added

KnockoutJS/index.html, KnockoutJS/scripts.js
=> Added KnockoutJS hello world

Swift/hello.swift
Create an array of localized languages
----
Swift
=> Start of Hello Array for multiple languages around the world

Mint/.gitignore, Mint/HelloWorld.mint, Mint/mint.json
Shows "Hello World!" on the screen as a web application.
----
It is written in Mint https://github.com/mint-lang/mint https://www.mint-lang.com
=> Added Mint 

C++/QueueMenu.cpp
Implementing Queue Data Struture with menu
C++
=> Add Program Queue with menu in C++

VueJS/Hello World/index.html, VueJS/Hello World/style.css
Ouput `Hello World !` and a toggle button which show/hide `And Hacktoberfest 2018 !`
----
[VueJS](https://vuejs.org/) - JavaScript
=> Add new VueJS example (in index.html)

C/hello_world_.c
=> create hello_world_.c file

Python/swapping_variable_values.py
=> I have modified program

Javascript/filter.js
=> Adding a javascript filter function

Prolog/prolog.pl
Write "Hello" and "World !" on different lines : D
----
Prolog
=> write hello and world on different lines

C++/stack.cpp, C/hellouniverse.c
Uses functions of stacks
----
C++
=> Add stack file

Language/HelloWorld.java, Language/ReadMe.md
It prints Hello world on Output screen
----
It is written in Java
=> HelloWorld

C/Producer Consumer.c
=> Add producer consumer implementation to C programs

C++/sam.cpp
----this will print the hello world
cpp
=> first cpp file

Java/Calculator/Calculator.java, Java/Calculator/Main.java, Java/ChristmasTree.java
=> New Calculator in Java

C#/RNG-Simulator.cs
This is a random number generator simulator.
---
C#
=> added rng-simulator.cs

Rust/hello_web_server.rs
Open web server on 9802 port.
----
Rust
=> Create web server for saying hello in Rust

C++/swade_says_wassup.cpp
Prints "Wassup world!"
----
C++
=> Added swade_says_wassup.cpp inside c++ directory. Happy hacking

JSP/helloworld.jsp
=> hello world in JSP

Pixie/hello.pxi
It prints "Hello World"
----
In Pixie :sparkles: https://github.com/pixie-lang/pixie
=> Add Pixie lang

Html/HelloWorld.html
=> HacktoberfestOK.php

PHP/HelloPhp.php
I have add the marquee for running text
----
=> HelloPhp.php

Javascript/privet.js
=> Rename hello.js to privet.js

Java/CountM.java
=> Added a program that counts UpCaseLetters

BIRL/if-else.birl, BIRL/while_loop.birl
This pull request adds an example of a classical while loop with a simple stop condition
----
It's written in the birl programming language
docs can be found @ birl-language.github.io/
=> While loop example in the BIRL language

Java/helloMundo.java
Show Hello World in the screen
Java
=> New hello World

Labyrinth/fizzbuzz.lab
This is the fizzbuzz challenge written in Labyrinth. For multiples of 3, show fizz then for multiples of 5 show buzz. For numbers which are both multiples of 3 and 5 show Fizzbuzz.
----
Labyrinth
=> Add FizzBuzz in Labyrinth

Groovy/Repeated_HelloWorld.groovy
displays hello world inside a while-loop
----
groovy script
=> update with groovy script

Java/determinant.java
calcul matrix determinant
----
writen in java
=> determinent.java

C/helloWorld.c, Html/HelloWorld.html, Python/BubbleSort.py, Python/Hello-World.py, Python/Hello-world.py, Python/fizzbuzz.py, SELECT/helloworld
=> Added FizzBuzz for Python

C/banker2.c, PHP/server.php, Python/paint.py
----it does bankers algorithm, paint app, and server connection respectively
python, c and php
=> Added python, c and php codes

C++/Hello-world.cpp
=> hola mundo español

Bash/hi_banner.sh
Announce hello world vertically
----
shell script
=> add hi_banner.sh in bash directory

Java/DateDemo.java, Java/SerializeDemo.java, Java/generic.java
this is used to file writing in java this can use as keep records in the programme
java
=> Java serialize

Java/generic.java
=> java generic with example

Python/project_euler01.py
Solution to Project Euler problem 1 :)
----
Python
=> Add solution to project Euler problem 1

NewtonScript/HelloWorld.nwt
Shows you Hello World!
NewtonScript. An old language for the Apple Newton platform.
=> NewtonScript Hello World for nostalgia

Batch Script/Hello_World.bat
Print Hello World on the Screen
Batch Script
=> Hello World in Batch Script

Javascript/fizzbuzz.js
This is the fizzbuzz challenge written in javascript. For multiples of 3, show fizz then for multiples of 5 show buzz. For numbers which are both multiples of 3 and 5 show Fizzbuzz.
Javascript
=> added fizzbuzz challenge using javascript

C++/topological sort.cpp
It will give topological sort array in graph input.
----
c++
=> Added topological sort programme

Java/HelloWorldT.java
=> created HelloWorldT.java file

Angular/src/app/app.component.ts
=> Change title

Javascript/hello-world.v2.ru.js
print hello world on ru lang
----
js
=> add js hello world on russian lang (strange way)

Python/all_prime_numbers.py
Program to get all prime numbers till N
----
Python
=> Program to get all prime numbers till N

Java/HelloWorldRehan.java.txt
=> Add<rehan jananga> to contibuted list

CLIPS/hello-world.clips
It prints Hello World!
----
In CLIPS. A language I used at AI in my degree 😄
=> Add Hello World in CLIPS

Python/python-hello.py
Prints hello world
----
Python
=> #166 added another hello world python file

Prolog/options.pl
Ask the user to select an option and print it.
----
Prolog
=> Add a simple prolog program

Java/HacktoberfestJavaHelloWorld.java
=> Hello World adding

Html/hello-lenzfliker-world.html
multiple hello world texts marquee-ing  at different speeds
----
html
=> added a spooky hello world html

Java/Hello-world.java, Java/bubble-sort.java
=> second commit of hackto

fibonacci/Fibo
displays fibonacci series
----
python
=> using recursion

C/kadane.c
Implemantation of Kadane's algorithm in C language.
Kadane's algorithm (Maximum subarray sum)
----
C
=> Added kadane.c

Python/Counting the occurence of each word.py
=> Update Counting the occurence of each word.py

Python/money_count.py
the program prompts you to enter how many of each bill you have, then spits out the total money (only works for USD)
----
python 3
=> added a python cli tool to count how much cash you have

Javascript/2 PLayer Box Game/README.md, Javascript/2 PLayer Box Game/gameTestArea.html
It's just a simple 2-player box dogding game. There is no score count or life count yet, but if someone could add that, that'd be amazing.
----
Javascript, HTML, CSS
=> improve this thing I made and make it great again, plez

C++/loop_in_linked_list.cpp
=> Added Linked List Loop Detect Code

Javascript/hello_world_class.js
=> Add hello world oop style to javascript folder.

comments_capitalise.l
It capitalises the comments in a file.
----
FLEX
=> Added a flex program

PHP/MySQL_Connection/PDO.php
=> MySQL connection using PHP Data Objects

C/infix/cstack.c, C/infix/cstack.h, C/infix/infix.c, C/infix/postfix.c, C/infix/stack.c, C/infix/stack.h
Solves an infix expression.
----
C language
=> Added infix problem's solution in C

palindrome.l
Counts the number of palindromes in a file.
----
FLEX
=> Added a flex program - palindrome.l

Ruby/even-or-odd.rb
check number is even or odd
Ruby
=> [Ruby] check number is even or odd

Java/Hello_world_fun.java
=> Hello world with funtion

C/Hello_world.c
Prints a hello world output
----
C
=> Added hello world file to C folder

C++/Merge_Sorted_LL.cpp, C++/loop_in_linked_list.cpp
=> Added Merge two sorted linked lists cpp code

C/series1.c
=> Improved time complexity, solving in constant-time

C/Ola_Mundo_Hacktober.c
It writes a "Hello World" in portuguese.
It is written in C
=> modified by carlos

C/GCD_Calculate.c
num1 and num2  initialized with n1 and n2 values, after reading the n1,  n2 value from the user
----
=> num value initialized with n in correct position

C++/templated_hello_world.cc
Introduces a simple templated hello world function and variadic arguments
----
C++
=> Templated hello world function

C/pthread.c
the program shows implementation of pthreads in c
----
c
=> Added c program to show pthread library

C/HelloWorld.c, C/infix2postfix.c, Python/take_a_break.py
HelloWorld.c
prints Hello World! in a unique check this out 
take_a_break.py a python script to refresh you while long working hours 
----
=> uploade HelloWorld.c alongwith a python script 

Python/pyHelloWorld.py
=> Add Hello_World in python

Javascript/gulpfile.js
It's a simple Gulp build file
----
Javascript
=> Add Gulp Build File

Processing/HelloWorld.pde
It prints "Hello World!" to the console.
----
It is written in [Processing](https://www.processing.org/).
=> Add Hello-World! in Processing

Java/helloWorld.java
Create hello world of java with joption pane
----
Java
=> Create Hello  world

Java/AreaOfShapes.java
it calculates the area of any given shape
----
java
=> Added area of shapes calculator

NodeJs/omdbRequest.js, NodeJs/parameters.js
Shows how to do an api request using nodejs
nodejs
=> adding omdb request

Deep_Learning/Overview.md, Jupyter Notebook/Fast_data_processing_in_python.ipynb
=> Fast data processing in Python

Pikalang/hello-world.pika
Prints "Hello World!"
----
[Pikalang](https://esolangs.org/wiki/Pikalang), an esoteric Language based on Brainfuck.
Code can be compiled using a site like https://www.dcode.fr/pikalang-language
=> Added Pikalang

PHP/echoHelloWorld.php
Program prints hello world 😄 
It's written in PHP
=> add another php hello world

Scala/HelloHacktoberfest.scala
This will print 'Hello, Hacktoberfest YEAR' as the output
----
Scala
=> Added Scala/HelloHacktoberfest.scala

Golang/holamundo.go
Print Hello World (in Spanish)
Golang
=> Add HolaMundo.go

Kotlin/calculator.kt
It can execute a calculation on two integers, either add, minus, multiply or divide
----
Kotlin
=> Added calculator

C++/helloWorld.cpp
=> Updated hello world

Python/Hello_Hacktoberfest.py, Scala/HelloHacktoberfest.scala
It will output as "Hello, Hacktoberfest 2018"
on running
`python Python/Hello_Hacktoberfest.py`
----
Python2.7
=> Python hello hacktoberfest

Java/HelloWorld/src/Hello_World.java
=> created Hello_World.java

Java/SayHello.java
=> Added SayHello.java

C++/8puzzle.cpp
This program solves the 8 puzzle problem in AI using Best First Search
----
C++
=> Add 8 puzzle problem (AI)

sed/hello_world.txt
=> Add hello world in sed.

Python/hello_world_in_python.py
=> Add Hello World in Python

C++/HelloOctober.cpp
HelloOctober.cpp adds another Hello World program to the C++ folder.
----
C++
=> Add hello world to C++ folder

C/malloc_example.c
The program stores a user selected integer into memory. 
Source includes comments to educate best practices and potential errors by new programmers.
----
C
=> Added malloc_example.c to show basic memory allocation in C

Javascript/helloWorldFromCharCodes.js
The script prints out and "Hello, world!" message from ASCII char codes.
----
Javascript
=> A javascript hello world message from char codes.

Bash/HelloWorld_fromTako.sh, Python/HelloHacktoberfest2018.py
Simple "hello world" python script.
Prints "Hello world! Have a good Hacktoberfest!"
----
Python
=> Add HelloHacktoberfest2018.py

C/helloWorld10.c
The program prints Hello, World! 10 times.
----
The program is written in C.
=> added helloWorld10.c 

Python/ReverseString.py
this program can reverse a string recursively and checks whether it is a palindrome or not.
This program reverses a given string recursively.
----
It is written in Python3.6.4
=> committed python file

Java/SelectionSort24Line.java
=> Selection Sort

AnyaBasic/hello-jeje.abs, AnyaBasic/hello-tagalog.abs, AnyaBasic/hello.abs
Show tagalog and jejemon version of hello world
AnyaBasic
=> #33 added tagalog and jejemon version of hello world

Nadeshiko/hello, world.txt
print "Hello, World!"
----
Nadeshiko
=> Add Language, Nadeshiko

C/hello.c, C/hello_world_.c
=> added my name

R/fib_recurse.r
the program computes the Fibonacci sequence recursively.
This program computes the Fibonacci sequence recursively and prints them.
----
This program is written in R.
=> committed r file

C/tictactoe.java
It is a game . In Java language
----
=> tictactoe.java

C/Multiplication Table
This is a program in C language for a multiplication table of an integer upto the required range.
=> Multiplication Table.

C/Factorial
Its a program in C language for finding the factorial of a number.
=> Factorial of a Number.

C/Simple Interest
Program in C language for finding simple interest.
=> Finds Simple Interest

C/Converts temp
Program in C language which converts temperature in fahrenheit to celsius.
=> Converts temperature.

C/Matrix Multiplication
Program in C which multiplies two matrices.
=> Matrix Multiplication

Z80/helloworld.src
Prints "Hello World!" to the calculator screen.
----
Z80 assembly
https://github.com/Hacktoberfest-2018/Hello-world/issues/33
https://github.com/Hacktoberfest-2018/Hello-world/issues/166
=> Added hello world in z80 assembly for the TI-83

Idris/hello.idr
---- says Hellow World
in Idris
=> Add Hello World in Idris

C++/hello-world-2.cpp
----prints "hello world" on execution
C++
=> a file added in C++

Java/N queens
Arranging N queens in a N*N board where no queen collide with other.
Arranges N number of queens in an N*N board.
----
java
=> N queens problem

Python/hello_world_nata.py
It prints my github handle.
----
It is written in python.
=> Add github handle

Picky/hello_world.p
It's a simple "hello world" program.
----
The program is written in **Picky** language (check white paper here: [white paper of Picky language](http://lsub.org/ls/export/newpicky/picky.pdf))
=> Added Picky language

Python/Prime numbers.py
---- It prints all the prime numbers one on each line
It is written in Python
=> Added prime numbers program in Python

Python/GCDSUM.py
solve a popular question of competative programing.
----
python
=> Added a python file

Python/rot13.py
=> Rot13 Encryption

Python/Mouse_cursor_Co-ordinates.py
Uses pyautogui module to show cursor position as output on screen. 
Continuous updates of new cursor location and clearing of screen.
Helpful when writing scripts to automate some clicking tasks, by using this one can find the co-ordinates easily and note them down.
----
It is written in python 3.
=> complete code to show co-ordinates of cursor

C#/factory.cs, C#/prototype.cs
Nothing really. They show how we can use factory and prototype design patterns.
----
C#
=> add c# builder and factory patterns

Javascript/helloUniverse.js
----
prints some content
JavaScript
=> Created hellouniverse.js

Python/socket_code/client_process.py, Python/socket_code/server_process.py
Establish a socket connection between client and socket using TCP connection
It contain 2 files :-- server_process.py and client_process.py
Python
=> Added server-client socket program in Python

Python/endless_greeting.py
Prints hello world and measures time
----
Python
=> Endless greeting

Python/Hello-World.py
=> Made it more better

Javascript/hello-world-kssbro.js
Console logs Hello World
JavaScript
=> Added my file.

Html/Bouncing_Ball.html
---- Creates a bouncing ball using animation in HTML page
HTML & CSS
=> Bouncing Ball

Eiffel/hello_world.e
Displaying Hello World
----
Eiffel
=> Added Eiffel Hello World

C++/Ascending order.cpp
changed the swapping method
----
=> Update Ascending order.cpp

Typescript/GameOfLife.ts
It is an implementation of Conway's Game of Life 
----
TypeScript
=> Added Game of Life in Typescript

Javascript/reverseAString.js
Reverses a string 
----
JavaScript
=> Added a simple algorithm to reverse a string

Html/Helloworld js by terabo.html
=> Helloworld By terabo090

Kotlin/hello-world.kt
=> Add hello-world.kt

Java/LongestSubstring
Gives Longest Substring without repeating character
return longest substring without repeating character
----
java
=> Longest Substring Without Repeating Character

Java/RotateMatrix
Java program to rotate a N*N matrix by 90 degree.
It rotates a N*N matrix by 90 degrees.
----
java
=> Rotate Matrix

Hack/helloworld.php
Hello World in Hack Programming Language
=> Hello World in Hack

Python/Python Hello World.py
=> hello world for python3 above

Python/newfile.py
I did Fibonacci series 
----
It is written in python language
=> added fibonacci program code

PHP/Factorial.php
Calculating Factorial of a Number.
----
PHP
=> Factorial PHP

C++/kthlargest.cpp
t is the number of test cases and n is the number of elements in each test case.
Prints kth largest element in a stream.
----
C++
=> C++ program to print kth largest element.

C/h3ll0_world.c, C/hell0_world.c
----This a simple hello world c program
=> H3ll0W0rld C Program

CherryBlossom/hello.cb
Fixes #1
Prints Hello World
----
[CherryBlossom](http://vivin.net/projects/cherryblossom/)
=> Add Hello World in CherryBlossom

C++/Loay.cpp
=> added loay prog

Python/Morse_Code_Translator.py
convert text to morse code
python
=> added sys args

Python/json_parsing.py, Python/xml_parsing.py
parse json and XML data and retrieve information from it.
----
python
=> added json and xml parsing

Golang/stack.go
Is a stack data structure
In GO
=> Add stack structure in go

C++/hello_ikad95.cpp, C++/yolo.cpp
=> C++ Code to print Hello

C#/HelloWorldHacktoberfest.cs
It Prints a message when executed
----
C#
=> Adding new HelloWorld in C#

Ruby/happy_hacking_hello_world.rb
Spits out a simple CLI hello world
----
Ruby
=> happy hacking

C++/Ascending order.cpp
Break out of loop if no swaps are made in a particular outer iteration
----
=> Introduced a counter that checks for sortedness

C++/bubbleSort.cpp
i have added a line which increases the speed of the cout and cin 
it is written in c++
=> bubbleSort cin and cout speed increased

111.php, Batch Script/hlo world, HW.bat
says hi to the world!
python , batch
=> Added files in correct folders.

Javascript/HeyWorld.js
----It prints "Hey world!..." to the console
Javascript
=> Adding es6 hey world program

Java/Rotations.java
It finds all the possible rotations of a string
Java
=> All rotations of a string

CodeForJava/Hello.java
=> Hello world code in java

C++/gcd.cpp
Using Euler's GCD algorithm. Refer GeeksForGeeks for algorithm
----
=> A simpler recursive approach

C++/helloworld_new.cpp
this program just print a line in the terminal 
----
c++
=> new helloworld_new.cpp added

pony/hello.pony
Prints `Hello, Hacktoberfest!`
----
[Pony](https://www.ponylang.io/)
=> Add hello.pony

Typescript/hello-leticia.ts
write in console
----
TypeScript
=> this is my contribution

Python/find_factorial.py
The program calculates the factorial of a number entered by the user.
Python
=> Add a program to find the factorial of a number provided by the user

Bliss/HelloWorld.bli
Hello World in the old systems language, BLISS.
It prints hello world
----
Bliss
=> Created HelloWorld

Bash/simple script hello world.sh, docker/README.md, docker/docker swarm service create example.sh
Deploy a example server in swarn mode
docker compose
=> docker Example script

C/leters-counter.c
=> add leters-counter.c

Python/password_manager.py
Password management script -- Not safe
----
Python3
=> Python Password Manager

hola-mundo/index.html
Added a simple html page with a js alert box. 
----
html, js
=> added hola-mundo

C++/Hello world.cpp
=> simplified hello world

Bash/setup-build-env.sh
Setups the build environment of arch/debian/fedora
----
Shell
=> Add a script in bash

ring/hello,world.ring
----prints hello,world
it is written in Ring programming languge
=> hello world!

MIPS/sorting.asm
=> created a program to sort array using mips

PHP/ScrambleHelloWorld.php
Run in the console to watch PHP guess random chars trying to get to hello world! Only correct letters move on to the next round.
----
PHP
=> Added ScrambleHelloWorld.php

C++/SoldiersAndBadges.cpp
=> Code Push 5

Javascript/palindrome.js
Checks whether the passed word is palindrome or not
----
JavaScript
=> Added palindrome program for JS

Html/helloworld.html.twig
It creates a Hello World Page with Symfony with a basic base.html.twig
html / twig
=> html twig Hello World

Zsh/epoch
Signed-off-by: Adam Jimerson <vendion@gmail.com>
Converts unix timestamps to human time, or gives current time in unix timestamp
ZSH shell script
=> Add Zsh script to convert unix timestamps to human time

Javascript/hello_world/index.js
PRINT "WELCOME TO THE HACKTOBER FEST"
JAVA SCRIPT
=>  WELCOME TO HACKTOBER FEST

Bash/HelloWorld
The program is a simple Hello World program that follows Google's shell style guide. (https://google.github.io/styleguide/shell.xml)
----
Bash!
=> Add HelloWorld

Python/selectionsort.py
=> Python Selection Sort

Turing/helloworld.t
prints "Hello World"
----
Turing
=> Turing Hello world

GLSL-Frag/hello.frag, GLSL-Frag/readme.md
Provide a GLSL Fragment Shader to render `HELLO` as pixel art.
GLSL Fragment Shader (`version 300 es`)
=> Add GLSL Fragment Shader example

Ruby/konnichiwa.rb
- puts "Hello, world." to STDOUT.
----
- Ruby
=> Add my hello world Ruby script

Html/kentshello.html
=> added kentshello.html

Grass/HelloWord.gs
What does the program do ?
Creates some dank ASCII art.
In what programming language it is written?
Grass
=> Grass - Hello World 

Java/SalomDunyo.java
Initial step to become the greatest programmer of all time :)
Program prints "Hello Funny Word" in 4 different languages. English, Russian, Uzbek and Turkish.
And I wrote some basic things I learned today along with my objectives for the future :)
----
Java
=> SalomDunyo.java file is created

C/sasantua.c
A project I did during the piscine for the 42 Silicon Valley programming school. (Almost) fully norminette compliant! Which is a very strict formatting style.
----
=> Sastantua from 42 Silicon Valley school.

Php/HelloWorld_Rasil
=> Removed interpolation

Python/digital-sum.py
The program is a recursive function that adds up each number of a digit.
Doing digitalSum(2018) would return 2+0+1+8 = 11
----
Python
=> Added recursive function digital-sum!

Cpp/print.cpp, Python/fibonacci_optimized.py
Fibonacci with memory optimization
----
Python
=> Atualização

Python/genetic_hello_world.py
Program demonstrates genetic algorithm usage by generating specified text using randomly generated characters.
Program uses population which is consisting of randomly generated text. Each iteration program calculates fitness of each population, builds selection pool which contains more elements with higher fitness rating, randomly select elements from selection pool that will be used as population for next generation with slight chance of replacing any letter in element. 
This program is written in **Python 3** (tested in 3.7).
=> Added python hello world genetic algorithm.

Java/BruteForceHelloWorld.java
Java program that basically brute forces "hello, world!" and logs the total number of attempts at guessing each character.
=> Added brute force hello world

C#/HelloWorldInGreen.cs
Says hello world in a green font.
----
The great C-Sharp
=> Add HelloWorldInGreen.cs

Python/hiya_world.py
=> Add python hiya

C/activityselectionproblem.c
This is a greedy approach to solve activity selection problem based on start and finish time. 
Input: A set of activities S = {a1,…, an}
Each activity has start time and a finish time
ai=(si, fi)
Two activities are compatible if and only if
their interval does not overlap
Output: a maximum-size subset of
mutually compatible activities
----
C language
=> an activity selection problem greedy approach implemented in c

Harbour/hello.prg, Harbour/readme.md
Just renders Hello World.
----
Harbour (Clipper)
=> Added hello world in Harbour (Clipper)

Java/GenericMergeSort
Only works on arrays so far
----
=> Created MergeSort for generic classes

AL/CustomerCardExtension.al, AL/GreetingsManagement.al, AL/HelloWorld.al, AL/app.json
Just renders Hello World.
----
AL (Dynamics 365)
=> Added hello world in AL (Dynamics 365)

Python/binary_search.py
=> Add python binary search

Ocaml/leap.ml
Function to determine whether a given year is a leap year.
----
Ocaml 🐫
=> basic ocaml program to determine whether a year is a leap year

Python/HelloWord.py
=> Updated by Pulkit

PowerShell/HelloHackedWorld.ps1
Some good motivation in PowerShell with the username
----
PowerShell :D
=> New PowerShell script with some motivation inside

Bash/train.sh
It shows 10 trains in terminal
----
Bash
=> Add Bash train program

Java/Operations.java, Python/automorphic.py
Automorphic Number is a number that exists at the end of its square. eg: 5 exists at the end of 5. 25 exists at the end of 625. 
----
###written in python 3
=> authomorphic.py

Javascript/noImg.js
It is a script for work. Just add it as a bookmarklet, and click it to remove all the images and videos from a webpage you're viewing
----
Javascript
=> Add noImg.js

Python/Factorial of a Number, Python/Program for Fibonacci sequence
Its an Program to display the Fibonacci sequence up to n-th term where n is provided by the user
----
Python
=> Created a Program for  Fibonacci Sequence

CSS/bgimg_using_id
=> Background image — using an ID

Python/command-line-arg.py
command line programming
----
python
=> Created command-line-arg.py

Html/LInk_opening
=> HTML Open Link in New Window

Javascript/ReverseAnArray
=> Reverse an Array

geode/hello.g
figured I'd throw my language in here, feel free to check it out here:
https://github.com/geode-lang/geode
Just logs hello world to the console
----
The Geode Programming Language, a little side project of mine
=> Add hello world for the geode language

Bash/helloworld, C++/djikstra.cpp
Runs the Djikstra's algorithm
C++
=> Add Djikstra algorithm in C++

PHP/phpelephant.php
Display a message for PHP ElePHPant 🐘
----
PHP
=> Hello ElePHPant 🐘

C/Makefile
Noticing there is no Makefile in the C directory, I decide to write a Hello world (after building all `.c` files in this folder)! This file is naive, though.
To begin with, type `make`.
----
[GNU Makefile](https://www.gnu.org/software/make/)!
=> naive Makefile

Html/customHello.html, MoveCursor/MoveCursor.ps1, MoveCursor/README.md
This small script moves your mouse cursor every 10 seconds one pixel to the right. If it reaches a specific x-position, your cursor will jump back to the start.
----
Windows PowerShell script
This html file let's you insert your name and prints you a custom welcome message for Hacktoberfest. (you can literally print it)
----
HTML
=> Added MoveCursor.ps1 and customHello.html

C#/HackersHelloWorld.cs
Prints "Hello World!" lines on the console as long as you are mashing your keyboard.
C#
=> Funny Hello World in C#

Scala/PureHelloHacktoberfest.scala
The program prints `Hello, Hacktoberfest 2018` to the console
----
Scala
#166
=> add PureHelloHacktoberfest in scala (using scalaz)

Javascript/hello stdout.js
Prints "hello world" to the stdout stream; written in js
=> js: Hello world using stdout

Javascript/helloyou.js
Console logging: "Hello, you! 👦🏻👩🏼"
Javascript
=> Hello you!

Cpp/gcd.cpp
calculating GCD of two numbers.
C++
=> Euclidean GCD in Cpp

Html/hello_hacktoberFest_world.html
=> adding redvan's hello hacktober fest world HTML code

LiveScript/hello-world.ls
It prints "Hello, World!"
----
LiveScript
---
[LiveScript](http://livescript.net/) is a language which compiles to JavaScript. It has a straightforward mapping to JavaScript and allows you to write expressive code devoid of repetitive boilerplate. While LiveScript adds many features to assist in functional style programming, it also has many improvements for object oriented and imperative programming.
LiveScript is a fork of Coco and an indirect descendant of CoffeeScript, with which it has much compatibility.
=> Add LiveScript version

Fortress/HelloWorld.fss
A simple "Hello, World!" example written in the experimental Fortress programming language from Sun Microsystems circa 2006.
=> Add HelloWorld example in Fortress lang

C/ArraySort.c
This C program can be used for sorting the array.
----
=> Created ArraySort.c

Bash/greetings-planet.sh, Java/GreetingsPlanet.java
=> Added GreetingsPlanet.java

Jupyter Notebook/first_steps_with_tensor_flow.ipynb, Jupyter Notebook/intro_to_pandas.ipynb
This jupyter notebook provides a basic/intermediate introduction to Pandas along with plotting some  graphs for rudimentary data analysis.
Python3 on Anaconda
=> Introduction to pandas

Jupyter Notebook/first_steps_with_tensor_flow.ipynb
This notebook introduces the basic concepts of TensorFlow.
Python3 on Anaconda
=> TensorFlow Introduction

C++/LambdaVectorSort.cpp
Input: Vector with strings  
Output: Words sorted by length  
C++
=> Sort a Vector using a Lambda function

Python/fuzzer
Added a program that will fuzz a network port for inputs that make it break
It's written in python
=> Added a python fuzzer

C#/AlohaWorld.cs
Hello World in Hawaiian.
----
C#
=> Aloha World in C#

DOG/hello_world
=> add hello world for DOG language

Python/aloha_world.py
Prints 'Aloha World!' to the console
----
Python
=> added aloha_world.py

Sakshi/HelloWorld.py
Wishes you "Hello World" 
----
Python 3
=> Added new codes :-)

Javascript/aloha_world.js
the program will run a giant loop 
----
written in javascript
=> aloha_world function

Python/FizzBuzz.py
This program takes in a number input `n` and returns a list of numbers from 1 to n, where multiples of three it are replaced with `Fizz` and multiples of five are replaced with `Buzz`. For numbers which are multiples of both three and five output `FizzBuzz`. 
----
Python
=> Dictionary approach to FizzBuzz

C/Hello Romania.c, Python/date_day.py
Show message "Hello Romania"
C
=> Hello Romania <3

Shell Script/2048_Game.sh, Shell Script/bash_colors_styles.sh, Shell Script/how-many-commands.sh, Shell Script/pacman_game.sh
=> Shell scripts

Javascript/myHelloWorld
prints 'Hello World' to console
----
JavaScript
=> myHelloWorldUpdate

C++/Display Prime Numbers Between Two Intervals
=> Create Display Prime Numbers Between Two Intervals

Vala/count.vala
A simple guessing game
----
Vala
=> Add Vala sample

C++/Program to Multiply two Matrices by Passing Matrix to Function
=> Create Program to Multiply two Matrices by Passing Matrix to Function

Python/hello_friend.py
print normal hello world and about my interest.
Python :)
=> added 'hello.py' in Python language

C++/Program to Remove all characters leaving alphabets only
=> Create Program to Remove all characters leaving alphabets only.

C++/Matrix multiplication
=> Create Matrix multiplication

Python/factorial.py
I fix iteration. 
iteration starts at 2.
Python
=> fix iteration

Python/HelloWorldFirstTimer.py
=> Hello World by HassankSalim

crystal/hello_world.cr
Add hello world in crystal programing language
----
crystal
=> Add hello world in crystal

Cpp/Hello and
=> help wanted

Python/Multiply and Print.py
Simple program to multiply two numbers then print the result in a sentence.
Python
=> Created Multiply and Print.py

Python/flatten.py
Flatten a list of list
----
Python
=> adding flatten python

Python/hello_KPI.py
Print Hello KPI
----
Python 3.6
=> Hello KPI commit

Python/calculate_sum.py
Calculates sum of two numbers.
----
Python.
=> A basic sum file.

Kotlin/Bubble sorting
Sort the ArrayList using bubble sort
Kotlin
=> Bubble sort in Kotlin

Typescript/HelloWorldFunciton.ts, Typescript/SortArrays.ts
Say Hello world in console
----
Typescript
=> hello world ts function

Python/holaaa.py
=> hello people in spanish added

Html/helloworldsection.html
=> helloworldsection

Python/infmous-helloworld.py
Hello world in python
----
Python
=> new hello world in python

Python/hello-World.py
=> Create Hello World program in python

C++/hello_world_in_cpp.cpp, Html/assign3_st.html
=> create hello world in cpp

Python/hello_world_people.py
Calls the Function to print Hello World
----
Python
=> Created hello_world using function

PowerShell/himawariforTurkeyTimeZone.ps1
This is a live wallpaper script. I saw that in Reddit. Link: https://www.reddit.com/r/programming/comments/441do9/i_made_a_windows_powershell_script_that_puts_a/
And I added some functions about timing and alerts. I adapted it for Turkey time zone.
It's provided a live Earth wallpaper.
----
Powershell script
=> Live Earth Wallpaper Script

Javascript/devleaguePrepOct2018.js
=> adds a nice var

Javascript/devLeagueC13.js
Sweet little message dedicated to my cohort
----
JavaScript
=> adds dedication to DevLeague Cohort 13"

Javascript/helloworldcarl.js
=> Rename helloworld.js to helloworldcarl.js

Python/Hello World in Python
----Printing Hello World 
Python
=> Update Hello World in Python

GML/Hello-World.gml, GML/README.md
* Displays _Hello World_ in wavy text
* GML(Gamemakers' Language)
* You can try it out online at: https://yal.cc/r/gml/
* or download Gamemaker Studio(1x) at: http://www.yoyogames.com/
=> Added GML Language

Javascript/helloWorldSepi.js
it shows hello world on console
JavaScript
=> Sepi Hello Wolrd

Javascript/helloHacktoberfest.js
Hello world in JavaScript
----
=> Solves issues #166

Javascript/hello-lauren.js
the program prints "Hello, Lauren!" to the console
----
the program is written in JavaScript
=> added helloLauren fucntion in JavaScript folder

C++/Hello world.cpp
=> Update C++/Hello world.cpp

Javascript/remove_last_element
=> Remove last Element from Array

NodeJs/chai-example.js, NodeJs/check-object-size.js, NodeJs/gulp-exec-example.js, NodeJs/html-to-pdf.js, NodeJs/json-to-csv.js, NodeJs/package.json
=> Added HTML to PDF code

Bash/HelloWorld, C++/Hello world.cpp, PHP/php-comment/php-comment.php
=> adding how to create comment on php

NodeJs/chai-example.js, NodeJs/gulp-exec-example.js
=> mocha-chai example

NodeJs/chai-example.js, NodeJs/gulp-exec-example.js
=> Added gulp execution

NodeJs/chai-example.js, NodeJs/check-object-size.js, NodeJs/gulp-exec-example.js
=> Get Size of an object

NodeJs/chai-example.js, NodeJs/check-object-size.js, NodeJs/gulp-exec-example.js, NodeJs/json-to-csv.js, NodeJs/package.json
=> Jsontocsv example

Perl/Hello-World.pl
Prints Hello World 10 times
Perl v 5.10.0
=> Added Hello World perl

C++/helloworldcpplus.cpp
Prints hello world - hacktoberfest!
C++
=> Added a new helloworld

Kotlin/HiWorld.kt
=> Added Kotlin without args :)

C++/modular-exponentiation.cpp
this is a program which performs modular exponentiation 
e.g = (a^b)%m = [a*(a^(b-1))]%m = [a%m * (a^(b-1))%m]%m
C++
=> program- Modular Exponentiation added to c++

Chicken/HelloWorld.chicken
Chicken is an esoteric programming language by Torbjörn Söderstedt, in which "chicken" is the only valid symbol.
It is an Hello World program
----
It is written in Chicken
=> Added Hello World program in Chicken

C++/Merge_Sort (2).cpp
Sorts an array using the merge sort algorithm.
----
C++
=> Merge Sort

Java/HelloWorld123.java
Displays hello world
----
Java
=> AreaAndVolume.java

C++/SudokuRecursion.cpp
=> Solving Sudoku using recursion
